// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

using System;
using System.Numerics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Security;
using Raylib_cs;
using static Raylib_cs.Raylib;

namespace R3D_cs;

// r3d_animation_player.h;

[SuppressUnmanagedCodeSecurity]
public static unsafe partial class R3D
{

    /// <summary>
    /// Creates an animation player for a skeleton and animation library.
    /// <para>
    /// Allocates memory for animation states and pose buffers.
    /// </para>
    /// </summary>
    /// <param name="skeleton">Skeleton to animate.</param>
    /// <param name="animLib">Animation library providing animations.</param>
    /// <returns>Newly created animation player, or a zeroed struct on failure.</returns>
    /// <remarks>
    /// Native: <c>R3D_LoadAnimationPlayer</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_LoadAnimationPlayer")]
    public static partial AnimationPlayer LoadAnimationPlayer(Skeleton skeleton, AnimationLib animLib);

    /// <summary>
    /// Releases all resources used by an animation player.
    /// </summary>
    /// <param name="player">Animation player to unload.</param>
    /// <remarks>
    /// Native: <c>R3D_UnloadAnimationPlayer</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_UnloadAnimationPlayer")]
    public static partial void UnloadAnimationPlayer(AnimationPlayer player);

    /// <summary>
    /// Checks whether an animation player is valid.
    /// </summary>
    /// <param name="player">Animation player to check.</param>
    /// <returns>true if valid, false otherwise.</returns>
    /// <remarks>
    /// Native: <c>R3D_IsAnimationPlayerValid</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_IsAnimationPlayerValid")]
    [return: MarshalAs(UnmanagedType.I1)]
    public static partial bool IsAnimationPlayerValid(AnimationPlayer player);

    /// <summary>
    /// Returns whether an animation is currently playing.
    /// </summary>
    /// <param name="player">Animation player.</param>
    /// <returns>true if playing, false otherwise.</returns>
    /// <remarks>
    /// Native: <c>R3D_IsAnimationPlaying</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_IsAnimationPlaying")]
    [return: MarshalAs(UnmanagedType.I1)]
    public static partial bool IsAnimationPlaying(AnimationPlayer player);

    /// <summary>
    /// Starts playback of the specified animation.
    /// </summary>
    /// <param name="player">Animation player.</param>
    /// <param name="animIndex">Index of the animation to play.</param>
    /// <remarks>
    /// Native: <c>R3D_PlayAnimation</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_PlayAnimation")]
    public static partial void PlayAnimation(ref AnimationPlayer player, int animIndex);

    /// <summary>
    /// Pauses the current animation.
    /// </summary>
    /// <param name="player">Animation player.</param>
    /// <param name="animIndex">Index of the animation to pause.</param>
    /// <remarks>
    /// Native: <c>R3D_PauseAnimation</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_PauseAnimation")]
    public static partial void PauseAnimation(ref AnimationPlayer player);

    /// <summary>
    /// Stops the current animation and clamps its time.
    /// </summary>
    /// <param name="player">Animation player.</param>
    /// <param name="animIndex">Index of the animation to stop.</param>
    /// <remarks>
    /// Native: <c>R3D_StopAnimation</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_StopAnimation")]
    public static partial void StopAnimation(ref AnimationPlayer player);

    /// <summary>
    /// Rewinds the animation to the start or end depending on playback direction.
    /// </summary>
    /// <param name="player">Animation player.</param>
    /// <param name="animIndex">Index of the animation to rewind.</param>
    /// <remarks>
    /// Native: <c>R3D_RewindAnimation</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_RewindAnimation")]
    public static partial void RewindAnimation(ref AnimationPlayer player);

    /// <summary>
    /// Gets the current playback time of an animation.
    /// </summary>
    /// <param name="player">Animation player.</param>
    /// <param name="animIndex">Index of the animation.</param>
    /// <returns>Current time in animation ticks.</returns>
    /// <remarks>
    /// Native: <c>R3D_GetAnimationTime</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_GetAnimationTime")]
    public static partial float GetAnimationTime(AnimationPlayer player, int animIndex);

    /// <summary>
    /// Sets the current playback time of an animation.
    /// </summary>
    /// <param name="player">Animation player.</param>
    /// <param name="animIndex">Index of the animation.</param>
    /// <param name="time">Time in animation ticks.</param>
    /// <remarks>
    /// Native: <c>R3D_SetAnimationTime</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_SetAnimationTime")]
    public static partial void SetAnimationTime(ref AnimationPlayer player, int animIndex, float time);

    /// <summary>
    /// Gets the playback speed of an animation.
    /// </summary>
    /// <param name="player">Animation player.</param>
    /// <param name="animIndex">Index of the animation.</param>
    /// <returns>Current speed (may be negative for reverse playback).</returns>
    /// <remarks>
    /// Native: <c>R3D_GetAnimationSpeed</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_GetAnimationSpeed")]
    public static partial float GetAnimationSpeed(AnimationPlayer player, int animIndex);

    /// <summary>
    /// Sets the playback speed of an animation.
    /// <para>
    /// Negative values play the animation backwards. If setting a negative speed on a stopped animation, consider calling RewindAnimation() to start at the end.
    /// </para>
    /// </summary>
    /// <param name="player">Animation player.</param>
    /// <param name="animIndex">Index of the animation.</param>
    /// <param name="speed">Playback speed.</param>
    /// <remarks>
    /// Native: <c>R3D_SetAnimationSpeed</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_SetAnimationSpeed")]
    public static partial void SetAnimationSpeed(ref AnimationPlayer player, int animIndex, float speed);

    /// <summary>
    /// Gets whether the animation is set to loop.
    /// </summary>
    /// <param name="player">Animation player.</param>
    /// <param name="animIndex">Index of the animation.</param>
    /// <returns>True if looping is enabled.</returns>
    /// <remarks>
    /// Native: <c>R3D_GetAnimationLoop</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_GetAnimationLoop")]
    [return: MarshalAs(UnmanagedType.I1)]
    public static partial bool GetAnimationLoop(AnimationPlayer player, int animIndex);

    /// <summary>
    /// Enables or disables looping for the animation.
    /// </summary>
    /// <param name="player">Animation player.</param>
    /// <param name="animIndex">Index of the animation.</param>
    /// <param name="loop">True to enable looping.</param>
    /// <remarks>
    /// Native: <c>R3D_SetAnimationLoop</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_SetAnimationLoop")]
    public static partial void SetAnimationLoop(ref AnimationPlayer player, int animIndex, [MarshalAs(UnmanagedType.I1)] bool loop);

    /// <summary>
    /// Advances the time of the current animation.
    /// <para>
    /// Updates animation timer based on speed and delta time. Does NOT recalculate the skeleton pose.
    /// </para>
    /// </summary>
    /// <param name="player">Animation player.</param>
    /// <param name="dt">Delta time in seconds.</param>
    /// <remarks>
    /// Native: <c>R3D_AdvanceAnimationTime</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_AdvanceAnimationTime")]
    public static partial void AdvanceAnimationTime(ref AnimationPlayer player, float dt);

    /// <summary>
    /// Computes the local-space transform of each bone for the current animation.
    /// <para>
    /// Samples and interpolates the current animation keyframes at the current playback time, and stores the resulting bone transforms in local space intoplayer-&gt;localPose. Does NOT advance animation time, and does NOT compute model-space transforms.
    /// </para>
    /// </summary>
    /// <param name="player">Animation player whose local pose will be updated.</param>
    /// <remarks>
    /// Native: <c>R3D_ComputeAnimationLocalPose</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_ComputeAnimationLocalPose")]
    public static partial void ComputeAnimationLocalPose(ref AnimationPlayer player);

    /// <summary>
    /// Computes the model-space transform of each bone from the current local pose.
    /// <para>
    /// Traverses the bone hierarchy and accumulates local transforms into model-space matrices, stored intoplayer-&gt;modelPose. This assumesplayer-&gt;localPose is already up-to-date. Does NOT sample animation keyframes, and does NOT advance animation time.
    /// </para>
    /// </summary>
    /// <param name="player">Animation player whose model pose will be updated.</param>
    /// <remarks>
    /// Native: <c>R3D_ComputeAnimationModelPose</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_ComputeAnimationModelPose")]
    public static partial void ComputeAnimationModelPose(ref AnimationPlayer player);

    /// <summary>
    /// Computes both the local and model-space transforms for the current animation.
    /// <para>
    /// Equivalent to calling R3D_ComputeAnimationLocalPose() followed by R3D_ComputeAnimationModelPose(). Does NOT advance animation time.
    /// </para>
    /// </summary>
    /// <param name="player">Animation player whose local and model poses will be updated.</param>
    /// <remarks>
    /// Native: <c>R3D_ComputeAnimationPose</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_ComputeAnimationPose")]
    public static partial void ComputeAnimationPose(ref AnimationPlayer player);

    /// <summary>
    /// Computes the final skinning matrices and uploads them to the GPU.
    /// <para>
    /// Multiplies each bone's model-space transform by its inverse bind matrix to produce the skinning matrices, then uploads them to the GPU skin texture. This assumesplayer-&gt;modelPose is already up-to-date.
    /// </para>
    /// </summary>
    /// <param name="player">Animation player whose skinning matrices will be uploaded.</param>
    /// <remarks>
    /// Native: <c>R3D_UploadAnimationPose</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_UploadAnimationPose")]
    public static partial void UploadAnimationPose(ref AnimationPlayer player);

    /// <summary>
    /// Updates the animation player: calculates and upload the current pose pose, then advances time.
    /// <para>
    /// Equivalent to calling R3D_ComputeAnimationLocalPose() followed by R3D_ComputeAnimationModelPose() and R3D_AdvanceAnimationTime().
    /// </para>
    /// </summary>
    /// <param name="player">Animation player.</param>
    /// <param name="dt">Delta time in seconds.</param>
    /// <remarks>
    /// Native: <c>R3D_UpdateAnimationPlayer</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_UpdateAnimationPlayer")]
    public static partial void UpdateAnimationPlayer(ref AnimationPlayer player, float dt);

}
