// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

using System;
using System.Numerics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Security;
using Raylib_cs;
using static Raylib_cs.Raylib;

namespace R3D_cs;

// r3d_camera.h;

[SuppressUnmanagedCodeSecurity]
public static unsafe partial class R3D
{

    /// <summary>
    /// Creates an R3D camera from a raylib camera.
    /// <para>
    /// The camera position, orientation, field of view and projection mode are derived from the given raylib camera.
    /// </para>
    /// <para>
    /// Since raylib's Camera3D does not store near/far clipping planes or layer masks, the near/far planes are initialized from the current rlgl culling distances, while the layer mask is set to the default R3D camera layer mask.
    /// </para>
    /// </summary>
    /// <param name="camera">Raylib camera to convert.</param>
    /// <returns>Converted R3D camera.</returns>
    /// <remarks>
    /// Native: <c>R3D_CameraFromRL</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_CameraFromRL")]
    public static partial Camera CameraFromRL(Camera3D camera);

    /// <summary>
    /// Converts an R3D camera to a raylib camera.
    /// <para>
    /// The raylib target/up vectors are derived from the camera quaternion. Near/far clipping planes and layer masks are not represented by Camera3D.
    /// </para>
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_CameraToRL</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_CameraToRL")]
    public static partial Camera3D CameraToRL(Camera camera);

    /// <summary>
    /// Sets the camera orientation so it looks at a target point.
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_CameraLookAt</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_CameraLookAt")]
    public static partial void CameraLookAt(ref Camera camera, Vector3 target, Vector3 up);

    /// <summary>
    /// Returns the camera forward direction in world space.
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_GetCameraForward</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_GetCameraForward")]
    public static partial Vector3 GetCameraForward(Camera camera);

    /// <summary>
    /// Returns the camera right direction in world space.
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_GetCameraRight</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_GetCameraRight")]
    public static partial Vector3 GetCameraRight(Camera camera);

    /// <summary>
    /// Returns the camera up direction in world space.
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_GetCameraUp</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_GetCameraUp")]
    public static partial Vector3 GetCameraUp(Camera camera);

    /// <summary>
    /// Returns the camera view matrix.
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_GetCameraView</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_GetCameraView")]
    public static partial Matrix4x4 GetCameraView(Camera camera);

    /// <summary>
    /// Returns the camera projection matrix.
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_GetCameraProj</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_GetCameraProj")]
    public static partial Matrix4x4 GetCameraProj(Camera camera, double aspect);

    /// <summary>
    /// Returns the combined view-projection matrix.
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_GetCameraViewProj</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_GetCameraViewProj")]
    public static partial Matrix4x4 GetCameraViewProj(Camera camera, double aspect);

    /// <summary>
    /// Moves the camera in world space.
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_MoveCamera</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_MoveCamera")]
    public static partial void MoveCamera(ref Camera camera, Vector3 delta);

    /// <summary>
    /// Moves the camera in local space.
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_MoveCameraLocal</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_MoveCameraLocal")]
    public static partial void MoveCameraLocal(ref Camera camera, Vector3 delta);

    /// <summary>
    /// Rotates the camera using a quaternion.
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_CameraRotate</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_CameraRotate")]
    public static partial void CameraRotate(ref Camera camera, Quaternion rotation);

    /// <summary>
    /// Rotates the camera around its local X axis.
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_CameraPitch</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_CameraPitch")]
    public static partial void CameraPitch(ref Camera camera, float angle);

    /// <summary>
    /// Rotates the camera around its local Y axis.
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_CameraYaw</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_CameraYaw")]
    public static partial void CameraYaw(ref Camera camera, float angle);

    /// <summary>
    /// Rotates the camera around its local Z axis.
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_CameraRoll</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_CameraRoll")]
    public static partial void CameraRoll(ref Camera camera, float angle);

    /// <summary>
    /// Replaces the camera culling mask.
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_SetCameraCullMask</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_SetCameraCullMask")]
    public static partial void SetCameraCullMask(ref Camera camera, Layer cullMask);

    /// <summary>
    /// Enables one or more layers in the camera culling mask.
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_EnableCameraCullLayers</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_EnableCameraCullLayers")]
    public static partial void EnableCameraCullLayers(ref Camera camera, Layer layerMask);

    /// <summary>
    /// Disables one or more layers from the camera culling mask.
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_DisableCameraCullLayers</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_DisableCameraCullLayers")]
    public static partial void DisableCameraCullLayers(ref Camera camera, Layer layerMask);

    /// <summary>
    /// Toggles one or more layers in the camera culling mask.
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_ToggleCameraCullLayers</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_ToggleCameraCullLayers")]
    public static partial void ToggleCameraCullLayers(ref Camera camera, Layer layerMask);

    /// <summary>
    /// Checks whether at least one object layer is visible to the camera.
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_IsCameraLayerVisible</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_IsCameraLayerVisible")]
    [return: MarshalAs(UnmanagedType.I1)]
    public static partial bool IsCameraLayerVisible(Camera camera, Layer layerMask);

}
