// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

using System;
using System.Numerics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Security;
using Raylib_cs;
using static Raylib_cs.Raylib;

namespace R3D_cs;

// r3d_ambient_map.h;

[SuppressUnmanagedCodeSecurity]
public static unsafe partial class R3D
{

    /// <summary>
    /// Loads a ambient map from an image file.
    /// <para>
    /// The layout parameter tells how faces are arranged inside the source image.
    /// </para>
    /// </summary>
    /// <seealso>R3D_LoadAmbientMap</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_LoadAmbientMap", StringMarshalling = StringMarshalling.Utf8)]
    public static partial AmbientMap LoadAmbientMap(string fileName, CubemapLayout layout, AmbientFlags flags);

    /// <summary>
    /// Builds a ambient map from an existing Image.
    /// <para>
    /// Same behavior as R3D_LoadAmbientMap(), but without loading from disk.
    /// </para>
    /// </summary>
    /// <seealso>R3D_LoadAmbientMapFromImage</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_LoadAmbientMapFromImage")]
    public static partial AmbientMap LoadAmbientMapFromImage(Image image, CubemapLayout layout, AmbientFlags flags);

    /// <summary>
    /// Generates an ambient map from a cubemap.
    /// <para>
    /// The source cubemap should usually be an HDR sky/environment.
    /// </para>
    /// <para>
    /// Depending on the provided flags, this function:
    /// <list type="bullet">
    /// <item><description>convolves the cubemap into diffuse irradiance</description></item>
    /// <item><description>builds a mipmapped prefiltered cubemap for reflections</description></item>
    /// </list>
    /// </para>
    /// </summary>
    /// <param name="cubemap">Source cubemap (environment / sky).</param>
    /// <param name="flags">Which components to generate (irradiance, reflection, or both).</param>
    /// <returns>A fully initialized ambient map.</returns>
    /// <seealso>R3D_GenAmbientMap</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_GenAmbientMap")]
    public static partial AmbientMap GenAmbientMap(Cubemap cubemap, AmbientFlags flags);

    /// <summary>
    /// Frees the textures used by an ambient map.
    /// <para>
    /// After this call, the ambient map is no longer valid.
    /// </para>
    /// </summary>
    /// <seealso>R3D_UnloadAmbientMap</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_UnloadAmbientMap")]
    public static partial void UnloadAmbientMap(AmbientMap ambientMap);

    /// <summary>
    /// Rebuilds an existing ambient map from a new cubemap.
    /// <para>
    /// Use this when the environment changes dynamically (time of day, weather, interior/exterior transitions, etc).
    /// </para>
    /// <para>
    /// Only the components enabled in `ambientMap.flags` are regenerated.
    /// </para>
    /// </summary>
    /// <param name="ambientMap">Existing ambient map to update.</param>
    /// <param name="cubemap">New cubemap source.</param>
    /// <seealso>R3D_UpdateAmbientMap</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_UpdateAmbientMap")]
    public static partial void UpdateAmbientMap(AmbientMap ambientMap, Cubemap cubemap);

}
