// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

using System;
using System.Numerics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Security;
using Raylib_cs;
using static Raylib_cs.Raylib;

namespace R3D_cs;

// r3d_surface_shader.h;

[SuppressUnmanagedCodeSecurity]
public static unsafe partial class R3D
{

    /// <summary>
    /// Loads a surface shader from a file.
    /// <para>
    /// The shader must define at least one entry point: `void vertex()` or `void fragment()`. It can define either one or both.
    /// </para>
    /// </summary>
    /// <param name="filePath">Path to the shader source file.</param>
    /// <returns>Pointer to the loaded surface shader, or NULL on failure.</returns>
    /// <remarks>
    /// Native: <c>R3D_LoadSurfaceShader</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_LoadSurfaceShader", StringMarshalling = StringMarshalling.Utf8)]
    public static partial SurfaceShader LoadSurfaceShader(string filePath);

    /// <summary>
    /// Loads a surface shader from a source code string in memory.
    /// <para>
    /// The shader must define at least one entry point: `void vertex()` or `void fragment()`. It can define either one or both.
    /// </para>
    /// </summary>
    /// <param name="code">Null-terminated shader source code.</param>
    /// <returns>Pointer to the loaded surface shader, or NULL on failure.</returns>
    /// <remarks>
    /// Native: <c>R3D_LoadSurfaceShaderFromMemory</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_LoadSurfaceShaderFromMemory", StringMarshalling = StringMarshalling.Utf8)]
    public static partial SurfaceShader LoadSurfaceShaderFromMemory(string code);

    /// <summary>
    /// Creates an alias of an existing surface shader.
    /// <para>
    /// The alias shares the same compiled program as the original but holds its own independent uniform and sampler state, allowing the same shader to be used multiple times within a single frame with different values.
    /// </para>
    /// <para>
    /// Uniform and sampler state is copied from the original at the moment this function is called, not from the shader source defaults. Any values set on the original after compilation but before this call will be reflected in the alias; values set afterward will not.
    /// </para>
    /// </summary>
    /// <param name="shader">The original surface shader to alias.</param>
    /// <returns>Pointer to the alias, or NULL on failure.</returns>
    /// <remarks>
    /// The alias does not own the program. Always unload all aliases before unloading the original, or the alias program references become dangling.
    /// Native: <c>R3D_LoadSurfaceShaderAlias</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_LoadSurfaceShaderAlias")]
    public static partial SurfaceShader LoadSurfaceShaderAlias(SurfaceShader shader);

    /// <summary>
    /// Unloads and destroys a surface shader.
    /// <para>
    /// If the shader owns its program shaders (i.e. it was created withR3D_LoadSurfaceShader orR3D_LoadSurfaceShaderFromMemory), they are deleted. Aliases created from this shader viaR3D_LoadSurfaceShaderAlias must be unloaded beforehand, as they share the same programs and will be left with dangling references.
    /// </para>
    /// </summary>
    /// <param name="shader">Surface shader to unload.</param>
    /// <remarks>
    /// Native: <c>R3D_UnloadSurfaceShader</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_UnloadSurfaceShader")]
    public static partial void UnloadSurfaceShader(SurfaceShader shader);

    /// <summary>
    /// Sets a uniform value for the current frame.
    /// <para>
    /// Once a uniform is set, it remains valid for the all frames. If an uniform is set multiple times during the same frame, the last value defined before R3D_End() is used.
    /// </para>
    /// <para>
    /// Supported types: bool, int, float, ivec2, ivec3, ivec4, vec2, vec3, vec4, mat2, mat3, mat4
    /// </para>
    /// </summary>
    /// <param name="shader">Target surface shader. May be NULL. In that case, the call is ignored and a warning is logged.</param>
    /// <param name="name">Name of the uniform. Must not be NULL.</param>
    /// <param name="value">Pointer to the uniform value. Must not be NULL.</param>
    /// <remarks>
    /// <b>Warning:</b>
    /// Boolean values are read as 4 bytes.
    /// Native: <c>R3D_SetSurfaceShaderUniform</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_SetSurfaceShaderUniform", StringMarshalling = StringMarshalling.Utf8)]
    public static partial void SetSurfaceShaderUniform(SurfaceShader shader, string name, void* value);

    /// <summary>
    /// Sets a texture sampler for the current frame.
    /// <para>
    /// Once a sampler is set, it remains valid for all frames. If a sampler is set multiple times during the same frame, the last value defined before R3D_End() is used.
    /// </para>
    /// <para>
    /// Supported samplers: sampler1D, sampler2D, sampler3D, samplerCube
    /// </para>
    /// </summary>
    /// <param name="shader">Target surface shader. May be NULL. In that case, the call is ignored and a warning is logged.</param>
    /// <param name="name">Name of the sampler uniform. Must not be NULL.</param>
    /// <param name="texture">Texture to bind to the sampler.</param>
    /// <remarks>
    /// Native: <c>R3D_SetSurfaceShaderSampler</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_SetSurfaceShaderSampler", StringMarshalling = StringMarshalling.Utf8)]
    public static partial void SetSurfaceShaderSampler(SurfaceShader shader, string name, Texture2D texture);

}
