// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

using System;
using System.Numerics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Security;
using Raylib_cs;
using static Raylib_cs.Raylib;

namespace R3D_cs;

// r3d_cubemap.h;

[SuppressUnmanagedCodeSecurity]
public static unsafe partial class R3D
{

    /// <summary>
    /// Loads a cubemap from an image file.
    /// <para>
    /// The layout parameter tells how faces are arranged inside the source image.
    /// </para>
    /// </summary>
    /// <seealso>R3D_LoadCubemap</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_LoadCubemap", StringMarshalling = StringMarshalling.Utf8)]
    public static partial Cubemap LoadCubemap(string fileName, CubemapLayout layout);

    /// <summary>
    /// Builds a cubemap from an existing Image.
    /// <para>
    /// Same behavior as R3D_LoadCubemap(), but without loading from disk.
    /// </para>
    /// </summary>
    /// <seealso>R3D_LoadCubemapFromImage</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_LoadCubemapFromImage")]
    public static partial Cubemap LoadCubemapFromImage(Image image, CubemapLayout layout);

    /// <summary>
    /// Generates a procedural sky cubemap.
    /// <para>
    /// Creates a GPU cubemap with procedural gradient sky and sun rendering. The cubemap is ready for use as environment map or IBL source.
    /// </para>
    /// </summary>
    /// <seealso>R3D_GenCubemapSky</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_GenCubemapSky")]
    public static partial Cubemap GenCubemapSky(int size, CubemapSky @params);

    /// <summary>
    /// Releases GPU resources associated with a cubemap.
    /// </summary>
    /// <seealso>R3D_UnloadCubemap</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_UnloadCubemap")]
    public static partial void UnloadCubemap(Cubemap cubemap);

    /// <summary>
    /// Updates an existing procedural sky cubemap.
    /// <para>
    /// Re-renders the cubemap with new parameters. Faster than unload + generate when animating sky conditions (time of day, weather, etc.).
    /// </para>
    /// </summary>
    /// <seealso>R3D_UpdateCubemapSky</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_UpdateCubemapSky")]
    public static partial void UpdateCubemapSky(ref Cubemap cubemap, CubemapSky @params);

}
