// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

using System;
using System.Numerics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Security;
using Raylib_cs;
using static Raylib_cs.Raylib;

namespace R3D_cs;

// r3d_sky.h;

[SuppressUnmanagedCodeSecurity]
public static unsafe partial class R3D
{

    /// <summary>
    /// Generates a procedural sky cubemap.
    /// <para>
    /// Creates a GPU cubemap with procedural gradient sky and sun rendering. The cubemap is ready for use as environment map or IBL source.
    /// </para>
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_GenProceduralSky</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_GenProceduralSky")]
    public static partial Cubemap GenProceduralSky(int size, ProceduralSky @params);

    /// <summary>
    /// Generates a custom sky cubemap.
    /// <para>
    /// Creates a GPU cubemap rendered using the provided sky shader. The cubemap is ready for use as environment map or IBL source.
    /// </para>
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_GenCustomSky</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_GenCustomSky")]
    public static partial Cubemap GenCustomSky(int size, SkyShader shader);

    /// <summary>
    /// Updates an existing procedural sky cubemap.
    /// <para>
    /// Re-renders the cubemap with new parameters. Faster than unload + generate when animating sky conditions (time of day, weather, etc.).
    /// </para>
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_UpdateProceduralSky</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_UpdateProceduralSky")]
    public static partial void UpdateProceduralSky(ref Cubemap cubemap, ProceduralSky @params);

    /// <summary>
    /// Updates an existing custom sky cubemap.
    /// <para>
    /// Re-renders the cubemap using the provided sky shader. Faster than unload + generate when animating sky conditions or updating shader uniforms (time, clouds, stars, etc.).
    /// </para>
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_UpdateCustomSky</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_UpdateCustomSky")]
    public static partial void UpdateCustomSky(ref Cubemap cubemap, SkyShader shader);

}
