// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

using System;
using System.Numerics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Security;
using Raylib_cs;
using static Raylib_cs.Raylib;

namespace R3D_cs;

// r3d_model.h;

[SuppressUnmanagedCodeSecurity]
public static unsafe partial class R3D
{

    /// <summary>
    /// Load a 3D model from a file.
    /// <para>
    /// Loads a 3D model from the specified file path. Supports various 3D file formats and automatically parses meshes, materials, and texture references.
    /// </para>
    /// </summary>
    /// <param name="filePath">Path to the 3D model file to load.</param>
    /// <returns>Loaded model structure containing meshes and materials.</returns>
    /// <seealso>R3D_LoadModel</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_LoadModel", StringMarshalling = StringMarshalling.Utf8)]
    public static partial Model LoadModel(string filePath);

    /// <summary>
    /// Load a 3D model from a file with import flags.
    /// <para>
    /// Extended version of R3D_LoadModel() allowing control over the import process through additional flags.
    /// </para>
    /// </summary>
    /// <param name="filePath">Path to the 3D model file to load.</param>
    /// <param name="flags">Importer behavior flags.</param>
    /// <returns>Loaded model structure containing meshes and materials.</returns>
    /// <seealso>R3D_LoadModelEx</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_LoadModelEx", StringMarshalling = StringMarshalling.Utf8)]
    public static partial Model LoadModelEx(string filePath, ImportFlags flags);

    /// <summary>
    /// Load a 3D model from memory buffer.
    /// <para>
    /// Loads a 3D model from a memory buffer containing the file data. Useful for loading models from embedded resources or network streams.
    /// </para>
    /// </summary>
    /// <param name="data">Pointer to the memory buffer containing the model data.</param>
    /// <param name="size">Size of the data buffer in bytes.</param>
    /// <param name="hint">Hint on the model format (can be NULL).</param>
    /// <returns>Loaded model structure containing meshes and materials.</returns>
    /// <remarks>
    /// External dependencies (e.g., textures or linked resources) are not supported. The model data must be fully self-contained. Use embedded formats like .glb to ensure compatibility.
    /// </remarks>
    /// <seealso>R3D_LoadModelFromMemory</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_LoadModelFromMemory", StringMarshalling = StringMarshalling.Utf8)]
    public static partial Model LoadModelFromMemory(void* data, uint size, string hint);

    /// <summary>
    /// Load a 3D model from a memory buffer with import flags.
    /// <para>
    /// Extended version of R3D_LoadModelFromMemory() allowing control over the import process through additional flags.
    /// </para>
    /// </summary>
    /// <param name="data">Pointer to the memory buffer containing the model data.</param>
    /// <param name="size">Size of the data buffer in bytes.</param>
    /// <param name="hint">Hint on the model format (can be NULL).</param>
    /// <param name="flags">Importer behavior flags.</param>
    /// <returns>Loaded model structure containing meshes and materials.</returns>
    /// <remarks>
    /// External dependencies (e.g., textures or linked resources) are not supported. The model data must be fully self-contained.
    /// </remarks>
    /// <seealso>R3D_LoadModelFromMemoryEx</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_LoadModelFromMemoryEx", StringMarshalling = StringMarshalling.Utf8)]
    public static partial Model LoadModelFromMemoryEx(void* data, uint size, string hint, ImportFlags flags);

    /// <summary>
    /// Load a 3D model from an existing importer.
    /// <para>
    /// Creates a model from a previously loaded importer instance. This avoids re-importing the source file.
    /// </para>
    /// </summary>
    /// <param name="importer">Importer instance to extract the model from.</param>
    /// <returns>Loaded model structure containing meshes and materials.</returns>
    /// <seealso>R3D_LoadModelFromImporter</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_LoadModelFromImporter")]
    public static partial Model LoadModelFromImporter(Importer* importer);

    /// <summary>
    /// Unload a model and optionally its materials.
    /// <para>
    /// Frees all memory associated with a model, including its meshes. Materials can be optionally unloaded as well.
    /// </para>
    /// </summary>
    /// <param name="model">The model to be unloaded.</param>
    /// <param name="unloadMaterials">If true, also unloads all materials associated with the model. Set to false if textures are still being used elsewhere to avoid freeing shared resources.</param>
    /// <seealso>R3D_UnloadModel</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_UnloadModel")]
    public static partial void UnloadModel(Model model, [MarshalAs(UnmanagedType.I1)] bool unloadMaterials);

}
