// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

using System;
using System.Numerics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Security;
using Raylib_cs;
using static Raylib_cs.Raylib;

namespace R3D_cs;

// r3d_animation.h;

[SuppressUnmanagedCodeSecurity]
public static unsafe partial class R3D
{

    /// <summary>
    /// Loads animations from a model file.
    /// </summary>
    /// <param name="filePath">Path to the model file containing animations.</param>
    /// <param name="targetFrameRate">Desired frame rate (FPS) for sampling the animations.</param>
    /// <returns>Pointer to an array of R3D_Animation, or NULL on failure.</returns>
    /// <remarks>
    /// Free the returned array using R3D_UnloadAnimationLib().
    /// </remarks>
    /// <seealso>R3D_LoadAnimationLib</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_LoadAnimationLib", StringMarshalling = StringMarshalling.Utf8)]
    public static partial AnimationLib LoadAnimationLib(string filePath);

    /// <summary>
    /// Loads animations from memory data.
    /// </summary>
    /// <param name="data">Pointer to memory buffer containing model animation data.</param>
    /// <param name="size">Size of the buffer in bytes.</param>
    /// <param name="hint">Hint on the model format (can be NULL).</param>
    /// <param name="targetFrameRate">Desired frame rate (FPS) for sampling the animations.</param>
    /// <returns>Pointer to an array of R3D_Animation, or NULL on failure.</returns>
    /// <remarks>
    /// Free the returned array using R3D_UnloadAnimationLib().
    /// </remarks>
    /// <seealso>R3D_LoadAnimationLibFromMemory</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_LoadAnimationLibFromMemory", StringMarshalling = StringMarshalling.Utf8)]
    public static partial AnimationLib LoadAnimationLibFromMemory(void* data, uint size, string hint);

    /// <summary>
    /// Loads animations from an existing importer.
    /// </summary>
    /// <param name="importer">Importer instance containing animation data.</param>
    /// <returns>Pointer to an array of R3D_Animation, or NULL on failure.</returns>
    /// <remarks>
    /// Free the returned array using R3D_UnloadAnimationLib().
    /// </remarks>
    /// <seealso>R3D_LoadAnimationLibFromImporter</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_LoadAnimationLibFromImporter")]
    public static partial AnimationLib LoadAnimationLibFromImporter(Importer* importer);

    /// <summary>
    /// Releases all resources associated with an animation library.
    /// </summary>
    /// <param name="animLib">Animation library to unload.</param>
    /// <seealso>R3D_UnloadAnimationLib</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_UnloadAnimationLib")]
    public static partial void UnloadAnimationLib(AnimationLib animLib);

    /// <summary>
    /// Returns the index of an animation by name.
    /// </summary>
    /// <param name="animLib">Animation library to search.</param>
    /// <param name="name">Name of the animation (case-sensitive).</param>
    /// <returns>Zero-based index if found, or -1 if not found.</returns>
    /// <seealso>R3D_GetAnimationIndex</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_GetAnimationIndex", StringMarshalling = StringMarshalling.Utf8)]
    public static partial int GetAnimationIndex(AnimationLib animLib, string name);

    /// <summary>
    /// Retrieves an animation by name.
    /// </summary>
    /// <param name="animLib">Animation library to search.</param>
    /// <param name="name">Name of the animation (case-sensitive).</param>
    /// <returns>Pointer to the animation, or NULL if not found.</returns>
    /// <seealso>R3D_GetAnimation</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_GetAnimation", StringMarshalling = StringMarshalling.Utf8)]
    public static partial Animation* GetAnimation(AnimationLib animLib, string name);

}
