// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

using System;
using System.Numerics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Security;
using Raylib_cs;
using static Raylib_cs.Raylib;

namespace R3D_cs;

// r3d_instance.h;

[SuppressUnmanagedCodeSecurity]
public static unsafe partial class R3D
{

    /// <summary>
    /// Create instance buffers on the GPU.
    /// </summary>
    /// <param name="capacity">Max instances.</param>
    /// <param name="flags">Attribute mask to allocate.</param>
    /// <returns>Initialized instance buffer.</returns>
    /// <remarks>
    /// Native: <c>R3D_LoadInstanceBuffer</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_LoadInstanceBuffer")]
    public static partial InstanceBuffer LoadInstanceBuffer(int capacity, InstanceFlags flags);

    /// <summary>
    /// Destroy all GPU buffers owned by this instance buffer.
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_UnloadInstanceBuffer</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_UnloadInstanceBuffer")]
    public static partial void UnloadInstanceBuffer(InstanceBuffer buffer);

    /// <summary>
    /// Upload a contiguous range of instance data.
    /// </summary>
    /// <param name="flag">Attribute being updated (single bit).</param>
    /// <param name="offset">First instance index.</param>
    /// <param name="count">Number of instances.</param>
    /// <param name="data">Source pointer.</param>
    /// <remarks>
    /// Native: <c>R3D_UploadInstances</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_UploadInstances")]
    public static partial void UploadInstances(InstanceBuffer buffer, InstanceFlags flag, int offset, int count, IntPtr data);

    /// <summary>
    /// Map an attribute buffer for CPU write access.
    /// </summary>
    /// <param name="flag">Attribute to map (single bit).</param>
    /// <returns>Writable pointer, or NULL on error.</returns>
    /// <remarks>
    /// Native: <c>R3D_MapInstances</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_MapInstances")]
    public static partial IntPtr MapInstances(InstanceBuffer buffer, InstanceFlags flag);

    /// <summary>
    /// Unmap one or more previously mapped attribute buffers.
    /// </summary>
    /// <param name="flags">Bitmask of attributes to unmap.</param>
    /// <remarks>
    /// Native: <c>R3D_UnmapInstances</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_UnmapInstances")]
    public static partial void UnmapInstances(InstanceBuffer buffer, InstanceFlags flags);

}
