// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

using System;
using System.Numerics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Security;
using Raylib_cs;
using static Raylib_cs.Raylib;

namespace R3D_cs;

// r3d_screen_shader.h;

[SuppressUnmanagedCodeSecurity]
public static unsafe partial class R3D
{

    /// <summary>
    /// Loads a screen shader from a file.
    /// <para>
    /// The shader must define a single entry point: `void fragment()`. Any other entry point, such as `vertex()`, or any varyings will be ignored.
    /// </para>
    /// </summary>
    /// <param name="filePath">Path to the shader source file.</param>
    /// <returns>Pointer to the loaded screen shader, or NULL on failure.</returns>
    /// <remarks>
    /// Native: <c>R3D_LoadScreenShader</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_LoadScreenShader", StringMarshalling = StringMarshalling.Utf8)]
    public static partial ScreenShader LoadScreenShader(string filePath);

    /// <summary>
    /// Loads a screen shader from a source code string in memory.
    /// <para>
    /// The shader must define a single entry point: `void fragment()`. Any other entry point, such as `vertex()`, or any varyings will be ignored.
    /// </para>
    /// </summary>
    /// <param name="code">Null-terminated shader source code.</param>
    /// <returns>Pointer to the loaded screen shader, or NULL on failure.</returns>
    /// <remarks>
    /// Native: <c>R3D_LoadScreenShaderFromMemory</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_LoadScreenShaderFromMemory", StringMarshalling = StringMarshalling.Utf8)]
    public static partial ScreenShader LoadScreenShaderFromMemory(string code);

    /// <summary>
    /// Creates an alias of an existing screen shader.
    /// <para>
    /// The alias shares the same compiled program as the original but holds its own independent uniform and sampler state. Typical use cases include pre-configuring aliases for distinct effects (e.g. different convolution kernels), or running the same shader multiple times in a post-process chain with different parameters at each pass.
    /// </para>
    /// <para>
    /// Uniform and sampler state is copied from the original at the moment this function is called, not from the shader source defaults. Any values set on the original after compilation but before this call will be reflected in the alias; values set afterward will not.
    /// </para>
    /// </summary>
    /// <param name="shader">The original screen shader to alias.</param>
    /// <returns>Pointer to the alias, or NULL on failure.</returns>
    /// <remarks>
    /// The alias does not own the program. Always unload all aliases before unloading the original, or the alias program references become dangling.
    /// Native: <c>R3D_LoadScreenShaderAlias</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_LoadScreenShaderAlias")]
    public static partial ScreenShader LoadScreenShaderAlias(ScreenShader shader);

    /// <summary>
    /// Unloads and destroys a screen shader.
    /// <para>
    /// If the shader owns its program shaders (i.e. it was created withR3D_LoadScreenShader orR3D_LoadScreenShaderFromMemory), they are deleted. Aliases created from this shader viaR3D_LoadScreenShaderAlias must be unloaded beforehand, as they share the same programs and will be left with dangling references.
    /// </para>
    /// </summary>
    /// <param name="shader">Screen shader to unload.</param>
    /// <remarks>
    /// Native: <c>R3D_UnloadScreenShader</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_UnloadScreenShader")]
    public static partial void UnloadScreenShader(ScreenShader shader);

    /// <summary>
    /// Sets a uniform value for the current frame.
    /// <para>
    /// Once a uniform is set, it remains valid for the all frames. If an uniform is set multiple times during the same frame, the last value defined before R3D_End() is used.
    /// </para>
    /// <para>
    /// Supported types: bool, int, float, ivec2, ivec3, ivec4, vec2, vec3, vec4, mat2, mat3, mat4
    /// </para>
    /// </summary>
    /// <param name="shader">Target screen shader. May be NULL. In that case, the call is ignored and a warning is logged.</param>
    /// <param name="name">Name of the uniform. Must not be NULL.</param>
    /// <param name="value">Pointer to the uniform value. Must not be NULL.</param>
    /// <remarks>
    /// <b>Warning:</b>
    /// Boolean values are read as 4 bytes.
    /// Native: <c>R3D_SetScreenShaderUniform</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_SetScreenShaderUniform", StringMarshalling = StringMarshalling.Utf8)]
    public static partial void SetScreenShaderUniform(ScreenShader shader, string name, void* value);

    /// <summary>
    /// Sets a texture sampler for the current frame.
    /// <para>
    /// Once a sampler is set, it remains valid for all frames. If a sampler is set multiple times during the same frame, the last value defined before R3D_End() is used.
    /// </para>
    /// <para>
    /// Supported samplers: sampler1D, sampler2D, sampler3D, samplerCube
    /// </para>
    /// </summary>
    /// <param name="shader">Target screen shader. May be NULL. In that case, the call is ignored and a warning is logged.</param>
    /// <param name="name">Name of the sampler uniform. Must not be NULL.</param>
    /// <param name="texture">Texture to bind to the sampler.</param>
    /// <remarks>
    /// Native: <c>R3D_SetScreenShaderSampler</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_SetScreenShaderSampler", StringMarshalling = StringMarshalling.Utf8)]
    public static partial void SetScreenShaderSampler(ScreenShader shader, string name, Texture2D texture);

    /// <summary>
    /// Sets the screen shader chain for a given stage.
    /// <para>
    /// Screen shaders are executed in the order provided. The maximum number of shaders per stage is `R3D_MAX_SCREEN_SHADERS`; extra entries are ignored and a warning is emitted.
    /// </para>
    /// <para>
    /// Shader pointers are copied internally, so the original array may be modified or freed after the call. NULL entries are allowed and skipped safely.
    /// </para>
    /// <para>
    /// Calling this function replaces the previous chain for the selected stage. To clear a stage, pass `shaders = NULL` or `count = 0`.
    /// </para>
    /// </summary>
    /// <param name="stage">Screen shader stage to configure.</param>
    /// <param name="shaders">Array of pointers to R3D_ScreenShader objects.</param>
    /// <param name="count">Number of shaders in the array.</param>
    /// <remarks>
    /// Native: <c>R3D_SetScreenShaderChain</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_SetScreenShaderChain")]
    public static partial void SetScreenShaderChain(ScreenShaderStage stage, ScreenShader* shaders, int count);

}
