// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

using System;
using System.Numerics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Security;
using Raylib_cs;
using static Raylib_cs.Raylib;

namespace R3D_cs;

// r3d_lighting.h;

[SuppressUnmanagedCodeSecurity]
public static unsafe partial class R3D
{

    /// <summary>
    /// Creates a new light of the specified type.
    /// <para>
    /// This function creates a light of the given type. The light must be destroyed manually when no longer needed by calling `R3D_DestroyLight`.
    /// </para>
    /// </summary>
    /// <param name="type">The type of light to create (directional, spot or omni-directional).</param>
    /// <returns>The ID of the created light.</returns>
    /// <seealso>R3D_CreateLight</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_CreateLight")]
    public static partial Light CreateLight(LightType type);

    /// <summary>
    /// Destroys the specified light.
    /// <para>
    /// This function deallocates the resources associated with the light and makes the light ID invalid. It must be called after the light is no longer needed.
    /// </para>
    /// </summary>
    /// <param name="id">The ID of the light to destroy.</param>
    /// <seealso>R3D_DestroyLight</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_DestroyLight")]
    public static partial void DestroyLight(Light id);

    /// <summary>
    /// Checks if a light exists.
    /// <para>
    /// This function checks if the specified light ID is valid and if the light exists.
    /// </para>
    /// </summary>
    /// <param name="id">The ID of the light to check.</param>
    /// <returns>True if the light exists, false otherwise.</returns>
    /// <seealso>R3D_IsLightExist</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_IsLightExist")]
    [return: MarshalAs(UnmanagedType.I1)]
    public static partial bool IsLightExist(Light id);

    /// <summary>
    /// Gets the type of a light.
    /// <para>
    /// This function returns the type of the specified light (directional, spot or omni-directional).
    /// </para>
    /// </summary>
    /// <param name="id">The ID of the light.</param>
    /// <returns>The type of the light.</returns>
    /// <seealso>R3D_GetLightType</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_GetLightType")]
    public static partial LightType GetLightType(Light id);

    /// <summary>
    /// Checks if a light is active.
    /// <para>
    /// This function checks whether the specified light is currently active (enabled or disabled).
    /// </para>
    /// </summary>
    /// <param name="id">The ID of the light to check.</param>
    /// <returns>True if the light is active, false otherwise.</returns>
    /// <seealso>R3D_IsLightActive</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_IsLightActive")]
    [return: MarshalAs(UnmanagedType.I1)]
    public static partial bool IsLightActive(Light id);

    /// <summary>
    /// Toggles the state of a light (active or inactive).
    /// <para>
    /// This function toggles the state of the specified light, turning it on if it is off, or off if it is on.
    /// </para>
    /// </summary>
    /// <param name="id">The ID of the light to toggle.</param>
    /// <seealso>R3D_ToggleLight</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_ToggleLight")]
    public static partial void ToggleLight(Light id);

    /// <summary>
    /// Sets the active state of a light.
    /// <para>
    /// This function allows manually turning a light on or off by specifying its active state.
    /// </para>
    /// </summary>
    /// <param name="id">The ID of the light to set the active state for.</param>
    /// <param name="active">True to activate the light, false to deactivate it.</param>
    /// <seealso>R3D_SetLightActive</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_SetLightActive")]
    public static partial void SetLightActive(Light id, [MarshalAs(UnmanagedType.I1)] bool active);

    /// <summary>
    /// Gets the color of a light.
    /// <para>
    /// This function retrieves the color of the specified light as a `Color` structure.
    /// </para>
    /// </summary>
    /// <param name="id">The ID of the light.</param>
    /// <returns>The color of the light as a `Color` structure.</returns>
    /// <seealso>R3D_GetLightColor</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_GetLightColor")]
    public static partial Color GetLightColor(Light id);

    /// <summary>
    /// Gets the color of a light as a `Vector3`.
    /// <para>
    /// This function retrieves the color of the specified light as a `Vector3`, where each component (x, y, z) represents the RGB values of the light.
    /// </para>
    /// </summary>
    /// <param name="id">The ID of the light.</param>
    /// <returns>The color of the light as a `Vector3`.</returns>
    /// <seealso>R3D_GetLightColorV</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_GetLightColorV")]
    public static partial Vector3 GetLightColorV(Light id);

    /// <summary>
    /// Sets the color of a light.
    /// <para>
    /// This function sets the color of the specified light using a `Color` structure.
    /// </para>
    /// </summary>
    /// <param name="id">The ID of the light.</param>
    /// <param name="color">The new color to set for the light.</param>
    /// <seealso>R3D_SetLightColor</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_SetLightColor")]
    public static partial void SetLightColor(Light id, Color color);

    /// <summary>
    /// Sets the color of a light using a `Vector3`.
    /// <para>
    /// This function sets the color of the specified light using a `Vector3`, where each component (x, y, z) represents the RGB values of the light.
    /// </para>
    /// </summary>
    /// <param name="id">The ID of the light.</param>
    /// <param name="color">The new color to set for the light as a `Vector3`.</param>
    /// <seealso>R3D_SetLightColorV</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_SetLightColorV")]
    public static partial void SetLightColorV(Light id, Vector3 color);

    /// <summary>
    /// Gets the position of a light.
    /// <para>
    /// This function retrieves the position of the specified light. Only applicable to spot lights or omni-lights.
    /// </para>
    /// </summary>
    /// <param name="id">The ID of the light.</param>
    /// <returns>The position of the light as a `Vector3`.</returns>
    /// <seealso>R3D_GetLightPosition</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_GetLightPosition")]
    public static partial Vector3 GetLightPosition(Light id);

    /// <summary>
    /// Sets the position of a light.
    /// <para>
    /// This function sets the position of the specified light. Only applicable to spot lights or omni-lights.
    /// </para>
    /// </summary>
    /// <param name="id">The ID of the light.</param>
    /// <param name="position">The new position to set for the light.</param>
    /// <remarks>
    /// Has no effect for directional lights. If called on a directional light, a warning will be logged.
    /// </remarks>
    /// <seealso>R3D_SetLightPosition</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_SetLightPosition")]
    public static partial void SetLightPosition(Light id, Vector3 position);

    /// <summary>
    /// Gets the direction of a light.
    /// <para>
    /// This function retrieves the direction of the specified light. Only applicable to directional lights or spot lights.
    /// </para>
    /// </summary>
    /// <param name="id">The ID of the light.</param>
    /// <returns>The direction of the light as a `Vector3`.</returns>
    /// <seealso>R3D_GetLightDirection</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_GetLightDirection")]
    public static partial Vector3 GetLightDirection(Light id);

    /// <summary>
    /// Sets the direction of a light.
    /// <para>
    /// This function sets the direction of the specified light. Only applicable to directional lights or spot lights.
    /// </para>
    /// </summary>
    /// <param name="id">The ID of the light.</param>
    /// <param name="direction">The new direction to set for the light. The vector is automatically normalized.</param>
    /// <remarks>
    /// Has no effect for omni-directional lights. If called on an omni-directional light, a warning will be logged.
    /// </remarks>
    /// <seealso>R3D_SetLightDirection</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_SetLightDirection")]
    public static partial void SetLightDirection(Light id, Vector3 direction);

    /// <summary>
    /// Sets the position and direction of a light to look at a target point.
    /// <para>
    /// This function sets both the position and the direction of the specified light, causing it to &quot;look at&quot; a given target point.
    /// </para>
    /// </summary>
    /// <param name="id">The ID of the light.</param>
    /// <param name="position">The position to set for the light.</param>
    /// <param name="target">The point the light should look at.</param>
    /// <remarks>
    /// <list type="bullet">
    /// <item><description>For directional lights, only the direction is updated (position is ignored).</description></item>
    /// <item><description>For omni-directional lights, only the position is updated (direction is not calculated).</description></item>
    /// <item><description>For spot lights, both position and direction are set accordingly.</description></item>
    /// <item><description>This function does **not** emit any warning or log message.</description></item>
    /// </list>
    /// </remarks>
    /// <seealso>R3D_LightLookAt</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_LightLookAt")]
    public static partial void LightLookAt(Light id, Vector3 position, Vector3 target);

    /// <summary>
    /// Gets the energy level of a light.
    /// <para>
    /// This function retrieves the energy level (intensity) of the specified light. Energy typically affects the brightness of the light.
    /// </para>
    /// </summary>
    /// <param name="id">The ID of the light.</param>
    /// <returns>The energy level of the light.</returns>
    /// <seealso>R3D_GetLightEnergy</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_GetLightEnergy")]
    public static partial float GetLightEnergy(Light id);

    /// <summary>
    /// Sets the energy level of a light.
    /// <para>
    /// This function sets the energy (intensity) of the specified light. A higher energy value will result in a brighter light.
    /// </para>
    /// </summary>
    /// <param name="id">The ID of the light.</param>
    /// <param name="energy">The new energy value to set for the light.</param>
    /// <seealso>R3D_SetLightEnergy</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_SetLightEnergy")]
    public static partial void SetLightEnergy(Light id, float energy);

    /// <summary>
    /// Gets the specular intensity of a light.
    /// <para>
    /// This function retrieves the current specular intensity of the specified light. Specular intensity affects how shiny surfaces appear when reflecting the light.
    /// </para>
    /// </summary>
    /// <param name="id">The ID of the light.</param>
    /// <returns>The current specular intensity of the light.</returns>
    /// <seealso>R3D_GetLightSpecular</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_GetLightSpecular")]
    public static partial float GetLightSpecular(Light id);

    /// <summary>
    /// Sets the specular intensity of a light.
    /// <para>
    /// This function sets the specular intensity of the specified light. Higher specular values result in stronger and sharper highlights on reflective surfaces.
    /// </para>
    /// </summary>
    /// <param name="id">The ID of the light.</param>
    /// <param name="specular">The new specular intensity value to set for the light.</param>
    /// <seealso>R3D_SetLightSpecular</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_SetLightSpecular")]
    public static partial void SetLightSpecular(Light id, float specular);

    /// <summary>
    /// Gets the range of a light.
    /// <para>
    /// This function retrieves the range of the specified light, which determines how far the light can affect. Only applicable to spot lights or omni-lights.
    /// </para>
    /// </summary>
    /// <param name="id">The ID of the light.</param>
    /// <returns>The range of the light.</returns>
    /// <seealso>R3D_GetLightRange</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_GetLightRange")]
    public static partial float GetLightRange(Light id);

    /// <summary>
    /// Sets the range parameter of a light.
    /// <para>
    /// For spot and omni lights, this defines the maximum illumination distance. For directional lights, this defines the shadow rendering radius around the camera.
    /// </para>
    /// </summary>
    /// <param name="id">The ID of the light.</param>
    /// <param name="range">The range value to apply.</param>
    /// <seealso>R3D_SetLightRange</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_SetLightRange")]
    public static partial void SetLightRange(Light id, float range);

    /// <summary>
    /// Gets the attenuation factor of a light.
    /// <para>
    /// This function retrieves the attenuation factor of the specified light. Attenuation controls how the intensity of a light decreases with distance. Only applicable to spot lights or omni-lights.
    /// </para>
    /// </summary>
    /// <param name="id">The ID of the light.</param>
    /// <returns>The attenuation factor of the light.</returns>
    /// <seealso>R3D_GetLightAttenuation</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_GetLightAttenuation")]
    public static partial float GetLightAttenuation(Light id);

    /// <summary>
    /// Sets the attenuation factor of a light.
    /// <para>
    /// This function sets the attenuation factor of the specified light. A higher attenuation value causes the light to lose intensity more quickly as the distance increases. For a realistic effect, an attenuation factor of 2.0f is typically used. Only applicable to spot lights or omni-lights.
    /// </para>
    /// </summary>
    /// <param name="id">The ID of the light.</param>
    /// <param name="attenuation">The new attenuation factor to set for the light.</param>
    /// <seealso>R3D_SetLightAttenuation</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_SetLightAttenuation")]
    public static partial void SetLightAttenuation(Light id, float attenuation);

    /// <summary>
    /// Gets the inner cutoff angle of a spotlight.
    /// <para>
    /// This function retrieves the inner cutoff angle of a spotlight. The inner cutoff defines the cone of light where the light is at full intensity.
    /// </para>
    /// </summary>
    /// <param name="id">The ID of the light.</param>
    /// <returns>The inner cutoff angle in degrees of the spotlight.</returns>
    /// <seealso>R3D_GetLightInnerCutOff</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_GetLightInnerCutOff")]
    public static partial float GetLightInnerCutOff(Light id);

    /// <summary>
    /// Sets the inner cutoff angle of a spotlight.
    /// <para>
    /// This function sets the inner cutoff angle of a spotlight. The inner cutoff angle defines the cone where the light is at full intensity. Anything outside this cone starts to fade.
    /// </para>
    /// </summary>
    /// <param name="id">The ID of the light.</param>
    /// <param name="degrees">The new inner cutoff angle in degrees.</param>
    /// <seealso>R3D_SetLightInnerCutOff</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_SetLightInnerCutOff")]
    public static partial void SetLightInnerCutOff(Light id, float degrees);

    /// <summary>
    /// Gets the outer cutoff angle of a spotlight.
    /// <para>
    /// This function retrieves the outer cutoff angle of a spotlight. The outer cutoff defines the outer boundary of the light's cone, where the light starts to fade.
    /// </para>
    /// </summary>
    /// <param name="id">The ID of the light.</param>
    /// <returns>The outer cutoff angle in degrees of the spotlight.</returns>
    /// <seealso>R3D_GetLightOuterCutOff</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_GetLightOuterCutOff")]
    public static partial float GetLightOuterCutOff(Light id);

    /// <summary>
    /// Sets the outer cutoff angle of a spotlight.
    /// <para>
    /// This function sets the outer cutoff angle of a spotlight. The outer cutoff defines the boundary of the light's cone where the light intensity starts to gradually decrease.
    /// </para>
    /// </summary>
    /// <param name="id">The ID of the light.</param>
    /// <param name="degrees">The new outer cutoff angle in degrees.</param>
    /// <seealso>R3D_SetLightOuterCutOff</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_SetLightOuterCutOff")]
    public static partial void SetLightOuterCutOff(Light id, float degrees);

    /// <summary>
    /// Enables shadow rendering for a light.
    /// <para>
    /// Turns on shadow rendering for the light. The engine will allocate a shadow map if needed, or reuse one previously allocated for another light.
    /// </para>
    /// <para>
    /// Shadow map resolutions are fixed: 2048x2048 for spot and point lights, and 4096x4096 for directional lights.
    /// </para>
    /// </summary>
    /// <param name="id">The ID of the light.</param>
    /// <remarks>
    /// Creating too many shadow-casting lights can exhaust GPU memory and potentially crash the graphics driver. Disabling shadows on one light and enabling them on another is free, since existing shadow maps are reused.
    /// </remarks>
    /// <seealso>R3D_EnableShadow</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_EnableShadow")]
    public static partial void EnableShadow(Light id);

    /// <summary>
    /// Disables shadow rendering for a light.
    /// <para>
    /// Turns off shadow rendering for the light. The associated shadow map is kept in memory and may later be reused by another light.
    /// </para>
    /// </summary>
    /// <param name="id">The ID of the light.</param>
    /// <seealso>R3D_DisableShadow</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_DisableShadow")]
    public static partial void DisableShadow(Light id);

    /// <summary>
    /// Checks if shadow casting is enabled for a light.
    /// <para>
    /// This function checks if shadow casting is currently enabled for the specified light.
    /// </para>
    /// </summary>
    /// <param name="id">The ID of the light.</param>
    /// <returns>True if shadow casting is enabled, false otherwise.</returns>
    /// <seealso>R3D_IsShadowEnabled</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_IsShadowEnabled")]
    [return: MarshalAs(UnmanagedType.I1)]
    public static partial bool IsShadowEnabled(Light id);

    /// <summary>
    /// Gets the shadow map update mode of a light.
    /// <para>
    /// This function retrieves the current mode for updating the shadow map of a light. The mode can be:
    /// <list type="bullet">
    /// <item><description>Interval: Updates the shadow map at a fixed interval.</description></item>
    /// <item><description>Continuous: Updates the shadow map continuously.</description></item>
    /// <item><description>Manual: Updates the shadow map manually (via explicit function calls).</description></item>
    /// </list>
    /// </para>
    /// </summary>
    /// <param name="id">The ID of the light.</param>
    /// <returns>The shadow map update mode.</returns>
    /// <seealso>R3D_GetShadowUpdateMode</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_GetShadowUpdateMode")]
    public static partial ShadowUpdateMode GetShadowUpdateMode(Light id);

    /// <summary>
    /// Sets the shadow map update mode of a light.
    /// <para>
    /// This function sets the mode for updating the shadow map of the specified light. The update mode controls when and how often the shadow map is refreshed.
    /// </para>
    /// </summary>
    /// <param name="id">The ID of the light.</param>
    /// <param name="mode">The update mode to set for the shadow map (Interval, Continuous, or Manual).</param>
    /// <seealso>R3D_SetShadowUpdateMode</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_SetShadowUpdateMode")]
    public static partial void SetShadowUpdateMode(Light id, ShadowUpdateMode mode);

    /// <summary>
    /// Gets the frequency of shadow map updates for the interval update mode.
    /// <para>
    /// This function retrieves the frequency (in milliseconds) at which the shadow map should be updated when the interval update mode is enabled. This function is only relevant if the shadow map update mode is set to &quot;Interval&quot;.
    /// </para>
    /// </summary>
    /// <param name="id">The ID of the light.</param>
    /// <returns>The frequency in milliseconds at which the shadow map is updated.</returns>
    /// <seealso>R3D_GetShadowUpdateFrequency</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_GetShadowUpdateFrequency")]
    public static partial int GetShadowUpdateFrequency(Light id);

    /// <summary>
    /// Sets the frequency of shadow map updates for the interval update mode.
    /// <para>
    /// This function sets the frequency (in milliseconds) at which the shadow map should be updated when the interval update mode is enabled. This function is only relevant if the shadow map update mode is set to &quot;Interval&quot;.
    /// </para>
    /// </summary>
    /// <param name="id">The ID of the light.</param>
    /// <param name="msec">The frequency in milliseconds at which to update the shadow map.</param>
    /// <seealso>R3D_SetShadowUpdateFrequency</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_SetShadowUpdateFrequency")]
    public static partial void SetShadowUpdateFrequency(Light id, int msec);

    /// <summary>
    /// Forces an immediate update of the shadow map during the next rendering pass.
    /// <para>
    /// This function forces the shadow map of the specified light to be updated during the next call to `R3D_End`. This is primarily used for the manual update mode, but may also work for the interval mode.
    /// </para>
    /// </summary>
    /// <param name="id">The ID of the light.</param>
    /// <seealso>R3D_UpdateShadowMap</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_UpdateShadowMap")]
    public static partial void UpdateShadowMap(Light id);

    /// <summary>
    /// Retrieves the softness radius used to simulate penumbra in shadows.
    /// <para>
    /// The softness is expressed as a sampling radius in texels within the shadow map.
    /// </para>
    /// </summary>
    /// <param name="id">The ID of the light.</param>
    /// <returns>The softness radius in texels currently set for the shadow.</returns>
    /// <seealso>R3D_GetShadowSoftness</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_GetShadowSoftness")]
    public static partial float GetShadowSoftness(Light id);

    /// <summary>
    /// Sets the softness radius used to simulate penumbra in shadows.
    /// <para>
    /// This function adjusts the softness of the shadow edges for the specified light. The softness value corresponds to a number of texels in the shadow map, independent of its resolution. Larger values increase the blur radius, resulting in softer, more diffuse shadows, while smaller values yield sharper shadows.
    /// </para>
    /// </summary>
    /// <param name="id">The ID of the light.</param>
    /// <param name="softness">The softness radius in texels to apply (must be &gt;= 0).</param>
    /// <remarks>
    /// The softness must be set only after shadows have been enabled for the light, since the shadow map resolution must be known before the softness can be applied.
    /// </remarks>
    /// <seealso>R3D_SetShadowSoftness</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_SetShadowSoftness")]
    public static partial void SetShadowSoftness(Light id, float softness);

    /// <summary>
    /// Gets the shadow depth bias value.
    /// </summary>
    /// <seealso>R3D_GetShadowDepthBias</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_GetShadowDepthBias")]
    public static partial float GetShadowDepthBias(Light id);

    /// <summary>
    /// Sets the shadow depth bias value.
    /// <para>
    /// A higher bias helps reduce &quot;shadow acne&quot; artifacts (shadows flickering or appearing misaligned on surfaces). Be careful: too large values may cause shadows to look detached or floating away from objects.
    /// </para>
    /// </summary>
    /// <seealso>R3D_SetShadowDepthBias</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_SetShadowDepthBias")]
    public static partial void SetShadowDepthBias(Light id, float value);

    /// <summary>
    /// Gets the shadow slope bias value.
    /// </summary>
    /// <seealso>R3D_GetShadowSlopeBias</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_GetShadowSlopeBias")]
    public static partial float GetShadowSlopeBias(Light id);

    /// <summary>
    /// Sets the shadow slope bias value.
    /// <para>
    /// This bias mainly compensates artifacts on surfaces angled relative to the light. It helps prevent shadows from incorrectly appearing or disappearing along object edges.
    /// </para>
    /// </summary>
    /// <seealso>R3D_SetShadowSlopeBias</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_SetShadowSlopeBias")]
    public static partial void SetShadowSlopeBias(Light id, float value);

    /// <summary>
    /// Returns the bounding box encompassing the light's area of influence.
    /// <para>
    /// This function computes the axis-aligned bounding box (AABB) that encloses the volume affected by the specified light, based on its type:
    /// </para>
    /// <para>
    /// <list type="bullet">
    /// <item><description>For spotlights, the bounding box encloses the light cone.</description></item>
    /// <item><description>For omni-directional lights, it encloses a sphere representing the light's range.</description></item>
    /// <item><description>For directional lights, it returns an infinite bounding box to represent global influence.</description></item>
    /// </list>
    /// </para>
    /// <para>
    /// This bounding box is primarily useful for spatial partitioning, culling, or visual debugging.
    /// </para>
    /// </summary>
    /// <param name="light">The light for which to compute the bounding box.</param>
    /// <returns>A BoundingBox struct that encloses the light's influence volume.</returns>
    /// <seealso>R3D_GetLightBoundingBox</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_GetLightBoundingBox")]
    public static partial BoundingBox GetLightBoundingBox(Light light);

    /// <summary>
    /// Draws the area of influence of the light in 3D space.
    /// <para>
    /// This function visualizes the area affected by a light in 3D space. It draws the light's influence, such as the cone for spotlights or the volume for omni-lights. This function is only relevant for spotlights and omni-lights.
    /// </para>
    /// </summary>
    /// <param name="id">The ID of the light.</param>
    /// <remarks>
    /// This function should be called while using the default 3D rendering mode of raylib, not with R3D's rendering mode. It uses raylib's 3D drawing functions to render the light's shape.
    /// </remarks>
    /// <seealso>R3D_DrawLightShape</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_DrawLightShape")]
    public static partial void DrawLightShape(Light id);

}
