// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

using System;
using System.Numerics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Security;
using Raylib_cs;
using static Raylib_cs.Raylib;

namespace R3D_cs;

// r3d_draw.h;

[SuppressUnmanagedCodeSecurity]
public static unsafe partial class R3D
{

    /// <summary>
    /// Begins a rendering session using the given camera.
    /// <para>
    /// Rendering output is directed to the default framebuffer.
    /// </para>
    /// </summary>
    /// <param name="camera">Camera used to render the scene.</param>
    /// <remarks>
    /// Native: <c>R3D_Begin</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_Begin")]
    public static partial void Begin(Camera3D camera);

    /// <summary>
    /// Begins a rendering session with a custom render target.
    /// <para>
    /// If the render target is invalid (ID = 0), rendering goes to the screen.
    /// </para>
    /// </summary>
    /// <param name="target">Render texture to render into.</param>
    /// <param name="camera">Camera used to render the scene.</param>
    /// <remarks>
    /// Native: <c>R3D_BeginEx</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_BeginEx")]
    public static partial void BeginEx(RenderTexture2D target, Camera3D camera);

    /// <summary>
    /// Ends the current rendering session.
    /// <para>
    /// This function is the one that actually performs the full rendering of the described scene. It carries out culling, sorting, shadow rendering, scene rendering, and screen / post-processing effects.
    /// </para>
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_End</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_End")]
    public static partial void End();

    /// <summary>
    /// Begins a clustered draw pass.
    /// <para>
    /// All draw calls submitted in this pass are first tested against the cluster AABB. If the cluster fails the scene/shadow frustum test, none of the contained objects are tested or drawn.
    /// </para>
    /// </summary>
    /// <param name="aabb">Bounding box used as the cluster-level frustum test.</param>
    /// <remarks>
    /// Native: <c>R3D_BeginCluster</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_BeginCluster")]
    public static partial void BeginCluster(BoundingBox aabb);

    /// <summary>
    /// Ends the current clustered draw pass.
    /// <para>
    /// Stops submitting draw calls to the active cluster.
    /// </para>
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_EndCluster</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_EndCluster")]
    public static partial void EndCluster();

    /// <summary>
    /// Queues a mesh draw command with position and uniform scale.
    /// <para>
    /// The command is executed during R3D_End().
    /// </para>
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_DrawMesh</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_DrawMesh")]
    public static partial void DrawMesh(Mesh mesh, Material material, Vector3 position, float scale);

    /// <summary>
    /// Queues a mesh draw command with position, rotation and non-uniform scale.
    /// <para>
    /// The command is executed during R3D_End().
    /// </para>
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_DrawMeshEx</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_DrawMeshEx")]
    public static partial void DrawMeshEx(Mesh mesh, Material material, Vector3 position, Quaternion rotation, Vector3 scale);

    /// <summary>
    /// Queues a mesh draw command using a full transform matrix.
    /// <para>
    /// The command is executed during R3D_End().
    /// </para>
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_DrawMeshPro</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_DrawMeshPro")]
    public static partial void DrawMeshPro(Mesh mesh, Material material, Matrix4x4 transform);

    /// <summary>
    /// Queues an instanced mesh draw command.
    /// <para>
    /// Draws multiple instances using the provided instance buffer.
    /// </para>
    /// <para>
    /// The command is executed during R3D_End().
    /// </para>
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_DrawMeshInstanced</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_DrawMeshInstanced")]
    public static partial void DrawMeshInstanced(Mesh mesh, Material material, InstanceBuffer instances, int count);

    /// <summary>
    /// Queues an instanced mesh draw command with an additional transform.
    /// <para>
    /// The transform is applied to all instances.
    /// </para>
    /// <para>
    /// The command is executed during R3D_End().
    /// </para>
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_DrawMeshInstancedEx</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_DrawMeshInstancedEx")]
    public static partial void DrawMeshInstancedEx(Mesh mesh, Material material, InstanceBuffer instances, int count, Matrix4x4 transform);

    /// <summary>
    /// Queues a model draw command with position and uniform scale.
    /// <para>
    /// The command is executed during R3D_End().
    /// </para>
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_DrawModel</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_DrawModel")]
    public static partial void DrawModel(Model model, Vector3 position, float scale);

    /// <summary>
    /// Queues a model draw command with position, rotation and non-uniform scale.
    /// <para>
    /// The command is executed during R3D_End().
    /// </para>
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_DrawModelEx</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_DrawModelEx")]
    public static partial void DrawModelEx(Model model, Vector3 position, Quaternion rotation, Vector3 scale);

    /// <summary>
    /// Queues a model draw command using a full transform matrix.
    /// <para>
    /// The command is executed during R3D_End().
    /// </para>
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_DrawModelPro</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_DrawModelPro")]
    public static partial void DrawModelPro(Model model, Matrix4x4 transform);

    /// <summary>
    /// Queues an instanced model draw command.
    /// <para>
    /// Draws multiple instances using the provided instance buffer.
    /// </para>
    /// <para>
    /// The command is executed during R3D_End().
    /// </para>
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_DrawModelInstanced</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_DrawModelInstanced")]
    public static partial void DrawModelInstanced(Model model, InstanceBuffer instances, int count);

    /// <summary>
    /// Queues an instanced model draw command with an additional transform.
    /// <para>
    /// The transform is applied to all instances.
    /// </para>
    /// <para>
    /// The command is executed during R3D_End().
    /// </para>
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_DrawModelInstancedEx</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_DrawModelInstancedEx")]
    public static partial void DrawModelInstancedEx(Model model, InstanceBuffer instances, int count, Matrix4x4 transform);

    /// <summary>
    /// Queues an animated model draw command.
    /// <para>
    /// Uses the provided animation player to compute the pose.
    /// </para>
    /// <para>
    /// The command is executed during R3D_End().
    /// </para>
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_DrawAnimatedModel</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_DrawAnimatedModel")]
    public static partial void DrawAnimatedModel(Model model, AnimationPlayer player, Vector3 position, float scale);

    /// <summary>
    /// Queues an animated model draw command with position, rotation and non-uniform scale.
    /// <para>
    /// Uses the provided animation player to compute the pose.
    /// </para>
    /// <para>
    /// The command is executed during R3D_End().
    /// </para>
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_DrawAnimatedModelEx</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_DrawAnimatedModelEx")]
    public static partial void DrawAnimatedModelEx(Model model, AnimationPlayer player, Vector3 position, Quaternion rotation, Vector3 scale);

    /// <summary>
    /// Queues an animated model draw command using a full transform matrix.
    /// <para>
    /// The command is executed during R3D_End().
    /// </para>
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_DrawAnimatedModelPro</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_DrawAnimatedModelPro")]
    public static partial void DrawAnimatedModelPro(Model model, AnimationPlayer player, Matrix4x4 transform);

    /// <summary>
    /// Queues an instanced animated model draw command.
    /// <para>
    /// Draws multiple animated instances using the provided instance buffer.
    /// </para>
    /// <para>
    /// The command is executed during R3D_End().
    /// </para>
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_DrawAnimatedModelInstanced</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_DrawAnimatedModelInstanced")]
    public static partial void DrawAnimatedModelInstanced(Model model, AnimationPlayer player, InstanceBuffer instances, int count);

    /// <summary>
    /// Queues an instanced animated model draw command with an additional transform.
    /// <para>
    /// The transform is applied to all instances.
    /// </para>
    /// <para>
    /// The command is executed during R3D_End().
    /// </para>
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_DrawAnimatedModelInstancedEx</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_DrawAnimatedModelInstancedEx")]
    public static partial void DrawAnimatedModelInstancedEx(Model model, AnimationPlayer player, InstanceBuffer instances, int count, Matrix4x4 transform);

    /// <summary>
    /// Queues a decal draw command with position and uniform scale.
    /// <para>
    /// The command is executed during R3D_End().
    /// </para>
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_DrawDecal</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_DrawDecal")]
    public static partial void DrawDecal(Decal decal, Vector3 position, float scale);

    /// <summary>
    /// Queues a decal draw command with position, rotation and non-uniform scale.
    /// <para>
    /// The command is executed during R3D_End().
    /// </para>
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_DrawDecalEx</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_DrawDecalEx")]
    public static partial void DrawDecalEx(Decal decal, Vector3 position, Quaternion rotation, Vector3 scale);

    /// <summary>
    /// Queues a decal draw command using a full transform matrix.
    /// <para>
    /// The command is executed during R3D_End().
    /// </para>
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_DrawDecalPro</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_DrawDecalPro")]
    public static partial void DrawDecalPro(Decal decal, Matrix4x4 transform);

    /// <summary>
    /// Queues an instanced decal draw command.
    /// <para>
    /// Draws multiple instances using the provided instance buffer.
    /// </para>
    /// <para>
    /// The command is executed during R3D_End().
    /// </para>
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_DrawDecalInstanced</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_DrawDecalInstanced")]
    public static partial void DrawDecalInstanced(Decal decal, InstanceBuffer instances, int count);

    /// <summary>
    /// Queues an instanced decal draw command with an additional transform.
    /// <para>
    /// The transform is applied to all instances.
    /// </para>
    /// <para>
    /// The command is executed during R3D_End().
    /// </para>
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_DrawDecalInstancedEx</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_DrawDecalInstancedEx")]
    public static partial void DrawDecalInstancedEx(Decal decal, InstanceBuffer instances, int count, Matrix4x4 transform);

}
