// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

using System;
using System.Numerics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Security;
using Raylib_cs;
using static Raylib_cs.Raylib;

namespace R3D_cs;

// r3d_skeleton.h;

[SuppressUnmanagedCodeSecurity]
public static unsafe partial class R3D
{

    /// <summary>
    /// Loads a skeleton hierarchy from a 3D model file.
    /// <para>
    /// Skeletons are automatically loaded when importing a model, but can be loaded manually for advanced use cases.
    /// </para>
    /// </summary>
    /// <param name="filePath">Path to the model file containing the skeleton data.</param>
    /// <returns>Return the loaded R3D_Skeleton.</returns>
    /// <seealso>R3D_LoadSkeleton</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_LoadSkeleton", StringMarshalling = StringMarshalling.Utf8)]
    public static partial Skeleton LoadSkeleton(string filePath);

    /// <summary>
    /// Loads a skeleton hierarchy from memory data.
    /// <para>
    /// Allows manual loading of skeletons directly from a memory buffer. Typically used for advanced or custom asset loading workflows.
    /// </para>
    /// </summary>
    /// <param name="data">Pointer to the memory buffer containing skeleton data.</param>
    /// <param name="size">Size of the memory buffer in bytes.</param>
    /// <param name="hint">Optional format hint (can be NULL).</param>
    /// <returns>Return the loaded R3D_Skeleton.</returns>
    /// <seealso>R3D_LoadSkeletonFromMemory</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_LoadSkeletonFromMemory", StringMarshalling = StringMarshalling.Utf8)]
    public static partial Skeleton LoadSkeletonFromMemory(void* data, uint size, string hint);

    /// <summary>
    /// Loads a skeleton hierarchy from an existing importer.
    /// <para>
    /// Extracts the skeleton data from a previously loaded importer instance.
    /// </para>
    /// </summary>
    /// <param name="importer">Importer instance to extract the skeleton from.</param>
    /// <returns>Return the loaded R3D_Skeleton.</returns>
    /// <seealso>R3D_LoadSkeletonFromImporter</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_LoadSkeletonFromImporter")]
    public static partial Skeleton LoadSkeletonFromImporter(Importer* importer);

    /// <summary>
    /// Frees the memory allocated for a skeleton.
    /// </summary>
    /// <param name="skeleton">R3D_Skeleton to destroy.</param>
    /// <seealso>R3D_UnloadSkeleton</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_UnloadSkeleton")]
    public static partial void UnloadSkeleton(Skeleton skeleton);

    /// <summary>
    /// Check if a skeleton is valid.
    /// <para>
    /// Returns true if atleast the texBindPose is greater than zero.
    /// </para>
    /// </summary>
    /// <param name="skeleton">The skeleton to check.</param>
    /// <returns>true if valid, false otherwise.</returns>
    /// <seealso>R3D_IsSkeletonValid</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_IsSkeletonValid")]
    [return: MarshalAs(UnmanagedType.I1)]
    public static partial bool IsSkeletonValid(Skeleton skeleton);

    /// <summary>
    /// Returns the index of the bone with the given name.
    /// </summary>
    /// <param name="skeleton">Skeleton to search in.</param>
    /// <param name="boneName">Name of the bone to find.</param>
    /// <returns>Index of the bone, or a negative value if not found.</returns>
    /// <seealso>R3D_GetSkeletonBoneIndex</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_GetSkeletonBoneIndex", StringMarshalling = StringMarshalling.Utf8)]
    public static partial int GetSkeletonBoneIndex(Skeleton skeleton, string boneName);

    /// <summary>
    /// Returns a pointer to the bone with the given name.
    /// </summary>
    /// <param name="skeleton">Skeleton to search in.</param>
    /// <param name="boneName">Name of the bone to find.</param>
    /// <returns>Pointer to the bone, or NULL if not found.</returns>
    /// <seealso>R3D_GetSkeletonBone</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_GetSkeletonBone", StringMarshalling = StringMarshalling.Utf8)]
    public static partial BoneInfo* GetSkeletonBone(Skeleton skeleton, string boneName);

}
