// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

using System;
using System.Numerics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Security;
using Raylib_cs;
using static Raylib_cs.Raylib;

namespace R3D_cs;

// r3d_mesh.h;

[SuppressUnmanagedCodeSecurity]
public static unsafe partial class R3D
{

    /// <summary>
    /// Creates a 3D mesh from CPU-side mesh data.
    /// </summary>
    /// <param name="type">Primitive type used to interpret vertex data.</param>
    /// <param name="data">R3D_MeshData containing vertices and indices (cannot be NULL).</param>
    /// <param name="aabb">Optional pointer to a bounding box. If NULL, it will be computed automatically.</param>
    /// <param name="usage">Hint on how the mesh will be used.</param>
    /// <returns>Created R3D_Mesh.</returns>
    /// <remarks>
    /// The function copies all vertex and index data into GPU buffers.
    /// </remarks>
    /// <seealso>R3D_LoadMesh</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_LoadMesh")]
    public static partial Mesh LoadMesh(PrimitiveType type, MeshData data, BoundingBox* aabb, MeshUsage usage);

    /// <summary>
    /// Destroys a 3D mesh and frees its resources.
    /// </summary>
    /// <param name="mesh">R3D_Mesh to destroy.</param>
    /// <seealso>R3D_UnloadMesh</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_UnloadMesh")]
    public static partial void UnloadMesh(Mesh mesh);

    /// <summary>
    /// Check if a mesh is valid for rendering.
    /// <para>
    /// Returns true if the mesh has a valid VAO and VBO.
    /// </para>
    /// </summary>
    /// <param name="mesh">The mesh to check.</param>
    /// <returns>true if valid, false otherwise.</returns>
    /// <seealso>R3D_IsMeshValid</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_IsMeshValid")]
    [return: MarshalAs(UnmanagedType.I1)]
    public static partial bool IsMeshValid(Mesh mesh);

    /// <summary>
    /// Generate a quad mesh with orientation.
    /// </summary>
    /// <param name="width">Width along local X axis.</param>
    /// <param name="length">Length along local Z axis.</param>
    /// <param name="resX">Subdivisions along width.</param>
    /// <param name="resZ">Subdivisions along length.</param>
    /// <param name="frontDir">Direction vector for the quad's front face.</param>
    /// <returns>Mesh ready for rendering.</returns>
    /// <seealso>R3D_GenMeshQuad</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_GenMeshQuad")]
    public static partial Mesh GenMeshQuad(float width, float length, int resX, int resZ, Vector3 frontDir);

    /// <summary>
    /// Generate a plane mesh.
    /// </summary>
    /// <param name="width">Width along X axis.</param>
    /// <param name="length">Length along Z axis.</param>
    /// <param name="resX">Subdivisions along X axis.</param>
    /// <param name="resZ">Subdivisions along Z axis.</param>
    /// <returns>Mesh ready for rendering.</returns>
    /// <seealso>R3D_GenMeshPlane</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_GenMeshPlane")]
    public static partial Mesh GenMeshPlane(float width, float length, int resX, int resZ);

    /// <summary>
    /// Generate a polygon mesh.
    /// </summary>
    /// <param name="sides">Number of sides (min 3).</param>
    /// <param name="radius">Radius of the polygon.</param>
    /// <param name="frontDir">Direction vector for the polygon's front face.</param>
    /// <returns>Mesh ready for rendering.</returns>
    /// <seealso>R3D_GenMeshPoly</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_GenMeshPoly")]
    public static partial Mesh GenMeshPoly(int sides, float radius, Vector3 frontDir);

    /// <summary>
    /// Generate a cube mesh.
    /// </summary>
    /// <param name="width">Width along X axis.</param>
    /// <param name="height">Height along Y axis.</param>
    /// <param name="length">Length along Z axis.</param>
    /// <returns>Mesh ready for rendering.</returns>
    /// <seealso>R3D_GenMeshCube</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_GenMeshCube")]
    public static partial Mesh GenMeshCube(float width, float height, float length);

    /// <summary>
    /// Generate a subdivided cube mesh.
    /// </summary>
    /// <param name="width">Width along X axis.</param>
    /// <param name="height">Height along Y axis.</param>
    /// <param name="length">Length along Z axis.</param>
    /// <param name="resX">Subdivisions along X axis.</param>
    /// <param name="resY">Subdivisions along Y axis.</param>
    /// <param name="resZ">Subdivisions along Z axis.</param>
    /// <returns>Mesh ready for rendering.</returns>
    /// <seealso>R3D_GenMeshCubeEx</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_GenMeshCubeEx")]
    public static partial Mesh GenMeshCubeEx(float width, float height, float length, int resX, int resY, int resZ);

    /// <summary>
    /// Generate a slope mesh.
    /// </summary>
    /// <param name="width">Width along X axis.</param>
    /// <param name="height">Height along Y axis.</param>
    /// <param name="length">Length along Z axis.</param>
    /// <param name="slopeNormal">Direction of the slope.</param>
    /// <returns>Mesh ready for rendering.</returns>
    /// <seealso>R3D_GenMeshSlope</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_GenMeshSlope")]
    public static partial Mesh GenMeshSlope(float width, float height, float length, Vector3 slopeNormal);

    /// <summary>
    /// Generate a sphere mesh.
    /// </summary>
    /// <param name="radius">Sphere radius.</param>
    /// <param name="rings">Number of latitude divisions.</param>
    /// <param name="slices">Number of longitude divisions.</param>
    /// <returns>Mesh ready for rendering.</returns>
    /// <seealso>R3D_GenMeshSphere</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_GenMeshSphere")]
    public static partial Mesh GenMeshSphere(float radius, int rings, int slices);

    /// <summary>
    /// Generate a hemisphere mesh.
    /// </summary>
    /// <param name="radius">Hemisphere radius.</param>
    /// <param name="rings">Number of latitude divisions.</param>
    /// <param name="slices">Number of longitude divisions.</param>
    /// <returns>Mesh ready for rendering.</returns>
    /// <seealso>R3D_GenMeshHemiSphere</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_GenMeshHemiSphere")]
    public static partial Mesh GenMeshHemiSphere(float radius, int rings, int slices);

    /// <summary>
    /// Generate a cylinder mesh.
    /// </summary>
    /// <param name="bottomRadius">Bottom radius.</param>
    /// <param name="topRadius">Top radius.</param>
    /// <param name="height">Height along Y axis.</param>
    /// <param name="slices">Radial subdivisions.</param>
    /// <returns>Mesh ready for rendering.</returns>
    /// <seealso>R3D_GenMeshCylinder</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_GenMeshCylinder")]
    public static partial Mesh GenMeshCylinder(float bottomRadius, float topRadius, float height, int slices);

    /// <summary>
    /// Generate a capsule mesh.
    /// </summary>
    /// <param name="radius">Capsule radius.</param>
    /// <param name="height">Height along Y axis.</param>
    /// <param name="rings">Number of latitude divisions.</param>
    /// <param name="slices">Number of longitude divisions.</param>
    /// <returns>Mesh ready for rendering.</returns>
    /// <seealso>R3D_GenMeshCapsule</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_GenMeshCapsule")]
    public static partial Mesh GenMeshCapsule(float radius, float height, int rings, int slices);

    /// <summary>
    /// Generate a torus mesh.
    /// </summary>
    /// <param name="radius">Major radius (center to tube).</param>
    /// <param name="size">Minor radius (tube thickness).</param>
    /// <param name="radSeg">Segments around major radius.</param>
    /// <param name="sides">Sides around tube cross-section.</param>
    /// <returns>Mesh ready for rendering.</returns>
    /// <seealso>R3D_GenMeshTorus</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_GenMeshTorus")]
    public static partial Mesh GenMeshTorus(float radius, float size, int radSeg, int sides);

    /// <summary>
    /// Generate a trefoil knot mesh.
    /// </summary>
    /// <param name="radius">Major radius.</param>
    /// <param name="size">Minor radius.</param>
    /// <param name="radSeg">Segments around major radius.</param>
    /// <param name="sides">Sides around tube cross-section.</param>
    /// <returns>Mesh ready for rendering.</returns>
    /// <seealso>R3D_GenMeshKnot</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_GenMeshKnot")]
    public static partial Mesh GenMeshKnot(float radius, float size, int radSeg, int sides);

    /// <summary>
    /// Generate a heightmap terrain mesh.
    /// </summary>
    /// <param name="heightmap">Heightmap image.</param>
    /// <param name="size">3D dimensions of terrain.</param>
    /// <returns>Mesh ready for rendering.</returns>
    /// <seealso>R3D_GenMeshHeightmap</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_GenMeshHeightmap")]
    public static partial Mesh GenMeshHeightmap(Image heightmap, Vector3 size);

    /// <summary>
    /// Generate a cubicmap voxel mesh.
    /// </summary>
    /// <param name="cubicmap">Cubicmap image.</param>
    /// <param name="cubeSize">Size of each cube.</param>
    /// <returns>Mesh ready for rendering.</returns>
    /// <seealso>R3D_GenMeshCubicmap</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_GenMeshCubicmap")]
    public static partial Mesh GenMeshCubicmap(Image cubicmap, Vector3 cubeSize);

    /// <summary>
    /// Upload a mesh data on the GPU.
    /// <para>
    /// This function uploads a mesh's vertex and optional index data to the GPU.
    /// </para>
    /// <para>
    /// If `aabb` is provided, it will be used as the mesh's bounding box; if null, the bounding box is automatically recalculated from the vertex data.
    /// </para>
    /// </summary>
    /// <param name="mesh">Pointer to the mesh structure to update.</param>
    /// <param name="data">Mesh data (vertices and indices) to upload.</param>
    /// <param name="aabb">Optional bounding box; if null, it is recalculated automatically.</param>
    /// <returns>Returns true if the update is successful, false otherwise.</returns>
    /// <seealso>R3D_UpdateMesh</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_UpdateMesh")]
    [return: MarshalAs(UnmanagedType.I1)]
    public static partial bool UpdateMesh(ref Mesh mesh, MeshData data, BoundingBox* aabb);

}
