// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

using System;
using System.Numerics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Security;
using Raylib_cs;
using static Raylib_cs.Raylib;

namespace R3D_cs;

// r3d_environment.h;

[SuppressUnmanagedCodeSecurity]
public static unsafe partial class R3D
{

    /// <summary>
    /// Retrieves a pointer to the current environment configuration.
    /// <para>
    /// Provides direct read/write access to environment settings. Modifications take effect immediately.
    /// </para>
    /// </summary>
    /// <returns>Pointer to the active R3D_Environment structure</returns>
    /// <seealso>R3D_GetEnvironment</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_GetEnvironment")]
    public static partial Environment* GetEnvironment();

    /// <summary>
    /// Replaces the entire environment configuration.
    /// <para>
    /// Copies all settings from the provided structure to the active environment. Useful for switching between presets or restoring saved states.
    /// </para>
    /// </summary>
    /// <param name="env">Pointer to the R3D_Environment structure to copy from</param>
    /// <seealso>R3D_SetEnvironment</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_SetEnvironment")]
    public static partial void SetEnvironment(Environment* env);

}
