// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

using System;
using System.Numerics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Security;
using Raylib_cs;
using static Raylib_cs.Raylib;

namespace R3D_cs;

// r3d_pack.h;

[SuppressUnmanagedCodeSecurity]
public static unsafe partial class R3D
{

    /// <summary>
    /// Packs a 32-bit float into a 16-bit floating-point value.
    /// </summary>
    /// <param name="x">Value to pack.</param>
    /// <returns>IEEE 754 half-precision representation.</returns>
    /// <remarks>
    /// Native: <c>R3D_PackFloat16</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_PackFloat16")]
    public static partial ushort PackFloat16(float x);

    /// <summary>
    /// Packs a float into a 16-bit unsigned normalized value.
    /// <para>
    /// The input value is clamped to the [0, 1] range before packing.
    /// </para>
    /// </summary>
    /// <param name="x">Value to pack.</param>
    /// <returns>16-bit UNORM representation.</returns>
    /// <remarks>
    /// Native: <c>R3D_PackUnorm16</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_PackUnorm16")]
    public static partial ushort PackUnorm16(float x);

    /// <summary>
    /// Packs a float into a 16-bit signed normalized value.
    /// <para>
    /// The input value is clamped to the [-1, 1] range before packing.
    /// </para>
    /// </summary>
    /// <param name="x">Value to pack.</param>
    /// <returns>16-bit SNORM representation.</returns>
    /// <remarks>
    /// Native: <c>R3D_PackSnorm16</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_PackSnorm16")]
    public static partial short PackSnorm16(float x);

    /// <summary>
    /// Packs a float into an 8-bit unsigned normalized value.
    /// <para>
    /// The input value is clamped to the [0, 1] range before packing.
    /// </para>
    /// </summary>
    /// <param name="x">Value to pack.</param>
    /// <returns>8-bit UNORM representation.</returns>
    /// <remarks>
    /// Native: <c>R3D_PackUnorm8</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_PackUnorm8")]
    public static partial byte PackUnorm8(float x);

    /// <summary>
    /// Packs a float into an 8-bit signed normalized value.
    /// <para>
    /// The input value is clamped to the [-1, 1] range before packing.
    /// </para>
    /// </summary>
    /// <param name="x">Value to pack.</param>
    /// <returns>8-bit SNORM representation.</returns>
    /// <remarks>
    /// Native: <c>R3D_PackSnorm8</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_PackSnorm8")]
    public static partial byte PackSnorm8(float x);

    /// <summary>
    /// Unpacks a 16-bit floating-point value into a 32-bit float.
    /// </summary>
    /// <param name="x">IEEE 754 half-precision representation.</param>
    /// <returns>Unpacked float value.</returns>
    /// <remarks>
    /// Native: <c>R3D_UnpackFloat16</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_UnpackFloat16")]
    public static partial float UnpackFloat16(ushort x);

    /// <summary>
    /// Unpacks a 16-bit unsigned normalized value.
    /// <para>
    /// The returned value is in the [0, 1] range.
    /// </para>
    /// </summary>
    /// <param name="x">16-bit UNORM representation.</param>
    /// <returns>Unpacked float value.</returns>
    /// <remarks>
    /// Native: <c>R3D_UnpackUnorm16</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_UnpackUnorm16")]
    public static partial float UnpackUnorm16(ushort x);

    /// <summary>
    /// Unpacks a 16-bit signed normalized value.
    /// <para>
    /// The returned value is clamped to the [-1, 1] range.
    /// </para>
    /// </summary>
    /// <param name="x">16-bit SNORM representation.</param>
    /// <returns>Unpacked float value.</returns>
    /// <remarks>
    /// Native: <c>R3D_UnpackSnorm16</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_UnpackSnorm16")]
    public static partial float UnpackSnorm16(short x);

    /// <summary>
    /// Unpacks an 8-bit unsigned normalized value.
    /// <para>
    /// The returned value is in the [0, 1] range.
    /// </para>
    /// </summary>
    /// <param name="x">8-bit UNORM representation.</param>
    /// <returns>Unpacked float value.</returns>
    /// <remarks>
    /// Native: <c>R3D_UnpackUnorm8</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_UnpackUnorm8")]
    public static partial float UnpackUnorm8(sbyte x);

    /// <summary>
    /// Unpacks an 8-bit signed normalized value.
    /// <para>
    /// The returned value is clamped to the [-1, 1] range.
    /// </para>
    /// </summary>
    /// <param name="x">8-bit SNORM representation.</param>
    /// <returns>Unpacked float value.</returns>
    /// <remarks>
    /// Native: <c>R3D_UnpackSnorm8</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_UnpackSnorm8")]
    public static partial float UnpackSnorm8(sbyte x);

}
