// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

using System;
using System.Numerics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Security;
using Raylib_cs;
using static Raylib_cs.Raylib;

namespace R3D_cs;

// r3d_material.h;

[SuppressUnmanagedCodeSecurity]
public static unsafe partial class R3D
{

    /// <summary>
    /// Get the default material configuration.
    /// <para>
    /// Returns `R3D_MATERIAL_BASE` by default, or the material defined via `R3D_SetDefaultMaterial()`.
    /// </para>
    /// </summary>
    /// <returns>Default material structure with standard properties.</returns>
    /// <remarks>
    /// Native: <c>R3D_GetDefaultMaterial</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_GetDefaultMaterial")]
    public static partial Material GetDefaultMaterial();

    /// <summary>
    /// Set the default material configuration.
    /// <para>
    /// Allows you to override the default material. The default material will be used as the basis for loading 3D models.
    /// </para>
    /// </summary>
    /// <param name="material">Default material to define.</param>
    /// <remarks>
    /// Native: <c>R3D_SetDefaultMaterial</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_SetDefaultMaterial")]
    public static partial void SetDefaultMaterial(Material material);

    /// <summary>
    /// Unload a material and its associated textures.
    /// <para>
    /// Frees all memory associated with a material, including its textures. This function will unload all textures that are not default textures.
    /// </para>
    /// </summary>
    /// <param name="material">Pointer to the material structure to be unloaded.</param>
    /// <remarks>
    /// <b>Warning:</b>
    /// Only call this function if you are certain that the textures are not shared with other materials or objects, as this will permanently free the texture data.
    /// Native: <c>R3D_UnloadMaterial</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_UnloadMaterial")]
    public static partial void UnloadMaterial(Material material);

    /// <summary>
    /// Load an albedo (base color) map from file.
    /// <para>
    /// Loads an image, uploads it as an sRGB texture (if enabled), and applies the provided tint color.
    /// </para>
    /// </summary>
    /// <param name="fileName">Path to the texture file.</param>
    /// <param name="color">Multiplicative tint applied in the shader.</param>
    /// <returns>Albedo map structure. Returns an empty map on failure.</returns>
    /// <remarks>
    /// Native: <c>R3D_LoadAlbedoMap</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_LoadAlbedoMap", StringMarshalling = StringMarshalling.Utf8)]
    public static partial AlbedoMap LoadAlbedoMap(string fileName, Color color);

    /// <summary>
    /// Load an albedo (base color) map from memory.
    /// <para>
    /// Same behavior as R3D_LoadAlbedoMap(), but reads from memory instead of disk.
    /// </para>
    /// </summary>
    /// <param name="fileType">Image format hint (e.g. &quot;png&quot;, &quot;jpg&quot;).</param>
    /// <param name="fileData">Pointer to image data.</param>
    /// <param name="dataSize">Size of image data in bytes.</param>
    /// <param name="color">Multiplicative tint applied in the shader.</param>
    /// <returns>Albedo map structure. Returns an empty map on failure.</returns>
    /// <remarks>
    /// Native: <c>R3D_LoadAlbedoMapFromMemory</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_LoadAlbedoMapFromMemory", StringMarshalling = StringMarshalling.Utf8)]
    public static partial AlbedoMap LoadAlbedoMapFromMemory(string fileType, void* fileData, int dataSize, Color color);

    /// <summary>
    /// Unload an albedo map texture.
    /// <para>
    /// Frees the underlying texture unless it is a default texture.
    /// </para>
    /// </summary>
    /// <param name="map">Albedo map to unload.</param>
    /// <remarks>
    /// Native: <c>R3D_UnloadAlbedoMap</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_UnloadAlbedoMap")]
    public static partial void UnloadAlbedoMap(AlbedoMap map);

    /// <summary>
    /// Load an emission map from file.
    /// <para>
    /// Loads an emissive texture (sRGB if enabled) and sets color + energy.
    /// </para>
    /// </summary>
    /// <param name="fileName">Path to the texture file.</param>
    /// <param name="color">Emission color.</param>
    /// <param name="energy">Emission intensity multiplier.</param>
    /// <returns>Emission map. Returns an empty map on failure.</returns>
    /// <remarks>
    /// Native: <c>R3D_LoadEmissionMap</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_LoadEmissionMap", StringMarshalling = StringMarshalling.Utf8)]
    public static partial EmissionMap LoadEmissionMap(string fileName, Color color, float energy);

    /// <summary>
    /// Load an emission map from memory.
    /// <para>
    /// Same behavior as R3D_LoadEmissionMap(), but reads from memory.
    /// </para>
    /// </summary>
    /// <param name="fileType">Image format hint.</param>
    /// <param name="fileData">Pointer to image data.</param>
    /// <param name="dataSize">Size of image data in bytes.</param>
    /// <param name="color">Emission color.</param>
    /// <param name="energy">Emission intensity multiplier.</param>
    /// <returns>Emission map. Returns an empty map on failure.</returns>
    /// <remarks>
    /// Native: <c>R3D_LoadEmissionMapFromMemory</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_LoadEmissionMapFromMemory", StringMarshalling = StringMarshalling.Utf8)]
    public static partial EmissionMap LoadEmissionMapFromMemory(string fileType, void* fileData, int dataSize, Color color, float energy);

    /// <summary>
    /// Unload an emission map texture.
    /// <para>
    /// Frees the texture unless it is a default texture.
    /// </para>
    /// </summary>
    /// <param name="map">Emission map to unload.</param>
    /// <remarks>
    /// Native: <c>R3D_UnloadEmissionMap</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_UnloadEmissionMap")]
    public static partial void UnloadEmissionMap(EmissionMap map);

    /// <summary>
    /// Load a normal map from file.
    /// <para>
    /// Uploads the texture in linear space and stores the normal scale factor.
    /// </para>
    /// </summary>
    /// <param name="fileName">Path to the texture file.</param>
    /// <param name="scale">Normal intensity multiplier.</param>
    /// <returns>Normal map. Returns an empty map on failure.</returns>
    /// <remarks>
    /// Native: <c>R3D_LoadNormalMap</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_LoadNormalMap", StringMarshalling = StringMarshalling.Utf8)]
    public static partial NormalMap LoadNormalMap(string fileName, float scale);

    /// <summary>
    /// Load a normal map from memory.
    /// <para>
    /// Same behavior as R3D_LoadNormalMap(), but reads from memory.
    /// </para>
    /// </summary>
    /// <param name="fileType">Image format hint.</param>
    /// <param name="fileData">Pointer to image data.</param>
    /// <param name="dataSize">Size of image data in bytes.</param>
    /// <param name="scale">Normal intensity multiplier.</param>
    /// <returns>Normal map. Returns an empty map on failure.</returns>
    /// <remarks>
    /// Native: <c>R3D_LoadNormalMapFromMemory</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_LoadNormalMapFromMemory", StringMarshalling = StringMarshalling.Utf8)]
    public static partial NormalMap LoadNormalMapFromMemory(string fileType, void* fileData, int dataSize, float scale);

    /// <summary>
    /// Unload a normal map texture.
    /// <para>
    /// Frees the texture unless it is a default texture.
    /// </para>
    /// </summary>
    /// <param name="map">Normal map to unload.</param>
    /// <remarks>
    /// Native: <c>R3D_UnloadNormalMap</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_UnloadNormalMap")]
    public static partial void UnloadNormalMap(NormalMap map);

    /// <summary>
    /// Load a combined ORM (Occlusion-Roughness-Metalness) map from file.
    /// <para>
    /// Uploads the texture in linear space and applies the provided multipliers.
    /// </para>
    /// </summary>
    /// <param name="fileName">Path to the ORM texture.</param>
    /// <param name="occlusion">Occlusion multiplier.</param>
    /// <param name="roughness">Roughness multiplier.</param>
    /// <param name="metalness">Metalness multiplier.</param>
    /// <returns>ORM map. Returns an empty map on failure.</returns>
    /// <remarks>
    /// Native: <c>R3D_LoadOrmMap</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_LoadOrmMap", StringMarshalling = StringMarshalling.Utf8)]
    public static partial OrmMap LoadOrmMap(string fileName, float occlusion, float roughness, float metalness);

    /// <summary>
    /// Load a combined ORM (Occlusion-Roughness-Metalness) map from memory.
    /// <para>
    /// Same behavior as R3D_LoadOrmMap(), but reads from memory.
    /// </para>
    /// </summary>
    /// <param name="fileType">Image format hint.</param>
    /// <param name="fileData">Pointer to image data.</param>
    /// <param name="dataSize">Size of image data in bytes.</param>
    /// <param name="occlusion">Occlusion multiplier.</param>
    /// <param name="roughness">Roughness multiplier.</param>
    /// <param name="metalness">Metalness multiplier.</param>
    /// <returns>ORM map. Returns an empty map on failure.</returns>
    /// <remarks>
    /// Native: <c>R3D_LoadOrmMapFromMemory</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_LoadOrmMapFromMemory", StringMarshalling = StringMarshalling.Utf8)]
    public static partial OrmMap LoadOrmMapFromMemory(string fileType, void* fileData, int dataSize, float occlusion, float roughness, float metalness);

    /// <summary>
    /// Unload an ORM map texture.
    /// <para>
    /// Frees the texture unless it is a default texture.
    /// </para>
    /// </summary>
    /// <param name="map">ORM map to unload.</param>
    /// <remarks>
    /// Native: <c>R3D_UnloadOrmMap</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_UnloadOrmMap")]
    public static partial void UnloadOrmMap(OrmMap map);

}
