// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

using System;
using System.Numerics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Security;
using Raylib_cs;
using static Raylib_cs.Raylib;

namespace R3D_cs;

// r3d_screen_shader.h;

[SuppressUnmanagedCodeSecurity]
public static unsafe partial class R3D
{

    /// <summary>
    /// Loads a screen shader from a file.
    /// <para>
    /// The shader must define a single entry point: `void fragment()`. Any other entry point, such as `vertex()`, or any varyings will be ignored.
    /// </para>
    /// </summary>
    /// <param name="filePath">Path to the shader source file.</param>
    /// <returns>Pointer to the loaded screen shader, or NULL on failure.</returns>
    /// <seealso>R3D_LoadScreenShader</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_LoadScreenShader", StringMarshalling = StringMarshalling.Utf8)]
    public static partial ScreenShader* LoadScreenShader(string filePath);

    /// <summary>
    /// Loads a screen shader from a source code string in memory.
    /// <para>
    /// The shader must define a single entry point: `void fragment()`. Any other entry point, such as `vertex()`, or any varyings will be ignored.
    /// </para>
    /// </summary>
    /// <param name="code">Null-terminated shader source code.</param>
    /// <returns>Pointer to the loaded screen shader, or NULL on failure.</returns>
    /// <seealso>R3D_LoadScreenShaderFromMemory</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_LoadScreenShaderFromMemory", StringMarshalling = StringMarshalling.Utf8)]
    public static partial ScreenShader* LoadScreenShaderFromMemory(string code);

    /// <summary>
    /// Unloads and destroys a screen shader.
    /// </summary>
    /// <param name="shader">Screen shader to unload.</param>
    /// <seealso>R3D_UnloadScreenShader</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_UnloadScreenShader")]
    public static partial void UnloadScreenShader(ref ScreenShader shader);

    /// <summary>
    /// Sets a uniform value for the current frame.
    /// <para>
    /// Once a uniform is set, it remains valid for the all frames. If an uniform is set multiple times during the same frame, the last value defined before R3D_End() is used.
    /// </para>
    /// <para>
    /// Supported types: bool, int, float, ivec2, ivec3, ivec4, vec2, vec3, vec4, mat2, mat3, mat4
    /// </para>
    /// </summary>
    /// <param name="shader">Target screen shader. May be NULL. In that case, the call is ignored and a warning is logged.</param>
    /// <param name="name">Name of the uniform. Must not be NULL.</param>
    /// <param name="value">Pointer to the uniform value. Must not be NULL.</param>
    /// <remarks>
    /// <b>Warning:</b>
    /// Boolean values are read as 4 bytes.
    /// </remarks>
    /// <seealso>R3D_SetScreenShaderUniform</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_SetScreenShaderUniform", StringMarshalling = StringMarshalling.Utf8)]
    public static partial void SetScreenShaderUniform(ref ScreenShader shader, string name, void* value);

    /// <summary>
    /// Sets a texture sampler for the current frame.
    /// <para>
    /// Once a sampler is set, it remains valid for all frames. If a sampler is set multiple times during the same frame, the last value defined before R3D_End() is used.
    /// </para>
    /// <para>
    /// Supported samplers: sampler1D, sampler2D, sampler3D, samplerCube
    /// </para>
    /// </summary>
    /// <param name="shader">Target screen shader. May be NULL. In that case, the call is ignored and a warning is logged.</param>
    /// <param name="name">Name of the sampler uniform. Must not be NULL.</param>
    /// <param name="texture">Texture to bind to the sampler.</param>
    /// <seealso>R3D_SetScreenShaderSampler</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_SetScreenShaderSampler", StringMarshalling = StringMarshalling.Utf8)]
    public static partial void SetScreenShaderSampler(ref ScreenShader shader, string name, Texture2D texture);

    /// <summary>
    /// Sets the list of screen shaders to execute at the end of the frame.
    /// <para>
    /// The maximum number of shaders is defined by `R3D_MAX_SCREEN_SHADERS`. If the provided count exceeds this limit, a warning is emitted and only the first `R3D_MAX_SCREEN_SHADERS` shaders are used.
    /// </para>
    /// <para>
    /// Shader pointers are copied internally, so the original array can be modified or freed after the call. NULL entries are allowed safely within the list.
    /// </para>
    /// <para>
    /// Calling this function resets all internal screen shaders before copying the new list. To disable all screen shaders, call this function with `shaders = NULL` and/or `count = 0`.
    /// </para>
    /// </summary>
    /// <param name="shaders">Array of pointers to R3D_ScreenShader objects.</param>
    /// <param name="count">Number of shaders in the array.</param>
    /// <seealso>R3D_SetScreenShaderChain</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_SetScreenShaderChain")]
    public static partial void SetScreenShaderChain(ScreenShader** shaders, int count);

}
