// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

using System;
using System.Numerics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Security;
using Raylib_cs;
using static Raylib_cs.Raylib;

namespace R3D_cs;

// r3d_decal.h;

[SuppressUnmanagedCodeSecurity]
public static unsafe partial class R3D
{

    /// <summary>
    /// Unload all map textures assigned to a R3D_Decal.
    /// <para>
    /// Frees all underlying textures in a R3D_Decal that are not a default texture.
    /// </para>
    /// </summary>
    /// <param name="decal">to unload maps from.</param>
    /// <remarks>
    /// Native: <c>R3D_UnloadDecalMaps</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_UnloadDecalMaps")]
    public static partial void UnloadDecalMaps(Decal decal);

}
