// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

using System;
using System.Numerics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Security;
using Raylib_cs;
using static Raylib_cs.Raylib;

namespace R3D_cs;

// r3d_frustum.h;

[SuppressUnmanagedCodeSecurity]
public static unsafe partial class R3D
{

    /// <summary>
    /// Get the current frustum.
    /// <para>
    /// Returns the frustum computed during the last call to R3D_Begin().
    /// </para>
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_GetFrustum</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_GetFrustum")]
    public static partial Frustum GetFrustum();

    /// <summary>
    /// Compute a frustum from a view-projection matrix.
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_ComputeFrustum</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_ComputeFrustum")]
    public static partial Frustum ComputeFrustum(Matrix4x4 viewProj);

    /// <summary>
    /// Compute the axis-aligned bounding box of a frustum.
    /// </summary>
    /// <param name="invViewProj">Inverse view-projection matrix.</param>
    /// <remarks>
    /// Native: <c>R3D_ComputeFrustumBoundingBox</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_ComputeFrustumBoundingBox")]
    public static partial BoundingBox ComputeFrustumBoundingBox(Matrix4x4 invViewProj);

    /// <summary>
    /// Compute the eight corner points of a frustum.
    /// </summary>
    /// <param name="invViewProj">Inverse view-projection matrix.</param>
    /// <param name="corners">Output array of 8 points.</param>
    /// <remarks>
    /// Native: <c>R3D_ComputeFrustumCorners</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_ComputeFrustumCorners")]
    public static partial void ComputeFrustumCorners(Matrix4x4 invViewProj, Vector3* corners);

    /// <summary>
    /// Check if a point is inside the frustum.
    /// </summary>
    /// <param name="frustum">Frustum to test against. Must not be NULL.</param>
    /// <remarks>
    /// Native: <c>R3D_FrustumContainsPoint</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_FrustumContainsPoint")]
    [return: MarshalAs(UnmanagedType.I1)]
    public static partial bool FrustumContainsPoint(ref Frustum frustum, Vector3 position);

    /// <summary>
    /// Check if any point from a set is inside the frustum.
    /// </summary>
    /// <param name="frustum">Frustum to test against. Must not be NULL.</param>
    /// <remarks>
    /// Native: <c>R3D_FrustumContainsAnyPoint</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_FrustumContainsAnyPoint")]
    [return: MarshalAs(UnmanagedType.I1)]
    public static partial bool FrustumContainsAnyPoint(ref Frustum frustum, ref Vector3 positions, int count);

    /// <summary>
    /// Check if a sphere intersects the frustum.
    /// </summary>
    /// <param name="frustum">Frustum to test against. Must not be NULL.</param>
    /// <remarks>
    /// Native: <c>R3D_FrustumIntersectsSphere</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_FrustumIntersectsSphere")]
    [return: MarshalAs(UnmanagedType.I1)]
    public static partial bool FrustumIntersectsSphere(ref Frustum frustum, Vector3 position, float radius);

    /// <summary>
    /// Check if a bounding box intersects the frustum.
    /// </summary>
    /// <param name="frustum">Frustum to test against. Must not be NULL.</param>
    /// <remarks>
    /// Native: <c>R3D_FrustumIntersectsBoundingBox</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_FrustumIntersectsBoundingBox")]
    [return: MarshalAs(UnmanagedType.I1)]
    public static partial bool FrustumIntersectsBoundingBox(ref Frustum frustum, BoundingBox aabb);

    /// <summary>
    /// Check if an oriented box intersects the frustum.
    /// </summary>
    /// <param name="frustum">Frustum to test against. Must not be NULL.</param>
    /// <remarks>
    /// Native: <c>R3D_FrustumIntersectsOrientedBox</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_FrustumIntersectsOrientedBox")]
    [return: MarshalAs(UnmanagedType.I1)]
    public static partial bool FrustumIntersectsOrientedBox(ref Frustum frustum, OrientedBox obb);

}
