// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

using System;
using System.Numerics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Security;
using Raylib_cs;
using static Raylib_cs.Raylib;

namespace R3D_cs;

// r3d_importer.h;

[SuppressUnmanagedCodeSecurity]
public static unsafe partial class R3D
{

    /// <summary>
    /// Load an importer from a file.
    /// <para>
    /// Creates an importer instance from the specified file path. The file is parsed once and can be reused to extract multiple resources such as models and animations.
    /// </para>
    /// </summary>
    /// <param name="filePath">Path to the asset file.</param>
    /// <param name="flags">Importer behavior flags.</param>
    /// <returns>Pointer to a new importer instance, or NULL on failure.</returns>
    /// <seealso>R3D_LoadImporter</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_LoadImporter", StringMarshalling = StringMarshalling.Utf8)]
    public static partial Importer* LoadImporter(string filePath, ImportFlags flags);

    /// <summary>
    /// Load an importer from a memory buffer.
    /// <para>
    /// Creates an importer instance from in-memory asset data. This is useful for embedded assets or streamed content.
    /// </para>
    /// </summary>
    /// <param name="data">Pointer to the asset data.</param>
    /// <param name="size">Size of the data buffer in bytes.</param>
    /// <param name="hint">Optional file format hint (may be NULL).</param>
    /// <param name="flags">Importer behavior flags.</param>
    /// <returns>Pointer to a new importer instance, or NULL on failure.</returns>
    /// <seealso>R3D_LoadImporterFromMemory</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_LoadImporterFromMemory", StringMarshalling = StringMarshalling.Utf8)]
    public static partial Importer* LoadImporterFromMemory(void* data, uint size, string hint, ImportFlags flags);

    /// <summary>
    /// Destroy an importer instance.
    /// <para>
    /// Frees all resources associated with the importer. Any models or animations extracted from it remain valid.
    /// </para>
    /// </summary>
    /// <param name="importer">Importer instance to destroy.</param>
    /// <seealso>R3D_UnloadImporter</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_UnloadImporter")]
    public static partial void UnloadImporter(Importer* importer);

}
