// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

using System;
using System.Numerics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Security;
using Raylib_cs;
using static Raylib_cs.Raylib;

namespace R3D_cs;

// r3d_utils.h;

[SuppressUnmanagedCodeSecurity]
public static unsafe partial class R3D
{

    /// <summary>
    /// Retrieves a default white texture.
    /// <para>
    /// This texture is fully white (1,1,1,1), useful for default material properties.
    /// </para>
    /// </summary>
    /// <returns>A white texture.</returns>
    /// <seealso>R3D_GetWhiteTexture</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_GetWhiteTexture")]
    public static partial Texture2D GetWhiteTexture();

    /// <summary>
    /// Retrieves a default black texture.
    /// <para>
    /// This texture is fully black (0,0,0,1), useful for masking or default values.
    /// </para>
    /// </summary>
    /// <returns>A black texture.</returns>
    /// <seealso>R3D_GetBlackTexture</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_GetBlackTexture")]
    public static partial Texture2D GetBlackTexture();

    /// <summary>
    /// Retrieves a default normal map texture.
    /// <para>
    /// This texture represents a neutral normal map (0.5, 0.5, 1.0), which applies no normal variation.
    /// </para>
    /// </summary>
    /// <returns>A neutral normal texture.</returns>
    /// <seealso>R3D_GetNormalTexture</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_GetNormalTexture")]
    public static partial Texture2D GetNormalTexture();

    /// <summary>
    /// Retrieves the buffer containing the scene's normal data.
    /// <para>
    /// This texture stores octahedral-compressed normals using two 16-bit per-channel RG components.
    /// </para>
    /// </summary>
    /// <returns>The normal buffer texture.</returns>
    /// <remarks>
    /// You can find the decoding functions in the embedded shaders, such as 'screen/lighting.fs.glsl'.
    /// </remarks>
    /// <seealso>R3D_GetBufferNormal</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_GetBufferNormal")]
    public static partial Texture2D GetBufferNormal();

    /// <summary>
    /// Retrieves the final depth buffer.
    /// <para>
    /// This texture is an R16 texture containing a linear depth value normalized between the near and far clipping planes. It does not include a stencil buffer.
    /// </para>
    /// <para>
    /// The texture is intended for post-processing effects outside of R3D that require access to linear depth information.
    /// </para>
    /// </summary>
    /// <returns>The final depth buffer texture (R16, linear depth).</returns>
    /// <seealso>R3D_GetBufferDepth</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_GetBufferDepth")]
    public static partial Texture2D GetBufferDepth();

    /// <summary>
    /// Retrieves the view matrix.
    /// <para>
    /// This matrix represents the camera's transformation from world space to view space. It is updated at the last call to 'R3D_Begin'.
    /// </para>
    /// </summary>
    /// <returns>The current view matrix.</returns>
    /// <seealso>R3D_GetMatrixView</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_GetMatrixView")]
    public static partial Matrix4x4 GetMatrixView();

    /// <summary>
    /// Retrieves the inverse view matrix.
    /// <para>
    /// This matrix transforms coordinates from view space back to world space. It is updated at the last call to 'R3D_Begin'.
    /// </para>
    /// </summary>
    /// <returns>The current inverse view matrix.</returns>
    /// <seealso>R3D_GetMatrixInvView</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_GetMatrixInvView")]
    public static partial Matrix4x4 GetMatrixInvView();

    /// <summary>
    /// Retrieves the projection matrix.
    /// <para>
    /// This matrix defines the transformation from view space to clip space. It is updated at the last call to 'R3D_Begin'.
    /// </para>
    /// </summary>
    /// <returns>The current projection matrix.</returns>
    /// <seealso>R3D_GetMatrixProjection</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_GetMatrixProjection")]
    public static partial Matrix4x4 GetMatrixProjection();

    /// <summary>
    /// Retrieves the inverse projection matrix.
    /// <para>
    /// This matrix transforms coordinates from clip space back to view space. It is updated at the last call to 'R3D_Begin'.
    /// </para>
    /// </summary>
    /// <returns>The current inverse projection matrix.</returns>
    /// <seealso>R3D_GetMatrixInvProjection</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_GetMatrixInvProjection")]
    public static partial Matrix4x4 GetMatrixInvProjection();

}
