// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

using System;
using System.Numerics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Security;
using Raylib_cs;
using static Raylib_cs.Raylib;

[assembly: DisableRuntimeMarshalling]

namespace R3D_cs;

// r3d_core.h;

[SuppressUnmanagedCodeSecurity]
public static unsafe partial class R3D
{

    /// <summary>
    /// Used by DllImport to load the native library
    /// </summary>
    public const string NativeLibName = "r3d";

    public const string R3D_VERSION = "0.8.0-dev";

    /// <summary>
    /// Initializes the rendering engine.
    /// <para>
    /// This function sets up the internal rendering system with the provided resolution.
    /// </para>
    /// </summary>
    /// <param name="resWidth">Width of the internal resolution.</param>
    /// <param name="resHeight">Height of the internal resolution.</param>
    /// <returns>True if the initialization is successful.</returns>
    /// <seealso>R3D_Init</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_Init")]
    [return: MarshalAs(UnmanagedType.I1)]
    public static partial bool Init(int resWidth, int resHeight);

    /// <summary>
    /// Closes the rendering engine and deallocates all resources.
    /// <para>
    /// This function shuts down the rendering system and frees all allocated memory, including the resources associated with the created lights.
    /// </para>
    /// </summary>
    /// <seealso>R3D_Close</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_Close")]
    public static partial void Close();

    /// <summary>
    /// Gets the current internal resolution.
    /// <para>
    /// This function retrieves the current internal resolution being used by the rendering engine.
    /// </para>
    /// </summary>
    /// <param name="width">Pointer to store the width of the internal resolution.</param>
    /// <param name="height">Pointer to store the height of the internal resolution.</param>
    /// <seealso>R3D_GetResolution</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_GetResolution")]
    public static partial void GetResolution(out int width, out int height);

    /// <summary>
    /// Updates the internal resolution.
    /// <para>
    /// This function changes the internal resolution of the rendering engine. Note that this process destroys and recreates all framebuffers, which may be a slow operation.
    /// </para>
    /// </summary>
    /// <param name="width">The new width for the internal resolution.</param>
    /// <param name="height">The new height for the internal resolution.</param>
    /// <remarks>
    /// <b>Warning:</b>
    /// This function may be slow due to the destruction and recreation of framebuffers.
    /// </remarks>
    /// <seealso>R3D_UpdateResolution</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_UpdateResolution")]
    public static partial void UpdateResolution(int width, int height);

    /// <summary>
    /// Retrieves the current anti-aliasing mode used for rendering.
    /// </summary>
    /// <returns>The currently active R3D_AntiAliasing mode.</returns>
    /// <seealso>R3D_GetAntiAliasing</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_GetAntiAliasing")]
    public static partial AntiAliasing GetAntiAliasing();

    /// <summary>
    /// Sets the anti-aliasing mode for rendering.
    /// </summary>
    /// <param name="mode">The desired R3D_AntiAliasing mode.</param>
    /// <seealso>R3D_SetAntiAliasing</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_SetAntiAliasing")]
    public static partial void SetAntiAliasing(AntiAliasing mode);

    /// <summary>
    /// Retrieves the current aspect ratio handling mode.
    /// </summary>
    /// <returns>The currently active R3D_AspectMode.</returns>
    /// <seealso>R3D_GetAspectMode</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_GetAspectMode")]
    public static partial AspectMode GetAspectMode();

    /// <summary>
    /// Sets the aspect ratio handling mode for rendering.
    /// </summary>
    /// <param name="mode">The desired R3D_AspectMode.</param>
    /// <seealso>R3D_SetAspectMode</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_SetAspectMode")]
    public static partial void SetAspectMode(AspectMode mode);

    /// <summary>
    /// Retrieves the current upscaling/filtering method.
    /// </summary>
    /// <returns>The currently active R3D_UpscaleMode.</returns>
    /// <seealso>R3D_GetUpscaleMode</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_GetUpscaleMode")]
    public static partial UpscaleMode GetUpscaleMode();

    /// <summary>
    /// Sets the upscaling/filtering method for rendering output.
    /// </summary>
    /// <param name="mode">The desired R3D_UpscaleMode.</param>
    /// <seealso>R3D_SetUpscaleMode</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_SetUpscaleMode")]
    public static partial void SetUpscaleMode(UpscaleMode mode);

    /// <summary>
    /// Retrieves the current downscaling mode used for rendering.
    /// </summary>
    /// <returns>The currently active R3D_DownscaleMode.</returns>
    /// <seealso>R3D_GetDownscaleMode</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_GetDownscaleMode")]
    public static partial DownscaleMode GetDownscaleMode();

    /// <summary>
    /// Sets the downscaling mode for rendering output.
    /// </summary>
    /// <param name="mode">The desired R3D_DownscaleMode.</param>
    /// <seealso>R3D_SetDownscaleMode</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_SetDownscaleMode")]
    public static partial void SetDownscaleMode(DownscaleMode mode);

    /// <summary>
    /// Gets the current output mode.
    /// </summary>
    /// <returns>The currently active R3D_OutputMode.</returns>
    /// <seealso>R3D_GetOutputMode</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_GetOutputMode")]
    public static partial OutputMode GetOutputMode();

    /// <summary>
    /// Sets the output mode for rendering.
    /// </summary>
    /// <param name="mode">The R3D_OutputMode to use.</param>
    /// <remarks>
    /// Nothing will be output if the requested target has not been created / used.
    /// </remarks>
    /// <seealso>R3D_SetOutputMode</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_SetOutputMode")]
    public static partial void SetOutputMode(OutputMode mode);

    /// <summary>
    /// Sets the default texture filtering mode.
    /// <para>
    /// This function defines the default texture filter that will be applied to all subsequently loaded textures, including those used in materials, sprites, and other resources.
    /// </para>
    /// <para>
    /// If a trilinear or anisotropic filter is selected, mipmaps will be automatically generated for the textures, but they will not be generated when using nearest or bilinear filtering.
    /// </para>
    /// <para>
    /// The default texture filter mode is `TEXTURE_FILTER_TRILINEAR`.
    /// </para>
    /// </summary>
    /// <param name="filter">The texture filtering mode to be applied by default.</param>
    /// <seealso>R3D_SetTextureFilter</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_SetTextureFilter")]
    public static partial void SetTextureFilter(TextureFilter filter);

    /// <summary>
    /// Set the working color space for user-provided surface colors and color textures.
    /// <para>
    /// Defines how all *color inputs* should be interpreted:
    /// <list type="bullet">
    /// <item><description>surface colors provided in materials (e.g. albedo/emission tints)</description></item>
    /// <item><description>color textures such as albedo and emission maps</description></item>
    /// </list>
    /// </para>
    /// <para>
    /// When set to sRGB, these values are converted to linear before shading. When set to linear, values are used as-is.
    /// </para>
    /// <para>
    /// This does NOT affect lighting inputs (direct or indirect light), which are always expected to be provided in linear space.
    /// </para>
    /// <para>
    /// The default color space is `R3D_COLORSPACE_SRGB`.
    /// </para>
    /// </summary>
    /// <param name="space">Color space to use for color inputs (linear or sRGB).</param>
    /// <seealso>R3D_SetColorSpace</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_SetColorSpace")]
    public static partial void SetColorSpace(ColorSpace space);

    /// <summary>
    /// Get the currently active global rendering layers.
    /// <para>
    /// Returns the bitfield representing the currently active layers in the renderer. By default, the internal active layers are set to 0, which means that any non-zero layer assigned to an object will NOT be rendered unless explicitly activated.
    /// </para>
    /// </summary>
    /// <returns>R3D_Layer Bitfield of active layers.</returns>
    /// <seealso>R3D_GetActiveLayers</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_GetActiveLayers")]
    public static partial Layer GetActiveLayers();

    /// <summary>
    /// Set the active global rendering layers.
    /// <para>
    /// Replaces the current set of active layers with the given bitfield.
    /// </para>
    /// </summary>
    /// <param name="bitfield">Bitfield representing the layers to activate.</param>
    /// <seealso>R3D_SetActiveLayers</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_SetActiveLayers")]
    public static partial void SetActiveLayers(Layer bitfield);

    /// <summary>
    /// Enable one or more layers without affecting other active layers.
    /// <para>
    /// This function sets the bits in the global active layers corresponding to the bits in the provided bitfield. Layers already active remain active.
    /// </para>
    /// </summary>
    /// <param name="bitfield">Bitfield representing one or more layers to enable.</param>
    /// <seealso>R3D_EnableLayers</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_EnableLayers")]
    public static partial void EnableLayers(Layer bitfield);

    /// <summary>
    /// Disable one or more layers without affecting other active layers.
    /// <para>
    /// This function clears the bits in the global active layers corresponding to the bits in the provided bitfield. Layers not included in the bitfield remain unchanged.
    /// </para>
    /// </summary>
    /// <param name="bitfield">Bitfield representing one or more layers to disable.</param>
    /// <seealso>R3D_DisableLayers</seealso>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_DisableLayers")]
    public static partial void DisableLayers(Layer bitfield);

}
