// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

using System;
using System.Numerics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Security;
using Raylib_cs;
using static Raylib_cs.Raylib;

namespace R3D_cs;

// r3d_sky_shader.h;

[SuppressUnmanagedCodeSecurity]
public static unsafe partial class R3D
{

    /// <summary>
    /// Loads a sky shader from a file.
    /// <para>
    /// The shader must define a single entry point: `void fragment()`. Any other entry point, such as `vertex()`, or any varyings will be ignored.
    /// </para>
    /// </summary>
    /// <param name="filePath">Path to the shader source file.</param>
    /// <returns>Pointer to the loaded sky shader, or NULL on failure.</returns>
    /// <remarks>
    /// Native: <c>R3D_LoadSkyShader</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_LoadSkyShader", StringMarshalling = StringMarshalling.Utf8)]
    public static partial SkyShader LoadSkyShader(string filePath);

    /// <summary>
    /// Loads a sky shader from a source code string in memory.
    /// <para>
    /// The shader must define a single entry point: `void fragment()`. Any other entry point, such as `vertex()`, or any varyings will be ignored.
    /// </para>
    /// </summary>
    /// <param name="code">Null-terminated shader source code.</param>
    /// <returns>Pointer to the loaded sky shader, or NULL on failure.</returns>
    /// <remarks>
    /// Native: <c>R3D_LoadSkyShaderFromMemory</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_LoadSkyShaderFromMemory", StringMarshalling = StringMarshalling.Utf8)]
    public static partial SkyShader LoadSkyShaderFromMemory(string code);

    /// <summary>
    /// Creates an alias of an existing sky shader.
    /// <para>
    /// The alias shares the same compiled program as the original but holds its own independent uniform and sampler state. A typical use case is to pre-configure several aliases with different uniforms or textures, avoiding the need to reconfigure the shader on every skybox switch.
    /// </para>
    /// <para>
    /// Uniform and sampler state is copied from the original at the moment this function is called, not from the shader source defaults. Any values set on the original after compilation but before this call will be reflected in the alias; values set afterward will not.
    /// </para>
    /// </summary>
    /// <param name="shader">The original sky shader to alias.</param>
    /// <returns>Pointer to the alias, or NULL on failure.</returns>
    /// <remarks>
    /// The alias does not own the program. Always unload all aliases before unloading the original, or the alias program references become dangling.
    /// Native: <c>R3D_LoadSkyShaderAlias</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_LoadSkyShaderAlias")]
    public static partial SkyShader LoadSkyShaderAlias(SkyShader shader);

    /// <summary>
    /// Unloads and destroys a sky shader.
    /// <para>
    /// If the shader owns its program shaders (i.e. it was created withR3D_LoadSkyShader orR3D_LoadSkyShaderFromMemory), they are deleted. Aliases created from this shader viaR3D_LoadSkyShaderAlias must be unloaded beforehand, as they share the same programs and will be left with dangling references.
    /// </para>
    /// </summary>
    /// <param name="shader">Sky shader to unload.</param>
    /// <remarks>
    /// Native: <c>R3D_UnloadSkyShader</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_UnloadSkyShader")]
    public static partial void UnloadSkyShader(SkyShader shader);

    /// <summary>
    /// Sets a uniform value for all subsequent sky generations.
    /// <para>
    /// Supported types: bool, int, float, ivec2, ivec3, ivec4, vec2, vec3, vec4, mat2, mat3, mat4
    /// </para>
    /// </summary>
    /// <param name="shader">Target sky shader. May be NULL. In that case, the call is ignored and a warning is logged.</param>
    /// <param name="name">Name of the uniform. Must not be NULL.</param>
    /// <param name="value">Pointer to the uniform value. Must not be NULL.</param>
    /// <remarks>
    /// <b>Warning:</b>
    /// Boolean values are read as 4 bytes.
    /// Native: <c>R3D_SetSkyShaderUniform</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_SetSkyShaderUniform", StringMarshalling = StringMarshalling.Utf8)]
    public static partial void SetSkyShaderUniform(SkyShader shader, string name, void* value);

    /// <summary>
    /// Sets a uniform value for all subsequent sky generations.
    /// <para>
    /// Supported samplers: sampler1D, sampler2D, sampler3D, samplerCube
    /// </para>
    /// </summary>
    /// <param name="shader">Target sky shader. May be NULL. In that case, the call is ignored and a warning is logged.</param>
    /// <param name="name">Name of the sampler uniform. Must not be NULL.</param>
    /// <param name="texture">Texture to bind to the sampler.</param>
    /// <remarks>
    /// Native: <c>R3D_SetSkyShaderSampler</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_SetSkyShaderSampler", StringMarshalling = StringMarshalling.Utf8)]
    public static partial void SetSkyShaderSampler(SkyShader shader, string name, Texture2D texture);

}
