// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

using System;
using System.Numerics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Security;
using Raylib_cs;
using static Raylib_cs.Raylib;

namespace R3D_cs;

// r3d_kinematics.h;

[SuppressUnmanagedCodeSecurity]
public static unsafe partial class R3D
{

    /// <summary>
    /// Remove the normal component from a velocity vector (project onto a plane)
    /// </summary>
    /// <param name="velocity">Incoming velocity</param>
    /// <param name="normal">Surface normal (must be normalized)</param>
    /// <returns>Velocity with the component along normal removed</returns>
    /// <remarks>
    /// Native: <c>R3D_ClipVelocity</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_ClipVelocity")]
    public static partial Vector3 ClipVelocity(Vector3 velocity, Vector3 normal);

    /// <summary>
    /// Reflect a velocity vector off a surface
    /// </summary>
    /// <param name="velocity">Incoming velocity</param>
    /// <param name="normal">Surface normal (must be normalized)</param>
    /// <param name="bounciness">Coefficient of restitution (0=no bounce, 1=perfect bounce)</param>
    /// <returns>Reflected velocity scaled by bounciness</returns>
    /// <remarks>
    /// Native: <c>R3D_ReflectVelocity</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_ReflectVelocity")]
    public static partial Vector3 ReflectVelocity(Vector3 velocity, Vector3 normal, float bounciness);

    /// <summary>
    /// Resolve a velocity vector against a sweep collision, sliding along the hit surface
    /// </summary>
    /// <param name="velocity">Desired movement vector</param>
    /// <param name="collision">Sweep collision result to resolve against</param>
    /// <param name="outNormal">Optional: receives the collision normal if a hit occurred</param>
    /// <returns>Resolved velocity (safe movement + clipped remainder)</returns>
    /// <remarks>
    /// Native: <c>R3D_SlideVelocity</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_SlideVelocity")]
    public static partial Vector3 SlideVelocity(Vector3 velocity, SweepCollision collision, ref Vector3 outNormal);

    /// <summary>
    /// Slide sphere along bounding box surface, resolving collisions
    /// </summary>
    /// <param name="center">Sphere center position</param>
    /// <param name="radius">Sphere radius</param>
    /// <param name="velocity">Desired movement vector</param>
    /// <param name="box">Obstacle bounding box</param>
    /// <param name="outNormal">Optional: receives collision normal if collision occurred</param>
    /// <returns>Actual movement applied (may be reduced/redirected by collision)</returns>
    /// <remarks>
    /// Native: <c>R3D_SlideSphereBoundingBox</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_SlideSphereBoundingBox")]
    public static partial Vector3 SlideSphereBoundingBox(Vector3 center, float radius, Vector3 velocity, BoundingBox box, ref Vector3 outNormal);

    /// <summary>
    /// Slide sphere along mesh surface, resolving collisions
    /// </summary>
    /// <param name="center">Sphere center position</param>
    /// <param name="radius">Sphere radius</param>
    /// <param name="velocity">Desired movement vector</param>
    /// <param name="mesh">Mesh data to collide against</param>
    /// <param name="transform">Mesh world transform</param>
    /// <param name="outNormal">Optional: receives collision normal if collision occurred</param>
    /// <returns>Actual movement applied (may be reduced/redirected by collision)</returns>
    /// <remarks>
    /// Native: <c>R3D_SlideSphereMesh</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_SlideSphereMesh")]
    public static partial Vector3 SlideSphereMesh(Vector3 center, float radius, Vector3 velocity, MeshData mesh, Matrix4x4 transform, ref Vector3 outNormal);

    /// <summary>
    /// Slide capsule along bounding box surface, resolving collisions
    /// </summary>
    /// <param name="capsule">Capsule shape</param>
    /// <param name="velocity">Desired movement vector</param>
    /// <param name="box">Obstacle bounding box</param>
    /// <param name="outNormal">Optional: receives collision normal if collision occurred</param>
    /// <returns>Actual movement applied (may be reduced/redirected by collision)</returns>
    /// <remarks>
    /// Native: <c>R3D_SlideCapsuleBoundingBox</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_SlideCapsuleBoundingBox")]
    public static partial Vector3 SlideCapsuleBoundingBox(Capsule capsule, Vector3 velocity, BoundingBox box, ref Vector3 outNormal);

    /// <summary>
    /// Slide capsule along mesh surface, resolving collisions
    /// </summary>
    /// <param name="capsule">Capsule shape</param>
    /// <param name="velocity">Desired movement vector</param>
    /// <param name="mesh">Mesh data to collide against</param>
    /// <param name="transform">Mesh world transform</param>
    /// <param name="outNormal">Optional: receives collision normal if collision occurred</param>
    /// <returns>Actual movement applied (may be reduced/redirected by collision)</returns>
    /// <remarks>
    /// Native: <c>R3D_SlideCapsuleMesh</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_SlideCapsuleMesh")]
    public static partial Vector3 SlideCapsuleMesh(Capsule capsule, Vector3 velocity, MeshData mesh, Matrix4x4 transform, ref Vector3 outNormal);

    /// <summary>
    /// Push sphere out of bounding box if penetrating
    /// </summary>
    /// <param name="center">Sphere center (modified in place if penetrating)</param>
    /// <param name="radius">Sphere radius</param>
    /// <param name="box">Obstacle box</param>
    /// <param name="outPenetration">Optional: receives penetration depth</param>
    /// <returns>true if depenetration occurred</returns>
    /// <remarks>
    /// Native: <c>R3D_DepenetrateSphereBoundingBox</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_DepenetrateSphereBoundingBox")]
    [return: MarshalAs(UnmanagedType.I1)]
    public static partial bool DepenetrateSphereBoundingBox(ref Vector3 center, float radius, BoundingBox box, ref float outPenetration);

    /// <summary>
    /// Push capsule out of bounding box if penetrating
    /// </summary>
    /// <param name="capsule">Capsule shape (modified in place if penetrating)</param>
    /// <param name="box">Obstacle box</param>
    /// <param name="outPenetration">Optional: receives penetration depth</param>
    /// <returns>true if depenetration occurred</returns>
    /// <remarks>
    /// Native: <c>R3D_DepenetrateCapsuleBoundingBox</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_DepenetrateCapsuleBoundingBox")]
    [return: MarshalAs(UnmanagedType.I1)]
    public static partial bool DepenetrateCapsuleBoundingBox(ref Capsule capsule, BoundingBox box, ref float outPenetration);

    /// <summary>
    /// Check if a sphere is supported by a bounding box in a given direction
    /// </summary>
    /// <param name="center">Sphere center</param>
    /// <param name="radius">Sphere radius</param>
    /// <param name="direction">Ray direction to probe (must be normalized)</param>
    /// <param name="distance">Maximum probe distance beyond the sphere surface</param>
    /// <param name="box">Bounding box to test against</param>
    /// <param name="outHit">Optional: receives raycast hit info</param>
    /// <returns>true if a surface is within reach in the given direction</returns>
    /// <remarks>
    /// Native: <c>R3D_CheckSphereSupportBoundingBox</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_CheckSphereSupportBoundingBox")]
    [return: MarshalAs(UnmanagedType.I1)]
    public static partial bool CheckSphereSupportBoundingBox(Vector3 center, float radius, Vector3 direction, float distance, BoundingBox box, ref RayCollision outHit);

    /// <summary>
    /// Check if a sphere is supported by mesh geometry in a given direction
    /// </summary>
    /// <param name="center">Sphere center</param>
    /// <param name="radius">Sphere radius</param>
    /// <param name="direction">Ray direction to probe (must be normalized)</param>
    /// <param name="distance">Maximum probe distance beyond the sphere surface</param>
    /// <param name="mesh">Mesh data to test against</param>
    /// <param name="transform">Mesh world transform</param>
    /// <param name="outHit">Optional: receives raycast hit info</param>
    /// <returns>true if a surface is within reach in the given direction</returns>
    /// <remarks>
    /// Native: <c>R3D_CheckSphereSupportMesh</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_CheckSphereSupportMesh")]
    [return: MarshalAs(UnmanagedType.I1)]
    public static partial bool CheckSphereSupportMesh(Vector3 center, float radius, Vector3 direction, float distance, MeshData mesh, Matrix4x4 transform, ref RayCollision outHit);

    /// <summary>
    /// Check if a capsule is supported by a bounding box in a given direction
    /// </summary>
    /// <param name="capsule">Capsule shape</param>
    /// <param name="direction">Ray direction to probe (must be normalized)</param>
    /// <param name="distance">Maximum probe distance beyond the capsule surface</param>
    /// <param name="box">Bounding box to test against</param>
    /// <param name="outHit">Optional: receives raycast hit info</param>
    /// <returns>true if a surface is within reach in the given direction</returns>
    /// <remarks>
    /// Native: <c>R3D_CheckCapsuleSupportBoundingBox</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_CheckCapsuleSupportBoundingBox")]
    [return: MarshalAs(UnmanagedType.I1)]
    public static partial bool CheckCapsuleSupportBoundingBox(Capsule capsule, Vector3 direction, float distance, BoundingBox box, ref RayCollision outHit);

    /// <summary>
    /// Check if a capsule is supported by mesh geometry in a given direction
    /// </summary>
    /// <param name="capsule">Capsule shape</param>
    /// <param name="direction">Ray direction to probe (must be normalized)</param>
    /// <param name="distance">Maximum probe distance beyond the capsule surface</param>
    /// <param name="mesh">Mesh data to test against</param>
    /// <param name="transform">Mesh world transform</param>
    /// <param name="outHit">Optional: receives raycast hit info</param>
    /// <returns>true if a surface is within reach in the given direction</returns>
    /// <remarks>
    /// Native: <c>R3D_CheckCapsuleSupportMesh</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_CheckCapsuleSupportMesh")]
    [return: MarshalAs(UnmanagedType.I1)]
    public static partial bool CheckCapsuleSupportMesh(Capsule capsule, Vector3 direction, float distance, MeshData mesh, Matrix4x4 transform, ref RayCollision outHit);

    /// <summary>
    /// Sweep sphere against single point
    /// </summary>
    /// <param name="center">Sphere center position</param>
    /// <param name="radius">Sphere radius</param>
    /// <param name="velocity">Movement vector (direction and magnitude)</param>
    /// <param name="point">Point to test against</param>
    /// <returns>Sweep collision info (hit, time, point, normal)</returns>
    /// <remarks>
    /// Native: <c>R3D_SweepSpherePoint</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_SweepSpherePoint")]
    public static partial SweepCollision SweepSpherePoint(Vector3 center, float radius, Vector3 velocity, Vector3 point);

    /// <summary>
    /// Sweep sphere against line segment
    /// </summary>
    /// <param name="center">Sphere center position</param>
    /// <param name="radius">Sphere radius</param>
    /// <param name="velocity">Movement vector (direction and magnitude)</param>
    /// <param name="a">Segment start point</param>
    /// <param name="b">Segment end point</param>
    /// <returns>Sweep collision info (hit, time, point, normal)</returns>
    /// <remarks>
    /// Native: <c>R3D_SweepSphereSegment</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_SweepSphereSegment")]
    public static partial SweepCollision SweepSphereSegment(Vector3 center, float radius, Vector3 velocity, Vector3 a, Vector3 b);

    /// <summary>
    /// Sweep sphere against triangle plane (no edge/vertex clipping)
    /// </summary>
    /// <param name="center">Sphere center position</param>
    /// <param name="radius">Sphere radius</param>
    /// <param name="velocity">Movement vector (direction and magnitude)</param>
    /// <param name="a">Triangle vertex A</param>
    /// <param name="b">Triangle vertex B</param>
    /// <param name="c">Triangle vertex C</param>
    /// <returns>Sweep collision info (hit, time, point, normal)</returns>
    /// <remarks>
    /// Native: <c>R3D_SweepSphereTrianglePlane</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_SweepSphereTrianglePlane")]
    public static partial SweepCollision SweepSphereTrianglePlane(Vector3 center, float radius, Vector3 velocity, Vector3 a, Vector3 b, Vector3 c);

    /// <summary>
    /// Sweep sphere against triangle with edge/vertex handling
    /// </summary>
    /// <param name="center">Sphere center position</param>
    /// <param name="radius">Sphere radius</param>
    /// <param name="velocity">Movement vector (direction and magnitude)</param>
    /// <param name="a">Triangle vertex A</param>
    /// <param name="b">Triangle vertex B</param>
    /// <param name="c">Triangle vertex C</param>
    /// <returns>Sweep collision info (hit, time, point, normal)</returns>
    /// <remarks>
    /// Native: <c>R3D_SweepSphereTriangle</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_SweepSphereTriangle")]
    public static partial SweepCollision SweepSphereTriangle(Vector3 center, float radius, Vector3 velocity, Vector3 a, Vector3 b, Vector3 c);

    /// <summary>
    /// Sweep sphere along velocity vector
    /// </summary>
    /// <param name="center">Sphere center position</param>
    /// <param name="radius">Sphere radius</param>
    /// <param name="velocity">Movement vector (direction and magnitude)</param>
    /// <param name="box">Obstacle bounding box</param>
    /// <returns>Sweep collision info (hit, distance, point, normal)</returns>
    /// <remarks>
    /// Native: <c>R3D_SweepSphereBoundingBox</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_SweepSphereBoundingBox")]
    public static partial SweepCollision SweepSphereBoundingBox(Vector3 center, float radius, Vector3 velocity, BoundingBox box);

    /// <summary>
    /// Sweep sphere along velocity vector against mesh geometry
    /// </summary>
    /// <param name="center">Sphere center position</param>
    /// <param name="radius">Sphere radius</param>
    /// <param name="velocity">Movement vector (direction and magnitude)</param>
    /// <param name="mesh">Mesh data to test against</param>
    /// <param name="transform">Mesh world transform</param>
    /// <returns>Sweep collision info (hit, time, point, normal)</returns>
    /// <remarks>
    /// Native: <c>R3D_SweepSphereMesh</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_SweepSphereMesh")]
    public static partial SweepCollision SweepSphereMesh(Vector3 center, float radius, Vector3 velocity, MeshData mesh, Matrix4x4 transform);

    /// <summary>
    /// Sweep capsule along velocity vector
    /// </summary>
    /// <param name="capsule">Capsule shape to sweep</param>
    /// <param name="velocity">Movement vector (direction and magnitude)</param>
    /// <param name="box">Obstacle bounding box</param>
    /// <returns>Sweep collision info (hit, distance, point, normal)</returns>
    /// <remarks>
    /// Native: <c>R3D_SweepCapsuleBoundingBox</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_SweepCapsuleBoundingBox")]
    public static partial SweepCollision SweepCapsuleBoundingBox(Capsule capsule, Vector3 velocity, BoundingBox box);

    /// <summary>
    /// Sweep capsule along velocity vector against mesh geometry
    /// </summary>
    /// <param name="capsule">Capsule shape to sweep</param>
    /// <param name="velocity">Movement vector (direction and magnitude)</param>
    /// <param name="mesh">Mesh data to test against</param>
    /// <param name="transform">Mesh world transform</param>
    /// <returns>Sweep collision info (hit, time, point, normal)</returns>
    /// <remarks>
    /// Native: <c>R3D_SweepCapsuleMesh</c>
    /// </remarks>
    [LibraryImport(NativeLibName, EntryPoint = "R3D_SweepCapsuleMesh")]
    public static partial SweepCollision SweepCapsuleMesh(Capsule capsule, Vector3 velocity, MeshData mesh, Matrix4x4 transform);

}
