// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

using System;
using System.Numerics;
using System.Runtime.InteropServices;
using Raylib_cs;

namespace R3D_cs;

/// <summary>
/// Albedo (base color) map.
/// <para>
/// Provides the base color texture and a color multiplier.
/// </para>
/// </summary>
/// <remarks>
/// Native: <c>R3D_AlbedoMap</c>
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public struct AlbedoMap
{
    /// <summary>
    /// Base color texture (default: WHITE)
    /// </summary>
    /// <remarks>
    /// Native: <c>texture</c>
    /// </remarks>
    public Texture2D Texture;

    /// <summary>
    /// Color multiplier (default: WHITE)
    /// </summary>
    /// <remarks>
    /// Native: <c>color</c>
    /// </remarks>
    public Color Color;

}
