// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

using System;
using System.Numerics;
using System.Runtime.InteropServices;
using Raylib_cs;

namespace R3D_cs;

/// <summary>
/// Global environment lighting data.
/// <para>
/// An ambient map is built from a cubemap (like a skybox) and preprocessed into two specialized textures:
/// </para>
/// <para>
/// <list type="bullet">
/// <item><description>irradiance: Low-frequency lighting used for diffuse IBL. Captures soft ambient light from all directions.</description></item>
/// </list>
/// </para>
/// <para>
/// <list type="bullet">
/// <item><description>prefilter: Mipmapped environment used for specular reflections. Higher mip levels simulate rougher surfaces.</description></item>
/// </list>
/// </para>
/// <para>
/// Both textures are derived from the same source cubemap, but serve different shading purposes.
/// </para>
/// </summary>
/// <remarks>
/// Native: <c>R3D_AmbientMap</c>
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public struct AmbientMap
{
    /// <summary>
    /// Components generated for this map
    /// </summary>
    /// <remarks>
    /// Native: <c>flags</c>
    /// </remarks>
    public AmbientFlags Flags;

    /// <summary>
    /// Diffuse IBL cubemap (may be 0 if not generated)
    /// </summary>
    /// <remarks>
    /// Native: <c>irradiance</c>
    /// </remarks>
    public uint Irradiance;

    /// <summary>
    /// Specular prefiltered cubemap (may be 0 if not generated)
    /// </summary>
    /// <remarks>
    /// Native: <c>prefilter</c>
    /// </remarks>
    public uint Prefilter;

}
