// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

using System;
using System.Numerics;
using System.Runtime.InteropServices;
using Raylib_cs;

namespace R3D_cs;

/// <summary>
/// Animation track storing keyframe times and values.
/// <para>
/// Represents a single animated property (translation, rotation or scale). Keys are sampled by time and interpolated at runtime.
/// </para>
/// </summary>
/// <seealso>R3D_AnimationTrack</seealso>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct AnimationTrack
{
    /// <summary>
    /// Keyframe times (sorted, in animation ticks).
    /// </summary>
    /// <seealso>times</seealso>
    public float* Times;

    /// <summary>
    /// Keyframe values (Vector3 or Quaternion).
    /// </summary>
    /// <seealso>values</seealso>
    public void* Values;

    /// <summary>
    /// Number of keyframes.
    /// </summary>
    /// <seealso>count</seealso>
    public int Count;

}
