// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

using System;
using System.Numerics;
using System.Runtime.InteropServices;
using System.Text;
using Raylib_cs;

namespace R3D_cs;

/// <remarks>
/// Native: <c>R3D_AnimationTreeNode</c>
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public struct AnimationTreeNode
{
    private nint _handle;
}
