// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

using System;
using System.Numerics;
using System.Runtime.InteropServices;
using Raylib_cs;

namespace R3D_cs;

/// <summary>
/// Manages playback and blending of multiple animations for a skeleton.
/// <para>
/// The animation player updates animation states, interpolates keyframes, blends animations according to their weights, and stores the resulting local and global bone transforms. It also supports GPU skinning by uploading the global pose into a texture.
/// </para>
/// </summary>
/// <remarks>
/// Native: <c>R3D_AnimationPlayer</c>
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct AnimationPlayer
{
    /// <summary>
    /// Array of active animation states, one per animation.
    /// </summary>
    /// <remarks>
    /// Native: <c>states</c>
    /// </remarks>
    internal AnimationState* _states;

    /// <summary>
    /// Animation library providing the available animations.
    /// </summary>
    /// <remarks>
    /// Native: <c>animLib</c>
    /// </remarks>
    public AnimationLib AnimLib;

    /// <summary>
    /// Skeleton to animate.
    /// </summary>
    /// <remarks>
    /// Native: <c>skeleton</c>
    /// </remarks>
    public Skeleton Skeleton;

    /// <summary>
    /// Array of bone transforms representing the blended local pose.
    /// </summary>
    /// <remarks>
    /// Native: <c>localPose</c>
    /// </remarks>
    internal Matrix4x4* _localPose;

    /// <summary>
    /// Array of bone transforms in model space, obtained by hierarchical accumulation.
    /// </summary>
    /// <remarks>
    /// Native: <c>modelPose</c>
    /// </remarks>
    internal Matrix4x4* _modelPose;

    /// <summary>
    /// Array of final skinning matrices (invBind * modelPose), sent to the GPU.
    /// </summary>
    /// <remarks>
    /// Native: <c>skinBuffer</c>
    /// </remarks>
    internal Matrix4x4* _skinBuffer;

    /// <summary>
    /// GPU texture ID storing the skinning matrices as a 1D RGBA16F texture.
    /// </summary>
    /// <remarks>
    /// Native: <c>skinTexture</c>
    /// </remarks>
    public uint SkinTexture;

    /// <summary>
    /// Callback function to receive animation events.
    /// </summary>
    /// <remarks>
    /// Native: <c>eventCallback</c>
    /// </remarks>
    public IntPtr EventCallback;

    /// <summary>
    /// Optional user data pointer passed to the callback.
    /// </summary>
    /// <remarks>
    /// Native: <c>eventUserData</c>
    /// </remarks>
    public IntPtr EventUserData;

    /// <summary>
    /// <see cref="States"/> as a <see cref="Span{T}"/>.
    /// </summary>
    public Span<AnimationState> States => _states != null ? new(_states, AnimLib.Count) : default;

    /// <summary>
    /// <see cref="LocalPose"/> as a <see cref="Span{T}"/>.
    /// </summary>
    public Span<Matrix4x4> LocalPose => _localPose != null ? new(_localPose, Skeleton.BoneCount) : default;

    /// <summary>
    /// <see cref="ModelPose"/> as a <see cref="Span{T}"/>.
    /// </summary>
    public Span<Matrix4x4> ModelPose => _modelPose != null ? new(_modelPose, Skeleton.BoneCount) : default;

    /// <summary>
    /// <see cref="SkinBuffer"/> as a <see cref="Span{T}"/>.
    /// </summary>
    public Span<Matrix4x4> SkinBuffer => _skinBuffer != null ? new(_skinBuffer, Skeleton.BoneCount) : default;

}
