// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

using System;
using System.Numerics;
using System.Runtime.InteropServices;
using Raylib_cs;

namespace R3D_cs;

/// <summary>
/// Callback type for manipulating the final animation.
/// </summary>
/// <param name="player">Pointer to the animation player used by the animation tree.</param>
/// <param name="boneIndex">Index of the processed bone.</param>
/// <param name="out">Transformation of the processed bone.</param>
/// <param name="userData">Optional user-defined data passed when the callback was registered.</param>
/// <remarks>
/// Native: <c>R3D_AnimationTreeCallback</c>
/// </remarks>
[UnmanagedFunctionPointer(CallingConvention.Cdecl)]
public unsafe delegate void AnimationTreeCallback(AnimationPlayer* player, int boneIndex, Transform* @out, IntPtr userData);

