// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

using System;
using System.Numerics;
using System.Runtime.InteropServices;
using Raylib_cs;

namespace R3D_cs;

/// <summary>
/// Animation channel controlling a single bone.
/// <para>
/// Contains animation tracks for translation, rotation and scale. The sampled tracks are combined to produce the bone local transform.
/// </para>
/// </summary>
/// <seealso>R3D_AnimationChannel</seealso>
[StructLayout(LayoutKind.Sequential)]
public struct AnimationChannel
{
    /// <summary>
    /// Translation track (Vector3).
    /// </summary>
    /// <seealso>translation</seealso>
    public AnimationTrack Translation;

    /// <summary>
    /// Rotation track (Quaternion).
    /// </summary>
    /// <seealso>rotation</seealso>
    public AnimationTrack Rotation;

    /// <summary>
    /// Scale track (Vector3).
    /// </summary>
    /// <seealso>scale</seealso>
    public AnimationTrack Scale;

    /// <summary>
    /// Index of the affected bone.
    /// </summary>
    /// <seealso>boneIndex</seealso>
    public int BoneIndex;

}
