// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

using System;
using System.Numerics;
using System.Runtime.InteropServices;
using Raylib_cs;

namespace R3D_cs;

/// <summary>
/// Callback type for receiving animation events.
/// </summary>
/// <param name="player">Pointer to the animation player emitting the event.</param>
/// <param name="eventType">Type of the event (finished, looped).</param>
/// <param name="animIndex">Index of the animation triggering the event.</param>
/// <param name="userData">Optional user-defined data passed when the callback was registered.</param>
/// <remarks>
/// Native: <c>R3D_AnimationEventCallback</c>
/// </remarks>
[UnmanagedFunctionPointer(CallingConvention.Cdecl)]
public unsafe delegate void AnimationEventCallback(AnimationPlayer* player, AnimationEvent eventType, int animIndex, IntPtr userData);

