// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

using System;
using System.Numerics;
using System.Runtime.InteropServices;
using Raylib_cs;

namespace R3D_cs;

/// <summary>
/// Callback type for manipulating the animation before it is used by the animation tree.
/// </summary>
/// <param name="animation">Pointer to the processed animation.</param>
/// <param name="state">Current animation state.</param>
/// <param name="boneIndex">Index of the processed bone.</param>
/// <param name="out">Transformation of the processed bone.</param>
/// <param name="userData">Optional user-defined data passed when the callback was registered.</param>
/// <remarks>
/// Native: <c>R3D_AnimationNodeCallback</c>
/// </remarks>
[UnmanagedFunctionPointer(CallingConvention.Cdecl)]
public unsafe delegate void AnimationNodeCallback(Animation* animation, AnimationState state, int boneIndex, Transform* @out, IntPtr userData);

