// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

using System;
using System.Numerics;
using System.Runtime.InteropServices;
using Raylib_cs;

namespace R3D_cs;

/// <summary>
/// Describes the playback state of a single animation within a player.
/// <para>
/// Tracks the current time, blending weight, speed, play/pause state, and looping behavior.
/// </para>
/// </summary>
/// <remarks>
/// Native: <c>R3D_AnimationState</c>
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public struct AnimationState
{
    /// <summary>
    /// Current playback time in animation ticks.
    /// </summary>
    /// <remarks>
    /// Native: <c>currentTime</c>
    /// </remarks>
    public float CurrentTime;

    /// <summary>
    /// Blending weight; any positive value is valid.
    /// </summary>
    /// <remarks>
    /// Native: <c>weight</c>
    /// </remarks>
    public float Weight;

    /// <summary>
    /// Playback speed; can be negative for reverse playback.
    /// </summary>
    /// <remarks>
    /// Native: <c>speed</c>
    /// </remarks>
    public float Speed;

    /// <summary>
    /// Whether the animation is currently playing.
    /// </summary>
    /// <remarks>
    /// Native: <c>play</c>
    /// </remarks>
    public bool Play;

    /// <summary>
    /// True to enable looping playback.
    /// </summary>
    /// <remarks>
    /// Native: <c>loop</c>
    /// </remarks>
    public bool Loop;

}
