// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

using System;
using System.Numerics;
using System.Runtime.InteropServices;
using System.Text;
using Raylib_cs;

namespace R3D_cs;

/// <summary>
/// Manages a tree structure of animation nodes.
/// <para>
/// Animation tree allows to define complex logic for switching and blending animations of associated animation player. It supports 5 different animation node types: Animation, Blend2, Add2, Switch and State Machine. It also fully supports root motion and bone masking in Blend2/Add2.
/// </para>
/// </summary>
/// <remarks>
/// Native: <c>R3D_AnimationTree</c>
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public struct AnimationTree
{
    /// <summary>
    /// Animation player and skeleton used by all animation nodes.
    /// </summary>
    /// <remarks>
    /// Native: <c>player</c>
    /// </remarks>
    public AnimationPlayer Player;

    /// <summary>
    /// Pointer to root animation node of the tree.
    /// </summary>
    /// <remarks>
    /// Native: <c>rootNode</c>
    /// </remarks>
    public AnimationTreeNode RootNode;

    /// <summary>
    /// Animation node pool of size nodePoolMaxSize.
    /// </summary>
    /// <remarks>
    /// Native: <c>nodePool</c>
    /// </remarks>
    public AnimationTreeNode NodePool;

    /// <summary>
    /// Current animation node pool size.
    /// </summary>
    /// <remarks>
    /// Native: <c>nodePoolSize</c>
    /// </remarks>
    public int NodePoolSize;

    /// <summary>
    /// Maximum number of animation nodes, defined during load.
    /// </summary>
    /// <remarks>
    /// Native: <c>nodePoolMaxSize</c>
    /// </remarks>
    public int NodePoolMaxSize;

    /// <summary>
    /// Optional root bone index, -1 if not defined.
    /// </summary>
    /// <remarks>
    /// Native: <c>rootBone</c>
    /// </remarks>
    public int RootBone;

    /// <summary>
    /// Callback function to receive and modify final animation transformation.
    /// </summary>
    /// <remarks>
    /// Native: <c>updateCallback</c>
    /// </remarks>
    public IntPtr UpdateCallback;

    /// <summary>
    /// Optional user data pointer passed to the callback.
    /// </summary>
    /// <remarks>
    /// Native: <c>updateUserData</c>
    /// </remarks>
    public IntPtr UpdateUserData;

}
