// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

namespace R3D_cs;

/// <remarks>Native: <c>R3D_AnimationStmIndex</c></remarks>
public struct AnimationStmIndex
{
    internal int id;

    public static explicit operator int(AnimationStmIndex handle) => handle.id;
    public static explicit operator AnimationStmIndex(int id) => new() { id = id };
}
