// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

using System;
using System.Numerics;
using System.Runtime.InteropServices;
using Raylib_cs;

namespace R3D_cs;

/// <summary>
/// Represents a collection of skeletal animations sharing the same skeleton.
/// <para>
/// Holds multiple animations that can be applied to compatible models or skeletons. Typically loaded together from a single 3D model file (e.g., GLTF, FBX) containing several animation clips.
/// </para>
/// </summary>
/// <seealso>R3D_AnimationLib</seealso>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct AnimationLib
{
    /// <summary>
    /// Array of animations included in this library.
    /// </summary>
    /// <seealso>animations</seealso>
    public Animation* Animations;

    /// <summary>
    /// Number of animations contained in the library.
    /// </summary>
    /// <seealso>count</seealso>
    public int Count;

}
