// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

using System;
using System.Numerics;
using System.Runtime.InteropServices;
using System.Text;
using Raylib_cs;

namespace R3D_cs;

/// <summary>
/// Parameters for animation tree node Animation.
/// <para>
/// Animation is a leaf node, holding the R3D_Animation structure.
/// </para>
/// </summary>
/// <remarks>
/// Native: <c>R3D_AnimationNodeParams</c>
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct AnimationNodeParams
{
    /// <summary>
    /// Animation name (null-terminated string).
    /// </summary>
    /// <remarks>
    /// Native: <c>name</c>
    /// </remarks>
    internal fixed byte _name[32];

    /// <inheritdoc cref="_name"/>
    public string Name
    {
        get
        {
            fixed (byte* ptr = _name)
            {
                int len = 0;
                while (len < 32 && ptr[len] != 0) len++;
                return Encoding.UTF8.GetString(ptr, len);
            }
        }
        set
        {
            byte[] utf8 = Encoding.UTF8.GetBytes(value);
            int len = Math.Min(utf8.Length, 31);
            for (int i = 0; i < len; i++) _name[i] = utf8[i];
            _name[len] = 0;
        }
    }

    /// <summary>
    /// Animation state.
    /// </summary>
    /// <remarks>
    /// Native: <c>state</c>
    /// </remarks>
    public AnimationState State;

    /// <summary>
    /// Flag to control whether the animation is considered done when looped; yes when true.
    /// </summary>
    /// <remarks>
    /// Native: <c>looper</c>
    /// </remarks>
    public bool Looper;

    /// <summary>
    /// Callback function to receive and modify animation transformation before been used.
    /// </summary>
    /// <remarks>
    /// Native: <c>evalCallback</c>
    /// </remarks>
    public IntPtr EvalCallback;

    /// <summary>
    /// Optional user data pointer passed to the callback.
    /// </summary>
    /// <remarks>
    /// Native: <c>evalUserData</c>
    /// </remarks>
    public IntPtr EvalUserData;

}
