// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

using System;
using System.Numerics;
using System.Runtime.InteropServices;
using Raylib_cs;

namespace R3D_cs;

/// <summary>
/// Animation track storing keyframe times and values.
/// <para>
/// Represents a single animated property (translation, rotation or scale). Keys are sampled by time and interpolated at runtime.
/// </para>
/// </summary>
/// <remarks>
/// Native: <c>R3D_AnimationTrack</c>
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct AnimationTrack
{
    /// <summary>
    /// Keyframe times (sorted, in animation ticks).
    /// </summary>
    /// <remarks>
    /// Native: <c>times</c>
    /// </remarks>
    internal float* _times;

    /// <summary>
    /// Keyframe values (Vector3 or Quaternion).
    /// </summary>
    /// <remarks>
    /// Native: <c>values</c>
    /// </remarks>
    public void* Values;

    /// <summary>
    /// Number of keyframes.
    /// </summary>
    /// <remarks>
    /// Native: <c>count</c>
    /// </remarks>
    public int Count;

    /// <summary>
    /// <see cref="Times"/> as a <see cref="Span{T}"/>.
    /// </summary>
    public Span<float> Times => _times != null ? new(_times, Count) : default;

    /// <summary>
    /// <see cref="Values"/> cast to the specified type as a <see cref="Span{T}"/>.
    /// </summary>
    public Span<T> ValuesAs<T>() where T : unmanaged => Values != null ? new((T*)Values, Count) : default;

}
