// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

using System;
using System.Numerics;
using System.Runtime.InteropServices;
using Raylib_cs;

namespace R3D_cs;

/// <summary>
/// Represents a collection of skeletal animations sharing the same skeleton.
/// <para>
/// Holds multiple animations that can be applied to compatible models or skeletons. Typically loaded together from a single 3D model file (e.g., GLTF, FBX) containing several animation clips.
/// </para>
/// </summary>
/// <remarks>
/// Native: <c>R3D_AnimationLib</c>
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct AnimationLib
{
    /// <summary>
    /// Array of animations included in this library.
    /// </summary>
    /// <remarks>
    /// Native: <c>animations</c>
    /// </remarks>
    internal Animation* _animations;

    /// <summary>
    /// Number of animations contained in the library.
    /// </summary>
    /// <remarks>
    /// Native: <c>count</c>
    /// </remarks>
    internal int Count;

    /// <summary>
    /// <see cref="Animations"/> as a <see cref="Span{T}"/>.
    /// </summary>
    public Span<Animation> Animations => _animations != null ? new(_animations, Count) : default;

}
