// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

using System;
using System.Numerics;
using System.Runtime.InteropServices;
using System.Text;
using Raylib_cs;

namespace R3D_cs;

/// <summary>
/// Parameters for animation tree node Blend2.
/// <para>
/// Blend2 node blends channels of any two animation nodes together, with respecting optional bone mask.
/// </para>
/// </summary>
/// <remarks>
/// Native: <c>R3D_Blend2NodeParams</c>
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct Blend2NodeParams
{
    /// <summary>
    /// Pointer to bone mask structure, can be NULL; calculated by R3D_ComputeBoneMask().
    /// </summary>
    /// <remarks>
    /// Native: <c>boneMask</c>
    /// </remarks>
    internal BoneMask* _boneMask;

    /// <summary>
    /// Blend weight value, can be in interval from 0.0 to 1.0.
    /// </summary>
    /// <remarks>
    /// Native: <c>blend</c>
    /// </remarks>
    public float Blend;

}
