// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

using System;
using System.Numerics;
using System.Runtime.InteropServices;
using System.Text;
using Raylib_cs;

namespace R3D_cs;

/// <summary>
/// Bone mask for Blend2 and Add2 animation nodes.
/// <para>
/// Bone mask structure, can by created by R3D_ComputeBoneMask.
/// </para>
/// </summary>
/// <remarks>
/// Native: <c>R3D_BoneMask</c>
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct BoneMask
{
    /// <summary>
    /// Bit mask buffer for maximum of 256 bones (32bits * 8).
    /// </summary>
    /// <remarks>
    /// Native: <c>mask</c>
    /// </remarks>
    public fixed int Mask[8];

    /// <summary>
    /// Actual bones count.
    /// </summary>
    /// <remarks>
    /// Native: <c>boneCount</c>
    /// </remarks>
    public int BoneCount;

}
