// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

using System;
using System.Numerics;
using System.Runtime.InteropServices;
using System.Text;
using Raylib_cs;

namespace R3D_cs;

/// <summary>
/// Stores bone information for skeletal animation.
/// <para>
/// Contains the bone name and the index of its parent bone.
/// </para>
/// </summary>
/// <remarks>
/// Native: <c>R3D_BoneInfo</c>
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct BoneInfo
{
    /// <summary>
    /// Bone name (max 31 characters + null terminator).
    /// </summary>
    /// <remarks>
    /// Native: <c>name</c>
    /// </remarks>
    internal fixed byte _name[32];

    /// <inheritdoc cref="_name"/>
    public string Name
    {
        get
        {
            fixed (byte* ptr = _name)
            {
                int len = 0;
                while (len < 32 && ptr[len] != 0) len++;
                return Encoding.UTF8.GetString(ptr, len);
            }
        }
        set
        {
            byte[] utf8 = Encoding.UTF8.GetBytes(value);
            int len = Math.Min(utf8.Length, 31);
            for (int i = 0; i < len; i++) _name[i] = utf8[i];
            _name[len] = 0;
        }
    }

    /// <summary>
    /// Index of the parent bone (-1 if root).
    /// </summary>
    /// <remarks>
    /// Native: <c>parent</c>
    /// </remarks>
    public int Parent;

}
