// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

using System;
using System.Numerics;
using System.Runtime.InteropServices;
using Raylib_cs;

namespace R3D_cs;

/// <summary>
/// Stores bone information for skeletal animation.
/// <para>
/// Contains the bone name and the index of its parent bone.
/// </para>
/// </summary>
/// <remarks>
/// Native: <c>R3D_BoneInfo</c>
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct BoneInfo
{
    /// <summary>
    /// Bone name (max 31 characters + null terminator).
    /// </summary>
    /// <remarks>
    /// Native: <c>name</c>
    /// </remarks>
    public fixed byte Name[32];

    /// <summary>
    /// Index of the parent bone (-1 if root).
    /// </summary>
    /// <remarks>
    /// Native: <c>parent</c>
    /// </remarks>
    public int Parent;

}
