// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

using System;
using System.Numerics;
using System.Runtime.InteropServices;
using System.Text;
using Raylib_cs;

namespace R3D_cs;

/// <summary>
/// Quaternion-based 3D camera used by R3D.
/// <para>
/// Unlike raylib's Camera3D, this camera stores its orientation directly as a quaternion instead of using a target/up pair. It also stores near/far clipping planes and a layer mask used to filter visible renderables.
/// </para>
/// </summary>
/// <remarks>
/// Native: <c>R3D_Camera</c>
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public struct Camera
{
    /// <summary>
    /// Camera world-space position.
    /// </summary>
    /// <remarks>
    /// Native: <c>position</c>
    /// </remarks>
    public Vector3 Position;

    /// <summary>
    /// Camera world-space orientation.
    /// </summary>
    /// <remarks>
    /// Native: <c>rotation</c>
    /// </remarks>
    public Quaternion Rotation;

    /// <summary>
    /// Vertical field of view in degrees for perspective projection; vertical size for orthographic projection.
    /// </summary>
    /// <remarks>
    /// Native: <c>fovy</c>
    /// </remarks>
    public double Fovy;

    /// <summary>
    /// Distance to the near clipping plane.
    /// </summary>
    /// <remarks>
    /// Native: <c>nearPlane</c>
    /// </remarks>
    public double NearPlane;

    /// <summary>
    /// Distance to the far clipping plane.
    /// </summary>
    /// <remarks>
    /// Native: <c>farPlane</c>
    /// </remarks>
    public double FarPlane;

    /// <summary>
    /// Camera visibility layer mask.
    /// </summary>
    /// <remarks>
    /// Native: <c>cullMask</c>
    /// </remarks>
    public Layer CullMask;

    /// <summary>
    /// Camera projection mode.
    /// </summary>
    /// <remarks>
    /// Native: <c>projection</c>
    /// </remarks>
    public Projection Projection;

}
