// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

using System;
using System.Numerics;
using System.Runtime.InteropServices;
using Raylib_cs;

namespace R3D_cs;

/// <summary>
/// Capsule shape defined by two endpoints and radius
/// </summary>
/// <remarks>
/// Native: <c>R3D_Capsule</c>
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public struct Capsule
{
    /// <summary>
    /// Start point of capsule axis
    /// </summary>
    /// <remarks>
    /// Native: <c>start</c>
    /// </remarks>
    public Vector3 Start;

    /// <summary>
    /// End point of capsule axis
    /// </summary>
    /// <remarks>
    /// Native: <c>end</c>
    /// </remarks>
    public Vector3 End;

    /// <summary>
    /// Capsule radius
    /// </summary>
    /// <remarks>
    /// Native: <c>radius</c>
    /// </remarks>
    public float Radius;

}
