// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

using System;
using System.Numerics;
using System.Runtime.InteropServices;
using Raylib_cs;

namespace R3D_cs;

/// <summary>
/// Parameters for procedural sky generation.
/// <para>
/// Curves control gradient falloff (lower = sharper transition at horizon).
/// </para>
/// </summary>
/// <remarks>
/// Native: <c>R3D_CubemapSky</c>
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public struct CubemapSky
{
    /// <summary>
    /// Sky color at zenith
    /// </summary>
    /// <remarks>
    /// Native: <c>skyTopColor</c>
    /// </remarks>
    public Color SkyTopColor;

    /// <summary>
    /// Sky color at horizon
    /// </summary>
    /// <remarks>
    /// Native: <c>skyHorizonColor</c>
    /// </remarks>
    public Color SkyHorizonColor;

    /// <summary>
    /// Gradient curve exponent (0.01 - 1.0, typical: 0.15)
    /// </summary>
    /// <remarks>
    /// Native: <c>skyHorizonCurve</c>
    /// </remarks>
    public float SkyHorizonCurve;

    /// <summary>
    /// Sky brightness multiplier
    /// </summary>
    /// <remarks>
    /// Native: <c>skyEnergy</c>
    /// </remarks>
    public float SkyEnergy;

    /// <summary>
    /// Ground color at nadir
    /// </summary>
    /// <remarks>
    /// Native: <c>groundBottomColor</c>
    /// </remarks>
    public Color GroundBottomColor;

    /// <summary>
    /// Ground color at horizon
    /// </summary>
    /// <remarks>
    /// Native: <c>groundHorizonColor</c>
    /// </remarks>
    public Color GroundHorizonColor;

    /// <summary>
    /// Gradient curve exponent (typical: 0.02)
    /// </summary>
    /// <remarks>
    /// Native: <c>groundHorizonCurve</c>
    /// </remarks>
    public float GroundHorizonCurve;

    /// <summary>
    /// Ground brightness multiplier
    /// </summary>
    /// <remarks>
    /// Native: <c>groundEnergy</c>
    /// </remarks>
    public float GroundEnergy;

    /// <summary>
    /// Direction from which light comes (can take not normalized)
    /// </summary>
    /// <remarks>
    /// Native: <c>sunDirection</c>
    /// </remarks>
    public Vector3 SunDirection;

    /// <summary>
    /// Sun disk color
    /// </summary>
    /// <remarks>
    /// Native: <c>sunColor</c>
    /// </remarks>
    public Color SunColor;

    /// <summary>
    /// Sun angular size in radians (real sun: ~0.0087 rad = 0.5°)
    /// </summary>
    /// <remarks>
    /// Native: <c>sunSize</c>
    /// </remarks>
    public float SunSize;

    /// <summary>
    /// Sun edge softness exponent (typical: 0.15)
    /// </summary>
    /// <remarks>
    /// Native: <c>sunCurve</c>
    /// </remarks>
    public float SunCurve;

    /// <summary>
    /// Sun brightness multiplier
    /// </summary>
    /// <remarks>
    /// Native: <c>sunEnergy</c>
    /// </remarks>
    public float SunEnergy;

}
