// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

using System;
using System.Numerics;
using System.Runtime.InteropServices;
using Raylib_cs;

namespace R3D_cs;

/// <summary>
/// GPU cubemap texture.
/// <para>
/// Holds the OpenGL texture handle and its base resolution (per face).
/// </para>
/// </summary>
/// <remarks>
/// Native: <c>R3D_Cubemap</c>
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public struct Cubemap
{
    /// <remarks>Native: <c>texture</c></remarks>
    public uint Texture;

    /// <remarks>Native: <c>fbo</c></remarks>
    public uint Fbo;

    /// <remarks>Native: <c>size</c></remarks>
    public int Size;

}
