// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

using System;
using System.Numerics;
using System.Runtime.InteropServices;
using Raylib_cs;

namespace R3D_cs;

/// <summary>
/// Parameters for procedural sky generation.
/// <para>
/// Curves control gradient falloff (lower = sharper transition at horizon).
/// </para>
/// </summary>
/// <seealso>R3D_CubemapSky</seealso>
[StructLayout(LayoutKind.Sequential)]
public struct CubemapSky
{
    /// <summary>
    /// Sky color at zenith
    /// </summary>
    /// <seealso>skyTopColor</seealso>
    public Color SkyTopColor;

    /// <summary>
    /// Sky color at horizon
    /// </summary>
    /// <seealso>skyHorizonColor</seealso>
    public Color SkyHorizonColor;

    /// <summary>
    /// Gradient curve exponent (0.01 - 1.0, typical: 0.15)
    /// </summary>
    /// <seealso>skyHorizonCurve</seealso>
    public float SkyHorizonCurve;

    /// <summary>
    /// Sky brightness multiplier
    /// </summary>
    /// <seealso>skyEnergy</seealso>
    public float SkyEnergy;

    /// <summary>
    /// Ground color at nadir
    /// </summary>
    /// <seealso>groundBottomColor</seealso>
    public Color GroundBottomColor;

    /// <summary>
    /// Ground color at horizon
    /// </summary>
    /// <seealso>groundHorizonColor</seealso>
    public Color GroundHorizonColor;

    /// <summary>
    /// Gradient curve exponent (typical: 0.02)
    /// </summary>
    /// <seealso>groundHorizonCurve</seealso>
    public float GroundHorizonCurve;

    /// <summary>
    /// Ground brightness multiplier
    /// </summary>
    /// <seealso>groundEnergy</seealso>
    public float GroundEnergy;

    /// <summary>
    /// Direction from which light comes (can take not normalized)
    /// </summary>
    /// <seealso>sunDirection</seealso>
    public Vector3 SunDirection;

    /// <summary>
    /// Sun disk color
    /// </summary>
    /// <seealso>sunColor</seealso>
    public Color SunColor;

    /// <summary>
    /// Sun angular size in radians (real sun: ~0.0087 rad = 0.5°)
    /// </summary>
    /// <seealso>sunSize</seealso>
    public float SunSize;

    /// <summary>
    /// Sun edge softness exponent (typical: 0.15)
    /// </summary>
    /// <seealso>sunCurve</seealso>
    public float SunCurve;

    /// <summary>
    /// Sun brightness multiplier
    /// </summary>
    /// <seealso>sunEnergy</seealso>
    public float SunEnergy;

}
