// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

using System;
using System.Numerics;
using System.Runtime.InteropServices;
using Raylib_cs;

namespace R3D_cs;

/// <summary>
/// Represents a decal and its properties.
/// <para>
/// This structure defines a decal that can be projected onto geometry that has already been rendered.
/// </para>
/// </summary>
/// <remarks>
/// Decals are drawn using deferred screen space rendering and do not interact with any forward rendered or non-opaque objects.
/// Native: <c>R3D_Decal</c>
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public struct Decal
{
    /// <summary>
    /// Albedo map (if the texture is undefined, implicitly treat `applyColor` as false, with alpha = 1.0)
    /// </summary>
    /// <remarks>
    /// Native: <c>albedo</c>
    /// </remarks>
    public AlbedoMap Albedo;

    /// <summary>
    /// Emission map
    /// </summary>
    /// <remarks>
    /// Native: <c>emission</c>
    /// </remarks>
    public EmissionMap Emission;

    /// <summary>
    /// Normal map
    /// </summary>
    /// <remarks>
    /// Native: <c>normal</c>
    /// </remarks>
    public NormalMap Normal;

    /// <summary>
    /// Occlusion-Roughness-Metalness map
    /// </summary>
    /// <remarks>
    /// Native: <c>orm</c>
    /// </remarks>
    public OrmMap Orm;

    /// <summary>
    /// UV offset (default: {0.0f, 0.0f})
    /// </summary>
    /// <remarks>
    /// Native: <c>uvOffset</c>
    /// </remarks>
    public Vector2 UvOffset;

    /// <summary>
    /// UV scale (default: {1.0f, 1.0f})
    /// </summary>
    /// <remarks>
    /// Native: <c>uvScale</c>
    /// </remarks>
    public Vector2 UvScale;

    /// <summary>
    /// Alpha cutoff threshold (default: 0.01f)
    /// </summary>
    /// <remarks>
    /// Native: <c>alphaCutoff</c>
    /// </remarks>
    public float AlphaCutoff;

    /// <summary>
    /// Maximum angle against the surface normal to draw decal. 0.0f disables threshold. (default: 0.0f)
    /// </summary>
    /// <remarks>
    /// Native: <c>normalThreshold</c>
    /// </remarks>
    public float NormalThreshold;

    /// <summary>
    /// The width of fading along the normal threshold (default: 0.0f)
    /// </summary>
    /// <remarks>
    /// Native: <c>fadeWidth</c>
    /// </remarks>
    public float FadeWidth;

    /// <summary>
    /// Indicates that the albedo color will not be rendered, only the alpha component of the albedo will be used as a mask. (default: true)
    /// </summary>
    /// <remarks>
    /// Native: <c>applyColor</c>
    /// </remarks>
    public bool ApplyColor;

    /// <summary>
    /// Custom shader applied to the decal (default: NULL)
    /// </summary>
    /// <remarks>
    /// Native: <c>shader</c>
    /// </remarks>
    public SurfaceShader Shader;

}
