// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

using System;
using System.Numerics;
using System.Runtime.InteropServices;
using Raylib_cs;

namespace R3D_cs;

/// <summary>
/// Ambient lighting configuration.
/// </summary>
/// <remarks>
/// Native: <c>R3D_EnvAmbient</c>
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public struct EnvAmbient
{
    /// <summary>
    /// Ambient light color when there is no ambient map
    /// </summary>
    /// <remarks>
    /// Native: <c>color</c>
    /// </remarks>
    public Color Color;

    /// <summary>
    /// Energy multiplier for ambient light (map or color)
    /// </summary>
    /// <remarks>
    /// Native: <c>energy</c>
    /// </remarks>
    public float Energy;

    /// <summary>
    /// IBL environment map, can be generated from skybox
    /// </summary>
    /// <remarks>
    /// Native: <c>map</c>
    /// </remarks>
    public AmbientMap Map;

}
