// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

using System;
using System.Numerics;
using System.Runtime.InteropServices;
using System.Text;
using Raylib_cs;

namespace R3D_cs;

/// <summary>
/// Auto exposure post-processing settings.
/// <para>
/// Automatically adjusts scene exposure from average luminance, simulating eye adaptation. Adaptation should physically be faster toward bright scenes than toward dark scenes, as dark adaptation is slower.
/// </para>
/// </summary>
/// <remarks>
/// <b>Warning:</b>
/// Current implementation keeps a single temporal history. Enabling auto exposure for multiple scene passes in the same frame, or across different scenes, may produce incorrect adaptation. For now, use it only on one continuous begin/end scene render path.
/// Native: <c>R3D_EnvAutoExposure</c>
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public struct EnvAutoExposure
{
    /// <summary>
    /// Minimum measured luminance in EV stops, relative to middle gray (default: -1.0)
    /// </summary>
    /// <remarks>
    /// Native: <c>minEV</c>
    /// </remarks>
    public float MinEV;

    /// <summary>
    /// Maximum measured luminance in EV stops, relative to middle gray (default:  1.0)
    /// </summary>
    /// <remarks>
    /// Native: <c>maxEV</c>
    /// </remarks>
    public float MaxEV;

    /// <summary>
    /// Artistic exposure bias in EV stops: +1 = one stop brighter (default: 0.0)
    /// </summary>
    /// <remarks>
    /// Native: <c>exposureCompensation</c>
    /// </remarks>
    public float ExposureCompensation;

    /// <summary>
    /// Time constant in seconds when scene luminance increases; lower = faster (default: 0.5)
    /// </summary>
    /// <remarks>
    /// Native: <c>adaptationToBright</c>
    /// </remarks>
    public float AdaptationToBright;

    /// <summary>
    /// Time constant in seconds when scene luminance decreases; lower = faster (default: 1.0)
    /// </summary>
    /// <remarks>
    /// Native: <c>adaptationToDark</c>
    /// </remarks>
    public float AdaptationToDark;

    /// <summary>
    /// Enable auto exposure (default: false)
    /// </summary>
    /// <remarks>
    /// Native: <c>enabled</c>
    /// </remarks>
    public bool Enabled;

}
