// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

using System;
using System.Numerics;
using System.Runtime.InteropServices;
using Raylib_cs;

namespace R3D_cs;

/// <summary>
/// Ambient lighting configuration.
/// </summary>
/// <seealso>R3D_EnvAmbient</seealso>
[StructLayout(LayoutKind.Sequential)]
public struct EnvAmbient
{
    /// <summary>
    /// Ambient light color when there is no ambient map
    /// </summary>
    /// <seealso>color</seealso>
    public Color Color;

    /// <summary>
    /// Energy multiplier for ambient light (map or color)
    /// </summary>
    /// <seealso>energy</seealso>
    public float Energy;

    /// <summary>
    /// IBL environment map, can be generated from skybox
    /// </summary>
    /// <seealso>map</seealso>
    public AmbientMap Map;

}
