// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

using System;
using System.Numerics;
using System.Runtime.InteropServices;
using Raylib_cs;

namespace R3D_cs;

/// <summary>
/// Bloom post-processing settings.
/// <para>
/// Glow effect around bright areas in the scene.
/// </para>
/// </summary>
/// <remarks>
/// Native: <c>R3D_EnvBloom</c>
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public struct EnvBloom
{
    /// <summary>
    /// Bloom blending mode (default: R3D_BLOOM_DISABLED)
    /// </summary>
    /// <remarks>
    /// Native: <c>mode</c>
    /// </remarks>
    public Bloom Mode;

    /// <summary>
    /// Mipmap spread factor [0-1]: higher = wider glow (default: 0.5)
    /// </summary>
    /// <remarks>
    /// Native: <c>levels</c>
    /// </remarks>
    public float Levels;

    /// <summary>
    /// Bloom strength multiplier (default: 0.05)
    /// </summary>
    /// <remarks>
    /// Native: <c>intensity</c>
    /// </remarks>
    public float Intensity;

    /// <summary>
    /// Minimum brightness to trigger bloom (default: 0.0)
    /// </summary>
    /// <remarks>
    /// Native: <c>threshold</c>
    /// </remarks>
    public float Threshold;

    /// <summary>
    /// Softness of brightness cutoff transition (default: 0.5)
    /// </summary>
    /// <remarks>
    /// Native: <c>softThreshold</c>
    /// </remarks>
    public float SoftThreshold;

    /// <summary>
    /// Blur filter radius during upscaling (default: 1.0)
    /// </summary>
    /// <remarks>
    /// Native: <c>filterRadius</c>
    /// </remarks>
    public float FilterRadius;

}
