// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

using System;
using System.Numerics;
using System.Runtime.InteropServices;
using Raylib_cs;

namespace R3D_cs;

/// <summary>
/// Bloom post-processing settings.
/// <para>
/// Glow effect around bright areas in the scene.
/// </para>
/// </summary>
/// <seealso>R3D_EnvBloom</seealso>
[StructLayout(LayoutKind.Sequential)]
public struct EnvBloom
{
    /// <summary>
    /// Bloom blending mode (default: R3D_BLOOM_DISABLED)
    /// </summary>
    /// <seealso>mode</seealso>
    public Bloom Mode;

    /// <summary>
    /// Mipmap spread factor [0-1]: higher = wider glow (default: 0.5)
    /// </summary>
    /// <seealso>levels</seealso>
    public float Levels;

    /// <summary>
    /// Bloom strength multiplier (default: 0.05)
    /// </summary>
    /// <seealso>intensity</seealso>
    public float Intensity;

    /// <summary>
    /// Minimum brightness to trigger bloom (default: 0.0)
    /// </summary>
    /// <seealso>threshold</seealso>
    public float Threshold;

    /// <summary>
    /// Softness of brightness cutoff transition (default: 0.5)
    /// </summary>
    /// <seealso>softThreshold</seealso>
    public float SoftThreshold;

    /// <summary>
    /// Blur filter radius during upscaling (default: 1.0)
    /// </summary>
    /// <seealso>filterRadius</seealso>
    public float FilterRadius;

}
