// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

using System;
using System.Numerics;
using System.Runtime.InteropServices;
using Raylib_cs;

namespace R3D_cs;

/// <summary>
/// Background and skybox configuration.
/// </summary>
/// <remarks>
/// Native: <c>R3D_EnvBackground</c>
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public struct EnvBackground
{
    /// <summary>
    /// Background color when there is no skybox
    /// </summary>
    /// <remarks>
    /// Native: <c>color</c>
    /// </remarks>
    public Color Color;

    /// <summary>
    /// Energy multiplier applied to background (skybox or color)
    /// </summary>
    /// <remarks>
    /// Native: <c>energy</c>
    /// </remarks>
    public float Energy;

    /// <summary>
    /// Sky blur factor [0,1], based on mipmaps, very fast
    /// </summary>
    /// <remarks>
    /// Native: <c>skyBlur</c>
    /// </remarks>
    public float SkyBlur;

    /// <summary>
    /// Skybox asset (used if ID is non-zero)
    /// </summary>
    /// <remarks>
    /// Native: <c>sky</c>
    /// </remarks>
    public Cubemap Sky;

    /// <summary>
    /// Skybox rotation (pitch, yaw, roll as quaternion)
    /// </summary>
    /// <remarks>
    /// Native: <c>rotation</c>
    /// </remarks>
    public Quaternion Rotation;

}
