// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

using System;
using System.Numerics;
using System.Runtime.InteropServices;
using Raylib_cs;

namespace R3D_cs;

/// <summary>
/// Color grading adjustments.
/// <para>
/// Final color correction applied after all other effects.
/// </para>
/// </summary>
/// <seealso>R3D_EnvColor</seealso>
[StructLayout(LayoutKind.Sequential)]
public struct EnvColor
{
    /// <summary>
    /// Overall brightness multiplier (default: 1.0)
    /// </summary>
    /// <seealso>brightness</seealso>
    public float Brightness;

    /// <summary>
    /// Contrast between dark and bright areas (default: 1.0)
    /// </summary>
    /// <seealso>contrast</seealso>
    public float Contrast;

    /// <summary>
    /// Color intensity (default: 1.0)
    /// </summary>
    /// <seealso>saturation</seealso>
    public float Saturation;

}
