// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

using System;
using System.Numerics;
using System.Runtime.InteropServices;
using Raylib_cs;

namespace R3D_cs;

/// <summary>
/// Fog atmospheric effect settings.
/// </summary>
/// <remarks>
/// Native: <c>R3D_EnvFog</c>
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public struct EnvFog
{
    /// <summary>
    /// Fog distribution mode (default: R3D_FOG_DISABLED)
    /// </summary>
    /// <remarks>
    /// Native: <c>mode</c>
    /// </remarks>
    public Fog Mode;

    /// <summary>
    /// Fog tint color (default: white)
    /// </summary>
    /// <remarks>
    /// Native: <c>color</c>
    /// </remarks>
    public Color Color;

    /// <summary>
    /// Linear mode: distance where fog begins (default: 1.0)
    /// </summary>
    /// <remarks>
    /// Native: <c>start</c>
    /// </remarks>
    public float Start;

    /// <summary>
    /// Linear mode: distance of full fog density (default: 50.0)
    /// </summary>
    /// <remarks>
    /// Native: <c>end</c>
    /// </remarks>
    public float End;

    /// <summary>
    /// Exponential modes: fog thickness factor (default: 0.05)
    /// </summary>
    /// <remarks>
    /// Native: <c>density</c>
    /// </remarks>
    public float Density;

    /// <summary>
    /// Fog influence on skybox [0-1] (default: 0.5)
    /// </summary>
    /// <remarks>
    /// Native: <c>skyAffect</c>
    /// </remarks>
    public float SkyAffect;

}
