// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

using System;
using System.Numerics;
using System.Runtime.InteropServices;
using Raylib_cs;

namespace R3D_cs;

/// <summary>
/// Screen Space Reflections (SSR) settings.
/// <para>
/// Real-time reflections calculated in screen space.
/// </para>
/// </summary>
/// <seealso>R3D_EnvSSR</seealso>
[StructLayout(LayoutKind.Sequential)]
public struct EnvSSR
{
    /// <summary>
    /// Maximum ray marching steps (default: 32)
    /// </summary>
    /// <seealso>maxRaySteps</seealso>
    public int MaxRaySteps;

    /// <summary>
    /// Binary search refinement steps (default: 4)
    /// </summary>
    /// <seealso>binarySteps</seealso>
    public int BinarySteps;

    /// <summary>
    /// Ray step size (default: 0.125)
    /// </summary>
    /// <seealso>stepSize</seealso>
    public float StepSize;

    /// <summary>
    /// Depth tolerance for valid hits (default: 0.2)
    /// </summary>
    /// <seealso>thickness</seealso>
    public float Thickness;

    /// <summary>
    /// Maximum ray distance (default: 4.0)
    /// </summary>
    /// <seealso>maxDistance</seealso>
    public float MaxDistance;

    /// <summary>
    /// Screen edge fade start [0,1] (default: 0.25)
    /// </summary>
    /// <seealso>edgeFade</seealso>
    public float EdgeFade;

    /// <summary>
    /// Enable/disable SSR (default: false)
    /// </summary>
    /// <seealso>enabled</seealso>
    public bool Enabled;

}
