// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

using System;
using System.Numerics;
using System.Runtime.InteropServices;
using System.Text;
using Raylib_cs;

namespace R3D_cs;

/// <summary>
/// Screen Space Indirect Lighting (SSIL) settings.
/// <para>
/// Extends the SSAO algorithm with a global illumination component: occluding surfaces not only darken the fragment (ambient occlusion) but also transfer their color to it (indirect light bounce). A larger radius than SSAO is generally preferable to capture meaningful indirect lighting contributions.
/// </para>
/// </summary>
/// <remarks>
/// Native: <c>R3D_EnvSSIL</c>
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public struct EnvSSIL
{
    /// <summary>
    /// Number of samples to compute SSIL (default: 16)
    /// </summary>
    /// <remarks>
    /// Native: <c>sampleCount</c>
    /// </remarks>
    public int SampleCount;

    /// <summary>
    /// Indirect light strength multiplier (default: 1.0)
    /// </summary>
    /// <remarks>
    /// Native: <c>giIntensity</c>
    /// </remarks>
    public float GiIntensity;

    /// <summary>
    /// Ambient occlusion strength multiplier (default: 1.0)
    /// </summary>
    /// <remarks>
    /// Native: <c>aoIntensity</c>
    /// </remarks>
    public float AoIntensity;

    /// <summary>
    /// Exponential falloff for sharper occlusion darkening (default: 1.0)
    /// </summary>
    /// <remarks>
    /// Native: <c>aoPower</c>
    /// </remarks>
    public float AoPower;

    /// <summary>
    /// Fraction of screen height beyond which the sampling radius is clamped (default: 0.2)
    /// </summary>
    /// <remarks>
    /// Native: <c>maxRadius</c>
    /// </remarks>
    public float MaxRadius;

    /// <summary>
    /// Sampling radius in world space (default: 4.0)
    /// </summary>
    /// <remarks>
    /// Native: <c>radius</c>
    /// </remarks>
    public float Radius;

    /// <summary>
    /// Depth bias to prevent self-occlusion artifacts, in world-space units (default: 0.03)
    /// </summary>
    /// <remarks>
    /// Native: <c>bias</c>
    /// </remarks>
    public float Bias;

    /// <summary>
    /// Enable/disable SSIL effect (default: false)
    /// </summary>
    /// <remarks>
    /// Native: <c>enabled</c>
    /// </remarks>
    public bool Enabled;

}
