// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

using System;
using System.Numerics;
using System.Runtime.InteropServices;
using Raylib_cs;

namespace R3D_cs;

/// <summary>
/// Screen Space Indirect Lighting (SSIL) settings.
/// <para>
/// Approximates indirect lighting by gathering light from nearby surfaces in screen space.
/// </para>
/// </summary>
/// <seealso>R3D_EnvSSIL</seealso>
[StructLayout(LayoutKind.Sequential)]
public struct EnvSSIL
{
    /// <summary>
    /// Number of samples to compute indirect lighting (default: 4)
    /// </summary>
    /// <seealso>sampleCount</seealso>
    public int SampleCount;

    /// <summary>
    /// Number of depth slices for accumulation (default: 4)
    /// </summary>
    /// <seealso>sliceCount</seealso>
    public int SliceCount;

    /// <summary>
    /// Maximum distance to gather light from (default: 5.0)
    /// </summary>
    /// <seealso>sampleRadius</seealso>
    public float SampleRadius;

    /// <summary>
    /// Thickness threshold for occluders (default: 0.5)
    /// </summary>
    /// <seealso>hitThickness</seealso>
    public float HitThickness;

    /// <summary>
    /// Exponential falloff for visibility factor (too high = more noise) (default: 1.0)
    /// </summary>
    /// <seealso>aoPower</seealso>
    public float AoPower;

    /// <summary>
    /// Multiplier for indirect light intensity (default: 1.0)
    /// </summary>
    /// <seealso>energy</seealso>
    public float Energy;

    /// <summary>
    /// Bounce feeback factor. (default: 0.5) Simulates light bounces by re-injecting the SSIL from the previous frame into the current direct light. Be careful not to make the factor too high in order to avoid a feedback loop.
    /// </summary>
    /// <seealso>bounce</seealso>
    public float Bounce;

    /// <summary>
    /// Temporal convergence factor (0 disables it, default 0.5). Smooths sudden light flashes by blending with previous frames. Higher values produce smoother results but may cause ghosting. Tip: The faster the screen changes, the higher the convergence can be acceptable. Requires an additional history buffer (so require more memory). If multiple SSIL passes are done in the same frame, the history may be inconsistent, in that case, enable SSIL/convergence for only one pass per frame.
    /// </summary>
    /// <seealso>convergence</seealso>
    public float Convergence;

    /// <summary>
    /// Enable/disable SSIL effect (default: false)
    /// </summary>
    /// <seealso>enabled</seealso>
    public bool Enabled;

}
