// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

using System;
using System.Numerics;
using System.Runtime.InteropServices;
using System.Text;
using Raylib_cs;

namespace R3D_cs;

/// <summary>
/// Screen Space Global Illumination (SSGI) settings.
/// <para>
/// Computes indirect lighting from the scene's visible surfaces in real time.
/// </para>
/// </summary>
/// <remarks>
/// Native: <c>R3D_EnvSSGI</c>
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public struct EnvSSGI
{
    /// <summary>
    /// Number of directions sampled per pixel. Higher = fewer noise streaks, higher cost. (default: 4)
    /// </summary>
    /// <remarks>
    /// Native: <c>sliceCount</c>
    /// </remarks>
    public int SliceCount;

    /// <summary>
    /// Fades out GI near screen edges to hide emissive objects partially off-screen. (default: 0.1)
    /// </summary>
    /// <remarks>
    /// Native: <c>edgeFade</c>
    /// </remarks>
    public float EdgeFade;

    /// <summary>
    /// How quickly indirect light fades with distance. Higher = shorter reach, darker result. (default: 1.0)
    /// </summary>
    /// <remarks>
    /// Native: <c>distanceFalloff</c>
    /// </remarks>
    public float DistanceFalloff;

    /// <summary>
    /// Prevents surfaces from receiving light through their own backside. 0 = off, 1 = physically correct. May look inconsistent with non-directional emissives. (default: 0.0)
    /// </summary>
    /// <remarks>
    /// Native: <c>normalRejection</c>
    /// </remarks>
    public float NormalRejection;

    /// <summary>
    /// Brightness of the indirect lighting. Dimly lit scenes may require significantly higher values to show probable contribution. (default: 1.0)
    /// </summary>
    /// <remarks>
    /// Native: <c>intensity</c>
    /// </remarks>
    public float Intensity;

    /// <summary>
    /// Number of denoiser passes. Higher = smoother result, slightly higher cost. (default: 4)
    /// </summary>
    /// <remarks>
    /// Native: <c>denoiseSteps</c>
    /// </remarks>
    public int DenoiseSteps;

    /// <summary>
    /// Enable or disable SSGI entirely. (default: false)
    /// </summary>
    /// <remarks>
    /// Native: <c>enabled</c>
    /// </remarks>
    public bool Enabled;

}
