// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

using System;
using System.Numerics;
using System.Runtime.InteropServices;
using Raylib_cs;

namespace R3D_cs;

/// <summary>
/// Screen Space Ambient Occlusion (SSAO) settings.
/// <para>
/// Darkens areas where surfaces are close together, such as corners and crevices.
/// </para>
/// </summary>
/// <seealso>R3D_EnvSSAO</seealso>
[StructLayout(LayoutKind.Sequential)]
public struct EnvSSAO
{
    /// <summary>
    /// Number of samples to compute SSAO (default: 16)
    /// </summary>
    /// <seealso>sampleCount</seealso>
    public int SampleCount;

    /// <summary>
    /// Base occlusion strength multiplier (default: 1.0)
    /// </summary>
    /// <seealso>intensity</seealso>
    public float Intensity;

    /// <summary>
    /// Exponential falloff for sharper darkening (default: 1.5)
    /// </summary>
    /// <seealso>power</seealso>
    public float Power;

    /// <summary>
    /// Sampling radius in world space (default: 0.25)
    /// </summary>
    /// <seealso>radius</seealso>
    public float Radius;

    /// <summary>
    /// Depth bias to prevent self-shadowing, good value is ~2% of the radius (default: 0.007)
    /// </summary>
    /// <seealso>bias</seealso>
    public float Bias;

    /// <summary>
    /// Enable/disable SSAO effect (default: false)
    /// </summary>
    /// <seealso>enabled</seealso>
    public bool Enabled;

}
