// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

using System;
using System.Numerics;
using System.Runtime.InteropServices;
using Raylib_cs;

namespace R3D_cs;

/// <summary>
/// Screen Space Reflections (SSR) settings.
/// <para>
/// Real-time reflections calculated in screen space.
/// </para>
/// </summary>
/// <seealso>R3D_EnvSSR</seealso>
[StructLayout(LayoutKind.Sequential)]
public struct EnvSSR
{
    /// <summary>
    /// Maximum ray marching iterations (default: 64)
    /// </summary>
    /// <seealso>maxRaySteps</seealso>
    public int MaxRaySteps;

    /// <summary>
    /// Refinement steps for intersection (default: 8)
    /// </summary>
    /// <seealso>binarySearchSteps</seealso>
    public int BinarySearchSteps;

    /// <summary>
    /// Maximum ray distance in view space (default: 8.0)
    /// </summary>
    /// <seealso>rayMarchLength</seealso>
    public float RayMarchLength;

    /// <summary>
    /// Depth tolerance for valid hits (default: 0.2)
    /// </summary>
    /// <seealso>depthThickness</seealso>
    public float DepthThickness;

    /// <summary>
    /// Negative margin to prevent false negatives (default: 0.005)
    /// </summary>
    /// <seealso>depthTolerance</seealso>
    public float DepthTolerance;

    /// <summary>
    /// Screen edge fade start [0-1] (default: 0.7)
    /// </summary>
    /// <seealso>edgeFadeStart</seealso>
    public float EdgeFadeStart;

    /// <summary>
    /// Screen edge fade end [0-1] (default: 1.0)
    /// </summary>
    /// <seealso>edgeFadeEnd</seealso>
    public float EdgeFadeEnd;

    /// <summary>
    /// Enable/disable SSR (default: false)
    /// </summary>
    /// <seealso>enabled</seealso>
    public bool Enabled;

}
