// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

using System;
using System.Numerics;
using System.Runtime.InteropServices;
using Raylib_cs;

namespace R3D_cs;

/// <summary>
/// Screen Space Ambient Occlusion (SSAO) settings.
/// <para>
/// Darkens areas where surfaces are close together, such as corners and crevices.
/// </para>
/// </summary>
/// <remarks>
/// Native: <c>R3D_EnvSSAO</c>
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public struct EnvSSAO
{
    /// <summary>
    /// Number of samples to compute SSAO (default: 16)
    /// </summary>
    /// <remarks>
    /// Native: <c>sampleCount</c>
    /// </remarks>
    public int SampleCount;

    /// <summary>
    /// Base occlusion strength multiplier (default: 1.0)
    /// </summary>
    /// <remarks>
    /// Native: <c>intensity</c>
    /// </remarks>
    public float Intensity;

    /// <summary>
    /// Exponential falloff for sharper darkening (default: 1.5)
    /// </summary>
    /// <remarks>
    /// Native: <c>power</c>
    /// </remarks>
    public float Power;

    /// <summary>
    /// Sampling radius in world space (default: 0.25)
    /// </summary>
    /// <remarks>
    /// Native: <c>radius</c>
    /// </remarks>
    public float Radius;

    /// <summary>
    /// Depth bias to prevent self-shadowing, good value is ~2% of the radius (default: 0.007)
    /// </summary>
    /// <remarks>
    /// Native: <c>bias</c>
    /// </remarks>
    public float Bias;

    /// <summary>
    /// Enable/disable SSAO effect (default: false)
    /// </summary>
    /// <remarks>
    /// Native: <c>enabled</c>
    /// </remarks>
    public bool Enabled;

}
