// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

using System;
using System.Numerics;
using System.Runtime.InteropServices;
using System.Text;
using Raylib_cs;

namespace R3D_cs;

/// <summary>
/// Screen Space Global Illumination (SSGI) settings.
/// <para>
/// Real-time global illlumination calculated in screen space.
/// </para>
/// </summary>
/// <remarks>
/// Best suited for enclosed/indoor environments.
/// Native: <c>R3D_EnvSSGI</c>
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public struct EnvSSGI
{
    /// <summary>
    /// Number of rays per pixel (default: 2)
    /// </summary>
    /// <remarks>
    /// Native: <c>sampleCount</c>
    /// </remarks>
    public int SampleCount;

    /// <summary>
    /// Maximum ray marching steps (default: 32)
    /// </summary>
    /// <remarks>
    /// Native: <c>maxRaySteps</c>
    /// </remarks>
    public int MaxRaySteps;

    /// <summary>
    /// Ray step size (default: 0.125)
    /// </summary>
    /// <remarks>
    /// Native: <c>stepSize</c>
    /// </remarks>
    public float StepSize;

    /// <summary>
    /// Depth tolerance for valid hits (default: 1.0)
    /// </summary>
    /// <remarks>
    /// Native: <c>thickness</c>
    /// </remarks>
    public float Thickness;

    /// <summary>
    /// Maximum ray distance (default: 4.0)
    /// </summary>
    /// <remarks>
    /// Native: <c>maxDistance</c>
    /// </remarks>
    public float MaxDistance;

    /// <summary>
    /// GI intensity multiplier (default: 3.0)
    /// </summary>
    /// <remarks>
    /// Native: <c>intensity</c>
    /// </remarks>
    public float Intensity;

    /// <summary>
    /// Distance at which the GI fade begins (default: 8.0)
    /// </summary>
    /// <remarks>
    /// Native: <c>fadeStart</c>
    /// </remarks>
    public float FadeStart;

    /// <summary>
    /// Distance at which GI is fully faded (default: 16.0)
    /// </summary>
    /// <remarks>
    /// Native: <c>fadeEnd</c>
    /// </remarks>
    public float FadeEnd;

    /// <summary>
    /// Number of denoiser iterations (default: 5)
    /// </summary>
    /// <remarks>
    /// Native: <c>denoiseSteps</c>
    /// </remarks>
    public int DenoiseSteps;

    /// <summary>
    /// Enable/disable SSGI (default: false)
    /// </summary>
    /// <remarks>
    /// Native: <c>enabled</c>
    /// </remarks>
    public bool Enabled;

}
