// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

using System;
using System.Numerics;
using System.Runtime.InteropServices;
using Raylib_cs;

namespace R3D_cs;

/// <summary>
/// Tone mapping and exposure settings.
/// <para>
/// Converts HDR colors to displayable LDR range.
/// </para>
/// </summary>
/// <remarks>
/// Native: <c>R3D_EnvTonemap</c>
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public struct EnvTonemap
{
    /// <summary>
    /// Tone mapping algorithm (default: R3D_TONEMAP_LINEAR)
    /// </summary>
    /// <remarks>
    /// Native: <c>mode</c>
    /// </remarks>
    public Tonemap Mode;

    /// <summary>
    /// Scene brightness multiplier (default: 1.0)
    /// </summary>
    /// <remarks>
    /// Native: <c>exposure</c>
    /// </remarks>
    public float Exposure;

    /// <summary>
    /// Reference white point (not used for AGX) (default: 1.0)
    /// </summary>
    /// <remarks>
    /// Native: <c>white</c>
    /// </remarks>
    public float White;

}
