// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

using System;
using System.Numerics;
using System.Runtime.InteropServices;
using Raylib_cs;

namespace R3D_cs;

/// <summary>
/// Tone mapping and exposure settings.
/// <para>
/// Converts HDR colors to displayable LDR range.
/// </para>
/// </summary>
/// <seealso>R3D_EnvTonemap</seealso>
[StructLayout(LayoutKind.Sequential)]
public struct EnvTonemap
{
    /// <summary>
    /// Tone mapping algorithm (default: R3D_TONEMAP_LINEAR)
    /// </summary>
    /// <seealso>mode</seealso>
    public Tonemap Mode;

    /// <summary>
    /// Scene brightness multiplier (default: 1.0)
    /// </summary>
    /// <seealso>exposure</seealso>
    public float Exposure;

    /// <summary>
    /// Reference white point (not used for AGX) (default: 1.0)
    /// </summary>
    /// <seealso>white</seealso>
    public float White;

}
