// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

using System;
using System.Numerics;
using System.Runtime.InteropServices;
using System.Text;
using Raylib_cs;

namespace R3D_cs;

/// <summary>
/// View frustum defined by its clipping planes.
/// <para>
/// Planes are stored as Vector4 (xyz = normal, w = distance).
/// </para>
/// </summary>
/// <remarks>
/// Native: <c>R3D_Frustum</c>
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct Frustum
{
    /// <remarks>Native: <c>planes</c></remarks>
    public FrustumPlanesBuffer Planes;

}

/// <summary>Inline fixed-size buffer of 6 <see cref="Vector4"/> elements.</summary>
[System.Runtime.CompilerServices.InlineArray(6)]
public struct FrustumPlanesBuffer
{
    private Vector4 _element0;
}
