// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

using System;
using System.Numerics;
using System.Runtime.InteropServices;
using Raylib_cs;

namespace R3D_cs;

/// <summary>
/// Opaque importer handle.
/// <para>
/// Represents a loaded asset file that can be used to extract multiple resources (models, skeletons, animations) without re-importing the file.
/// </para>
/// </summary>
/// <seealso>R3D_Importer</seealso>
[StructLayout(LayoutKind.Sequential)]
public struct Importer
{
}
