// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

using System;
using System.Numerics;
using System.Runtime.InteropServices;
using System.Text;
using Raylib_cs;

namespace R3D_cs;

/// <summary>
/// GPU buffers storing instance attribute streams.
/// <para>
/// Each enabled attribute owns one GPU buffer. The enabled attributes and their storage formats are described by `layout`.
/// </para>
/// </summary>
/// <remarks>
/// Native: <c>R3D_InstanceBuffer</c>
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct InstanceBuffer
{
    /// <summary>
    /// One GPU buffer per attribute, indexed by attribute order.
    /// </summary>
    /// <remarks>
    /// Native: <c>buffers</c>
    /// </remarks>
    public fixed uint Buffers[5];

    /// <summary>
    /// Instance buffer layout.
    /// </summary>
    /// <remarks>
    /// Native: <c>layout</c>
    /// </remarks>
    public InstanceLayout Layout;

    /// <summary>
    /// Maximum number of instances.
    /// </summary>
    /// <remarks>
    /// Native: <c>capacity</c>
    /// </remarks>
    public int Capacity;

}
