// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

using System;
using System.Numerics;
using System.Runtime.InteropServices;
using Raylib_cs;

namespace R3D_cs;

/// <summary>
/// GPU buffers storing instance attribute streams.
/// <para>
/// buffers: One VBO per attribute (indexed by flag order). capcity: Maximum number of instances. flags: Enabled attribute mask.
/// </para>
/// </summary>
/// <remarks>
/// Native: <c>R3D_InstanceBuffer</c>
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct InstanceBuffer
{
    /// <remarks>Native: <c>buffers</c></remarks>
    public fixed uint Buffers[5];

    /// <remarks>Native: <c>capacity</c></remarks>
    public int Capacity;

    /// <remarks>Native: <c>flags</c></remarks>
    public int Flags;

}
