// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

using System;
using System.Numerics;
using System.Runtime.InteropServices;
using System.Text;
using Raylib_cs;

namespace R3D_cs;

/// <summary>
/// Describes the layout of an instance buffer.
/// <para>
/// `flags` defines which instance attributes are allocated. `formats` defines the storage format used by each attribute.
/// </para>
/// <para>
/// The `formats` array is indexed in the same order as the instance attribute flags:
/// </para>
/// <para>
/// <list type="bullet">
/// <item><description>index 0: `R3D_INSTANCE_POSITION`</description></item>
/// <item><description>index 1: `R3D_INSTANCE_ROTATION`</description></item>
/// <item><description>index 2: `R3D_INSTANCE_SCALE`</description></item>
/// <item><description>index 3: `R3D_INSTANCE_COLOR`</description></item>
/// <item><description>index 4: `R3D_INSTANCE_CUSTOM`</description></item>
/// </list>
/// </para>
/// <para>
/// Data uploaded or mapped for an attribute must match the format selected for that attribute.
/// </para>
/// </summary>
/// <remarks>
/// Native: <c>R3D_InstanceLayout</c>
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct InstanceLayout
{
    /// <summary>
    /// Storage format for each instance attribute.
    /// </summary>
    /// <remarks>
    /// Native: <c>formats</c>
    /// </remarks>
    public InstanceLayoutFormatsBuffer Formats;

    /// <summary>
    /// Enabled instance attribute mask.
    /// </summary>
    /// <remarks>
    /// Native: <c>flags</c>
    /// </remarks>
    public InstanceFlags Flags;

}

/// <summary>Inline fixed-size buffer of 5 <see cref="InstanceFormat"/> elements.</summary>
[System.Runtime.CompilerServices.InlineArray(5)]
public struct InstanceLayoutFormatsBuffer
{
    private InstanceFormat _element0;
}
