// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

using System;
using System.Numerics;
using System.Runtime.InteropServices;
using Raylib_cs;

namespace R3D_cs;

/// <summary>
/// GPU buffers storing instance attribute streams.
/// <para>
/// buffers: One VBO per attribute (indexed by flag order). capcity: Maximum number of instances. flags: Enabled attribute mask.
/// </para>
/// </summary>
/// <seealso>R3D_InstanceBuffer</seealso>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct InstanceBuffer
{
    /// <seealso>buffers</seealso>
    public fixed uint Buffers[4];

    /// <seealso>capacity</seealso>
    public int Capacity;

    /// <seealso>flags</seealso>
    public int Flags;

}
