// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

namespace R3D_cs;

/// <summary>
/// Unique identifier for an R3D light.
/// <para>
/// ID type used to reference a light. A negative value indicates an invalid light.
/// </para>
/// </summary>
/// <remarks>
/// Native: <c>R3D_Light</c>
/// </remarks>
public struct Light
{
    internal int id;

    public static explicit operator int(Light handle) => handle.id;
    public static explicit operator Light(int id) => new() { id = id };
}
