// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

using System;
using System.Numerics;
using System.Runtime.InteropServices;
using Raylib_cs;

namespace R3D_cs;

/// <summary>
/// Material definition.
/// <para>
/// Combines multiple texture maps and rendering parameters for shading.
/// </para>
/// </summary>
/// <seealso>R3D_Material</seealso>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct Material
{
    /// <summary>
    /// Albedo map
    /// </summary>
    /// <seealso>albedo</seealso>
    public AlbedoMap Albedo;

    /// <summary>
    /// Emission map
    /// </summary>
    /// <seealso>emission</seealso>
    public EmissionMap Emission;

    /// <summary>
    /// Normal map
    /// </summary>
    /// <seealso>normal</seealso>
    public NormalMap Normal;

    /// <summary>
    /// Occlusion-Roughness-Metalness map
    /// </summary>
    /// <seealso>orm</seealso>
    public OrmMap Orm;

    /// <summary>
    /// UV offset (default: {0.0f, 0.0f})
    /// </summary>
    /// <seealso>uvOffset</seealso>
    public Vector2 UvOffset;

    /// <summary>
    /// UV scale (default: {1.0f, 1.0f})
    /// </summary>
    /// <seealso>uvScale</seealso>
    public Vector2 UvScale;

    /// <summary>
    /// Alpha cutoff threshold (default: 0.01f)
    /// </summary>
    /// <seealso>alphaCutoff</seealso>
    public float AlphaCutoff;

    /// <summary>
    /// Depth test configuration (default: standard)
    /// </summary>
    /// <seealso>depth</seealso>
    public DepthState Depth;

    /// <summary>
    /// Stencil test configuration (default: disabled)
    /// </summary>
    /// <seealso>stencil</seealso>
    public StencilState Stencil;

    /// <summary>
    /// Transparency mode (default: DISABLED)
    /// </summary>
    /// <seealso>transparencyMode</seealso>
    public TransparencyMode TransparencyMode;

    /// <summary>
    /// Billboard mode (default: DISABLED)
    /// </summary>
    /// <seealso>billboardMode</seealso>
    public BillboardMode BillboardMode;

    /// <summary>
    /// Blend mode (default: MIX)
    /// </summary>
    /// <seealso>blendMode</seealso>
    public BlendMode BlendMode;

    /// <summary>
    /// Face culling mode (default: BACK)
    /// </summary>
    /// <seealso>cullMode</seealso>
    public CullMode CullMode;

    /// <summary>
    /// If true, material does not participate in lighting (default: false)
    /// </summary>
    /// <seealso>unlit</seealso>
    public bool Unlit;

    /// <summary>
    /// Custom shader applied to the material (default: NULL)
    /// </summary>
    /// <seealso>shader</seealso>
    public SurfaceShader* Shader;

}
