// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

using System;
using System.Numerics;
using System.Runtime.InteropServices;
using Raylib_cs;

namespace R3D_cs;

/// <summary>
/// Material definition.
/// <para>
/// Combines multiple texture maps and rendering parameters for shading.
/// </para>
/// </summary>
/// <remarks>
/// Native: <c>R3D_Material</c>
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public struct Material
{
    /// <summary>
    /// Albedo map
    /// </summary>
    /// <remarks>
    /// Native: <c>albedo</c>
    /// </remarks>
    public AlbedoMap Albedo;

    /// <summary>
    /// Emission map
    /// </summary>
    /// <remarks>
    /// Native: <c>emission</c>
    /// </remarks>
    public EmissionMap Emission;

    /// <summary>
    /// Normal map
    /// </summary>
    /// <remarks>
    /// Native: <c>normal</c>
    /// </remarks>
    public NormalMap Normal;

    /// <summary>
    /// Occlusion-Roughness-Metalness map
    /// </summary>
    /// <remarks>
    /// Native: <c>orm</c>
    /// </remarks>
    public OrmMap Orm;

    /// <summary>
    /// UV offset (default: {0.0f, 0.0f})
    /// </summary>
    /// <remarks>
    /// Native: <c>uvOffset</c>
    /// </remarks>
    public Vector2 UvOffset;

    /// <summary>
    /// UV scale (default: {1.0f, 1.0f})
    /// </summary>
    /// <remarks>
    /// Native: <c>uvScale</c>
    /// </remarks>
    public Vector2 UvScale;

    /// <summary>
    /// Alpha cutoff threshold (default: 0.01f)
    /// </summary>
    /// <remarks>
    /// Native: <c>alphaCutoff</c>
    /// </remarks>
    public float AlphaCutoff;

    /// <summary>
    /// Depth test configuration (default: standard)
    /// </summary>
    /// <remarks>
    /// Native: <c>depth</c>
    /// </remarks>
    public DepthState Depth;

    /// <summary>
    /// Stencil test configuration (default: disabled)
    /// </summary>
    /// <remarks>
    /// Native: <c>stencil</c>
    /// </remarks>
    public StencilState Stencil;

    /// <summary>
    /// Transparency mode (default: DISABLED)
    /// </summary>
    /// <remarks>
    /// Native: <c>transparencyMode</c>
    /// </remarks>
    public TransparencyMode TransparencyMode;

    /// <summary>
    /// Billboard mode (default: DISABLED)
    /// </summary>
    /// <remarks>
    /// Native: <c>billboardMode</c>
    /// </remarks>
    public BillboardMode BillboardMode;

    /// <summary>
    /// Blend mode (default: MIX)
    /// </summary>
    /// <remarks>
    /// Native: <c>blendMode</c>
    /// </remarks>
    public BlendMode BlendMode;

    /// <summary>
    /// Face culling mode (default: BACK)
    /// </summary>
    /// <remarks>
    /// Native: <c>cullMode</c>
    /// </remarks>
    public CullMode CullMode;

    /// <summary>
    /// If true, material does not participate in lighting (default: false)
    /// </summary>
    /// <remarks>
    /// Native: <c>unlit</c>
    /// </remarks>
    public bool Unlit;

    /// <summary>
    /// Custom shader applied to the material (default: NULL)
    /// </summary>
    /// <remarks>
    /// Native: <c>shader</c>
    /// </remarks>
    public SurfaceShader Shader;

}
