// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

using System;
using System.Numerics;
using System.Runtime.InteropServices;
using Raylib_cs;

namespace R3D_cs;

/// <summary>
/// Represents a mesh stored in CPU memory.
/// <para>
/// R3D_MeshData is the CPU-side container of a mesh. It stores vertex and index data, and provides utility functions to generate, transform, and process geometry before uploading it to the GPU as an R3D_Mesh.
/// </para>
/// <para>
/// Think of it as a toolbox for procedural or dynamic mesh generation on the CPU.
/// </para>
/// </summary>
/// <remarks>
/// Native: <c>R3D_MeshData</c>
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct MeshData
{
    /// <summary>
    /// Pointer to vertex data in CPU memory.
    /// </summary>
    /// <remarks>
    /// Native: <c>vertices</c>
    /// </remarks>
    internal Vertex* _vertices;

    /// <summary>
    /// Pointer to index data in CPU memory.
    /// </summary>
    /// <remarks>
    /// Native: <c>indices</c>
    /// </remarks>
    internal uint* _indices;

    /// <summary>
    /// Number of vertices.
    /// </summary>
    /// <remarks>
    /// Native: <c>vertexCount</c>
    /// </remarks>
    public int VertexCount;

    /// <summary>
    /// Number of indices.
    /// </summary>
    /// <remarks>
    /// Native: <c>indexCount</c>
    /// </remarks>
    public int IndexCount;

    /// <summary>
    /// <see cref="Vertices"/> as a <see cref="Span{T}"/>.
    /// </summary>
    public Span<Vertex> Vertices => _vertices != null ? new(_vertices, VertexCount) : default;

    /// <summary>
    /// <see cref="Indices"/> as a <see cref="Span{T}"/>.
    /// </summary>
    public Span<uint> Indices => _indices != null ? new(_indices, IndexCount) : default;

}
