// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

using System;
using System.Numerics;
using System.Runtime.InteropServices;
using System.Text;
using Raylib_cs;

namespace R3D_cs;

/// <summary>
/// Fixed-length string type for mesh names.
/// <para>
/// The size can be freely adjusted before compilation.
/// </para>
/// </summary>
/// <remarks>
/// Native: <c>R3D_MeshName</c>
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct MeshName
{
    internal fixed byte _value[32];

    /// <summary>The UTF-8 string stored in this fixed-length buffer.</summary>
    public string Value
    {
        get
        {
            fixed (byte* ptr = _value)
            {
                int len = 0;
                while (len < 32 && ptr[len] != 0) len++;
                return Encoding.UTF8.GetString(ptr, len);
            }
        }
        set
        {
            byte[] utf8 = Encoding.UTF8.GetBytes(value);
            int len = Math.Min(utf8.Length, 31);
            for (int i = 0; i < len; i++) _value[i] = utf8[i];
            _value[len] = 0;
        }
    }

    /// <inheritdoc/>
    public override string ToString() => Value;

    public static implicit operator string(MeshName v) => v.Value;
}
