// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

using System;
using System.Numerics;
using System.Runtime.InteropServices;
using Raylib_cs;

namespace R3D_cs;

/// <summary>
/// Represents a 3D mesh.
/// <para>
/// Stores vertex and index data, shadow casting settings, bounding box, and layer information. Can represent a static or skinned mesh.
/// </para>
/// </summary>
/// <remarks>
/// Native: <c>R3D_Mesh</c>
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public struct Mesh
{
    /// <summary>
    /// OpenGL objects handles.
    /// </summary>
    /// <remarks>
    /// Native: <c>vao</c>
    /// </remarks>
    public uint Vao;

    /// <summary>
    /// OpenGL objects handles.
    /// </summary>
    /// <remarks>
    /// Native: <c>vbo</c>
    /// </remarks>
    public uint Vbo;

    /// <summary>
    /// OpenGL objects handles.
    /// </summary>
    /// <remarks>
    /// Native: <c>ebo</c>
    /// </remarks>
    public uint Ebo;

    /// <summary>
    /// Number of vertices and indices currently in use.
    /// </summary>
    /// <remarks>
    /// Native: <c>vertexCount</c>
    /// </remarks>
    public int VertexCount;

    /// <summary>
    /// Number of vertices and indices currently in use.
    /// </summary>
    /// <remarks>
    /// Native: <c>indexCount</c>
    /// </remarks>
    public int IndexCount;

    /// <summary>
    /// Number of vertices and indices allocated in GPU buffers.
    /// </summary>
    /// <remarks>
    /// Native: <c>allocVertexCount</c>
    /// </remarks>
    public int AllocVertexCount;

    /// <summary>
    /// Number of vertices and indices allocated in GPU buffers.
    /// </summary>
    /// <remarks>
    /// Native: <c>allocIndexCount</c>
    /// </remarks>
    public int AllocIndexCount;

    /// <summary>
    /// Shadow casting mode for the mesh.
    /// </summary>
    /// <remarks>
    /// Native: <c>shadowCastMode</c>
    /// </remarks>
    public ShadowCastMode ShadowCastMode;

    /// <summary>
    /// Type of primitive that constitutes the vertices.
    /// </summary>
    /// <remarks>
    /// Native: <c>primitiveType</c>
    /// </remarks>
    public PrimitiveType PrimitiveType;

    /// <summary>
    /// Hint about the usage of the mesh, retained in case of update if there is a reallocation.
    /// </summary>
    /// <remarks>
    /// Native: <c>usage</c>
    /// </remarks>
    public MeshUsage Usage;

    /// <summary>
    /// Bitfield indicating the rendering layer(s) of this mesh.
    /// </summary>
    /// <remarks>
    /// Native: <c>layerMask</c>
    /// </remarks>
    public Layer LayerMask;

    /// <summary>
    /// Axis-Aligned Bounding Box in local space.
    /// </summary>
    /// <remarks>
    /// Native: <c>aabb</c>
    /// </remarks>
    public BoundingBox Aabb;

}
