// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

using System;
using System.Numerics;
using System.Runtime.InteropServices;
using Raylib_cs;

namespace R3D_cs;

/// <summary>
/// Represents a complete 3D model with meshes and materials.
/// <para>
/// Contains multiple meshes and their associated materials, along with animation and bounding information.
/// </para>
/// </summary>
/// <remarks>
/// Native: <c>R3D_Model</c>
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct Model
{
    /// <summary>
    /// Array of meshes composing the model.
    /// </summary>
    /// <remarks>
    /// Native: <c>meshes</c>
    /// </remarks>
    public Mesh* Meshes;

    /// <summary>
    /// Array of meshes data in RAM (optional, can be NULL).
    /// </summary>
    /// <remarks>
    /// Native: <c>meshData</c>
    /// </remarks>
    public MeshData* MeshData;

    /// <summary>
    /// Array of materials used by the model.
    /// </summary>
    /// <remarks>
    /// Native: <c>materials</c>
    /// </remarks>
    public Material* Materials;

    /// <summary>
    /// Array of material indices, one per mesh.
    /// </summary>
    /// <remarks>
    /// Native: <c>meshMaterials</c>
    /// </remarks>
    public int* MeshMaterials;

    /// <summary>
    /// Number of meshes.
    /// </summary>
    /// <remarks>
    /// Native: <c>meshCount</c>
    /// </remarks>
    public int MeshCount;

    /// <summary>
    /// Number of materials.
    /// </summary>
    /// <remarks>
    /// Native: <c>materialCount</c>
    /// </remarks>
    public int MaterialCount;

    /// <summary>
    /// Axis-Aligned Bounding Box encompassing the whole model.
    /// </summary>
    /// <remarks>
    /// Native: <c>aabb</c>
    /// </remarks>
    public BoundingBox Aabb;

    /// <summary>
    /// Skeleton hierarchy and bind pose used for skinning (NULL if non-skinned).
    /// </summary>
    /// <remarks>
    /// Native: <c>skeleton</c>
    /// </remarks>
    public Skeleton Skeleton;

}
