// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

using System;
using System.Numerics;
using System.Runtime.InteropServices;
using Raylib_cs;

namespace R3D_cs;

/// <summary>
/// Represents a complete 3D model with meshes and materials.
/// <para>
/// Contains multiple meshes and their associated materials, along with animation and bounding information.
/// </para>
/// </summary>
/// <remarks>
/// Native: <c>R3D_Model</c>
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct Model
{
    /// <summary>
    /// Array of meshes composing the model.
    /// </summary>
    /// <remarks>
    /// Native: <c>meshes</c>
    /// </remarks>
    internal Mesh* _meshes;

    /// <summary>
    /// Array of meshes data in RAM (optional, can be NULL).
    /// </summary>
    /// <remarks>
    /// Native: <c>meshData</c>
    /// </remarks>
    internal MeshData* _meshData;

    /// <summary>
    /// Array of materials used by the model.
    /// </summary>
    /// <remarks>
    /// Native: <c>materials</c>
    /// </remarks>
    internal Material* _materials;

    /// <summary>
    /// Array of material indices, one per mesh.
    /// </summary>
    /// <remarks>
    /// Native: <c>meshMaterials</c>
    /// </remarks>
    internal int* _meshMaterials;

    /// <summary>
    /// Number of meshes.
    /// </summary>
    /// <remarks>
    /// Native: <c>meshCount</c>
    /// </remarks>
    public int MeshCount;

    /// <summary>
    /// Number of materials.
    /// </summary>
    /// <remarks>
    /// Native: <c>materialCount</c>
    /// </remarks>
    public int MaterialCount;

    /// <summary>
    /// Axis-Aligned Bounding Box encompassing the whole model.
    /// </summary>
    /// <remarks>
    /// Native: <c>aabb</c>
    /// </remarks>
    public BoundingBox Aabb;

    /// <summary>
    /// Skeleton hierarchy and bind pose used for skinning (NULL if non-skinned).
    /// </summary>
    /// <remarks>
    /// Native: <c>skeleton</c>
    /// </remarks>
    public Skeleton Skeleton;

    /// <summary>
    /// <see cref="Meshes"/> as a <see cref="Span{T}"/>.
    /// </summary>
    public Span<Mesh> Meshes => _meshes != null ? new(_meshes, MeshCount) : default;

    /// <summary>
    /// <see cref="MeshData"/> as a <see cref="Span{T}"/>.
    /// </summary>
    public Span<MeshData> MeshData => _meshData != null ? new(_meshData, MeshCount) : default;

    /// <summary>
    /// <see cref="Materials"/> as a <see cref="Span{T}"/>.
    /// </summary>
    public Span<Material> Materials => _materials != null ? new(_materials, MaterialCount) : default;

    /// <summary>
    /// <see cref="MeshMaterials"/> as a <see cref="Span{T}"/>.
    /// </summary>
    public Span<int> MeshMaterials => _meshMaterials != null ? new(_meshMaterials, MeshCount) : default;

}
