// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

using System;
using System.Numerics;
using System.Runtime.InteropServices;
using Raylib_cs;

namespace R3D_cs;

/// <summary>
/// Normal map.
/// <para>
/// Provides normal map texture and scale factor.
/// </para>
/// </summary>
/// <seealso>R3D_NormalMap</seealso>
[StructLayout(LayoutKind.Sequential)]
public struct NormalMap
{
    /// <summary>
    /// Normal map texture (default: Front Facing)
    /// </summary>
    /// <seealso>texture</seealso>
    public Texture2D Texture;

    /// <summary>
    /// Normal scale (default: 1.0f)
    /// </summary>
    /// <seealso>scale</seealso>
    public float Scale;

}
