// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

using System;
using System.Numerics;
using System.Runtime.InteropServices;
using Raylib_cs;

namespace R3D_cs;

/// <summary>
/// Combined Occlusion-Roughness-Metalness (ORM) map.
/// <para>
/// Provides texture and individual multipliers for occlusion, roughness, and metalness.
/// </para>
/// </summary>
/// <remarks>
/// Native: <c>R3D_OrmMap</c>
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public struct OrmMap
{
    /// <summary>
    /// ORM texture (default: WHITE)
    /// </summary>
    /// <remarks>
    /// Native: <c>texture</c>
    /// </remarks>
    public Texture2D Texture;

    /// <summary>
    /// Occlusion multiplier (default: 1.0f)
    /// </summary>
    /// <remarks>
    /// Native: <c>occlusion</c>
    /// </remarks>
    public float Occlusion;

    /// <summary>
    /// Roughness multiplier (default: 1.0f)
    /// </summary>
    /// <remarks>
    /// Native: <c>roughness</c>
    /// </remarks>
    public float Roughness;

    /// <summary>
    /// Metalness multiplier (default: 0.0f)
    /// </summary>
    /// <remarks>
    /// Native: <c>metalness</c>
    /// </remarks>
    public float Metalness;

}
