// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

using System;
using System.Numerics;
using System.Runtime.InteropServices;
using Raylib_cs;

namespace R3D_cs;

/// <summary>
/// Combined Occlusion-Roughness-Metalness (ORM) map.
/// <para>
/// Provides texture and individual multipliers for occlusion, roughness, and metalness.
/// </para>
/// </summary>
/// <seealso>R3D_OrmMap</seealso>
[StructLayout(LayoutKind.Sequential)]
public struct OrmMap
{
    /// <summary>
    /// ORM texture (default: WHITE)
    /// </summary>
    /// <seealso>texture</seealso>
    public Texture2D Texture;

    /// <summary>
    /// Occlusion multiplier (default: 1.0f)
    /// </summary>
    /// <seealso>occlusion</seealso>
    public float Occlusion;

    /// <summary>
    /// Roughness multiplier (default: 1.0f)
    /// </summary>
    /// <seealso>roughness</seealso>
    public float Roughness;

    /// <summary>
    /// Metalness multiplier (default: 0.0f)
    /// </summary>
    /// <seealso>metalness</seealso>
    public float Metalness;

}
