// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

using System;
using System.Numerics;
using System.Runtime.InteropServices;
using Raylib_cs;

namespace R3D_cs;

/// <summary>
/// Penetration information from an overlap test
/// </summary>
/// <remarks>
/// Native: <c>R3D_Penetration</c>
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public struct Penetration
{
    /// <summary>
    /// Whether shapes are overlapping
    /// </summary>
    /// <remarks>
    /// Native: <c>collides</c>
    /// </remarks>
    public bool Collides;

    /// <summary>
    /// Penetration depth
    /// </summary>
    /// <remarks>
    /// Native: <c>depth</c>
    /// </remarks>
    public float Depth;

    /// <summary>
    /// Collision normal (direction to resolve penetration)
    /// </summary>
    /// <remarks>
    /// Native: <c>normal</c>
    /// </remarks>
    public Vector3 Normal;

    /// <summary>
    /// Minimum Translation Vector (normal * depth)
    /// </summary>
    /// <remarks>
    /// Native: <c>mtv</c>
    /// </remarks>
    public Vector3 Mtv;

}
