// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

namespace R3D_cs;

/// <summary>
/// Unique identifier for an R3D probe.
/// <para>
/// Negative values indicate an invalid probe.
/// </para>
/// </summary>
/// <seealso>R3D_Probe</seealso>
public struct Probe
{
    internal int id;

    public static explicit operator int(Probe handle) => handle.id;
    public static explicit operator Probe(int id) => new() { id = id };
}
