// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

using System;
using System.Numerics;
using System.Runtime.InteropServices;
using Raylib_cs;

namespace R3D_cs;

/// <summary>
/// ======================================== OPAQUE TYPES ========================================
/// </summary>
/// <seealso>R3D_ScreenShader</seealso>
[StructLayout(LayoutKind.Sequential)]
public struct ScreenShader
{
}
