// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

using System;
using System.Numerics;
using System.Runtime.InteropServices;
using Raylib_cs;

namespace R3D_cs;

/// <summary>
/// Represents a skeletal hierarchy used for skinning.
/// <para>
/// Defines the bone structure, reference poses, and inverse bind matrices required for skeletal animation. The skeleton provides both local and global bind poses used during skinning and animation playback.
/// </para>
/// </summary>
/// <remarks>
/// Native: <c>R3D_Skeleton</c>
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct Skeleton
{
    /// <summary>
    /// Array of bone descriptors defining the hierarchy and names.
    /// </summary>
    /// <remarks>
    /// Native: <c>bones</c>
    /// </remarks>
    public BoneInfo* Bones;

    /// <summary>
    /// Total number of bones in the skeleton.
    /// </summary>
    /// <remarks>
    /// Native: <c>boneCount</c>
    /// </remarks>
    public int BoneCount;

    /// <summary>
    /// Bind pose matrices relative to parent
    /// </summary>
    /// <remarks>
    /// Native: <c>localBind</c>
    /// </remarks>
    public Matrix4x4* LocalBind;

    /// <summary>
    /// Bind pose matrices in model/global space
    /// </summary>
    /// <remarks>
    /// Native: <c>modelBind</c>
    /// </remarks>
    public Matrix4x4* ModelBind;

    /// <summary>
    /// Inverse bind matrices (model space) for skinning
    /// </summary>
    /// <remarks>
    /// Native: <c>invBind</c>
    /// </remarks>
    public Matrix4x4* InvBind;

    /// <summary>
    /// Root correction if local bind is not identity
    /// </summary>
    /// <remarks>
    /// Native: <c>rootBind</c>
    /// </remarks>
    public Matrix4x4 RootBind;

    /// <summary>
    /// Texture ID that contains the bind pose for GPU skinning. This is a 1D Texture RGBA16F 4*boneCount.
    /// </summary>
    /// <remarks>
    /// Native: <c>skinTexture</c>
    /// </remarks>
    public uint SkinTexture;

}
