// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

using System;
using System.Numerics;
using System.Runtime.InteropServices;
using Raylib_cs;

namespace R3D_cs;

/// <summary>
/// Represents a skeletal hierarchy used for skinning.
/// <para>
/// Defines the bone structure, reference poses, and inverse bind matrices required for skeletal animation. The skeleton provides both local and global bind poses used during skinning and animation playback.
/// </para>
/// </summary>
/// <remarks>
/// Native: <c>R3D_Skeleton</c>
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct Skeleton
{
    /// <summary>
    /// Array of bone descriptors defining the hierarchy and names.
    /// </summary>
    /// <remarks>
    /// Native: <c>bones</c>
    /// </remarks>
    internal BoneInfo* _bones;

    /// <summary>
    /// Total number of bones in the skeleton.
    /// </summary>
    /// <remarks>
    /// Native: <c>boneCount</c>
    /// </remarks>
    public int BoneCount;

    /// <summary>
    /// Bind pose matrices relative to parent
    /// </summary>
    /// <remarks>
    /// Native: <c>localBind</c>
    /// </remarks>
    internal Matrix4x4* _localBind;

    /// <summary>
    /// Bind pose matrices in model/global space
    /// </summary>
    /// <remarks>
    /// Native: <c>modelBind</c>
    /// </remarks>
    internal Matrix4x4* _modelBind;

    /// <summary>
    /// Inverse bind matrices (model space) for skinning
    /// </summary>
    /// <remarks>
    /// Native: <c>invBind</c>
    /// </remarks>
    internal Matrix4x4* _invBind;

    /// <summary>
    /// Root correction if local bind is not identity
    /// </summary>
    /// <remarks>
    /// Native: <c>rootBind</c>
    /// </remarks>
    public Matrix4x4 RootBind;

    /// <summary>
    /// Texture ID that contains the bind pose for GPU skinning. This is a 1D Texture RGBA16F 4*boneCount.
    /// </summary>
    /// <remarks>
    /// Native: <c>skinTexture</c>
    /// </remarks>
    public uint SkinTexture;

    /// <summary>
    /// <see cref="Bones"/> as a <see cref="Span{T}"/>.
    /// </summary>
    public Span<BoneInfo> Bones => _bones != null ? new(_bones, BoneCount) : default;

    /// <summary>
    /// <see cref="LocalBind"/> as a <see cref="Span{T}"/>.
    /// </summary>
    public Span<Matrix4x4> LocalBind => _localBind != null ? new(_localBind, BoneCount) : default;

    /// <summary>
    /// <see cref="ModelBind"/> as a <see cref="Span{T}"/>.
    /// </summary>
    public Span<Matrix4x4> ModelBind => _modelBind != null ? new(_modelBind, BoneCount) : default;

    /// <summary>
    /// <see cref="InvBind"/> as a <see cref="Span{T}"/>.
    /// </summary>
    public Span<Matrix4x4> InvBind => _invBind != null ? new(_invBind, BoneCount) : default;

}
