// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

using System;
using System.Numerics;
using System.Runtime.InteropServices;
using System.Text;
using Raylib_cs;

namespace R3D_cs;

/// <summary>
/// Parameters for animation state machine edge.
/// </summary>
/// <remarks>
/// Native: <c>R3D_StmEdgeParams</c>
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public struct StmEdgeParams
{
    /// <summary>
    /// Operation mode.
    /// </summary>
    /// <remarks>
    /// Native: <c>mode</c>
    /// </remarks>
    public StmEdgeMode Mode;

    /// <summary>
    /// Current travel status.
    /// </summary>
    /// <remarks>
    /// Native: <c>status</c>
    /// </remarks>
    public StmEdgeStatus Status;

    /// <summary>
    /// Travel status used after machine traversed through this edge with status set to R3D_STM_EDGE_ONCE.
    /// </summary>
    /// <remarks>
    /// Native: <c>nextStatus</c>
    /// </remarks>
    public StmEdgeStatus NextStatus;

    /// <summary>
    /// Cross fade blending time between connected animation nodes, in seconds.
    /// </summary>
    /// <remarks>
    /// Native: <c>xFadeTime</c>
    /// </remarks>
    public float XFadeTime;

}
