// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

using System;
using System.Numerics;
using System.Runtime.InteropServices;
using Raylib_cs;

namespace R3D_cs;

/// <summary>
/// Collision information from a sweep test
/// </summary>
/// <seealso>R3D_SweepCollision</seealso>
[StructLayout(LayoutKind.Sequential)]
public struct SweepCollision
{
    /// <summary>
    /// Whether a collision occurred
    /// </summary>
    /// <seealso>hit</seealso>
    public bool Hit;

    /// <summary>
    /// Time of impact [0-1], fraction along velocity vector
    /// </summary>
    /// <seealso>time</seealso>
    public float Time;

    /// <summary>
    /// World space collision point
    /// </summary>
    /// <seealso>point</seealso>
    public Vector3 Point;

    /// <summary>
    /// Surface normal at collision point
    /// </summary>
    /// <seealso>normal</seealso>
    public Vector3 Normal;

}
