// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

using System;
using System.Numerics;
using System.Runtime.InteropServices;
using System.Text;
using Raylib_cs;

namespace R3D_cs;

/// <summary>
/// Parameters for animation tree node Switch.
/// <para>
/// Switch node allows instant or blended/faded transition between any animation nodes connected to inputs.
/// </para>
/// </summary>
/// <remarks>
/// Native: <c>R3D_SwitchNodeParams</c>
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public struct SwitchNodeParams
{
    /// <summary>
    /// Flag to control input animation nodes synchronization; activated input is reset when false.
    /// </summary>
    /// <remarks>
    /// Native: <c>synced</c>
    /// </remarks>
    public bool Synced;

    /// <summary>
    /// Active input zero-based index.
    /// </summary>
    /// <remarks>
    /// Native: <c>activeInput</c>
    /// </remarks>
    public int ActiveInput;

    /// <summary>
    /// Animation nodes cross fade blending time, in seconds.
    /// </summary>
    /// <remarks>
    /// Native: <c>xFadeTime</c>
    /// </remarks>
    public float XFadeTime;

}
