// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

using System;
using System.Numerics;
using System.Runtime.InteropServices;
using System.Text;
using Raylib_cs;

namespace R3D_cs;

/// <summary>
/// Compact vertex format used by R3D meshes.
/// <para>
/// Texture coordinates are stored as float16 values. Normals and tangents are stored as signed normalized 8-bit values. Bone weights are stored as unsigned 8-bit values and should sum to 255.
/// </para>
/// </summary>
/// <remarks>
/// Native: <c>R3D_Vertex</c>
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct Vertex
{
    /// <summary>
    /// Vertex position in object space.
    /// </summary>
    /// <remarks>
    /// Native: <c>position</c>
    /// </remarks>
    public Vector3 Position;

    /// <summary>
    /// Texture coordinates stored as float16.
    /// </summary>
    /// <remarks>
    /// Native: <c>texcoord</c>
    /// </remarks>
    public fixed ushort Texcoord[2];

    /// <summary>
    /// Normal vector stored as SNORM8. XYZ are used, W is unused.
    /// </summary>
    /// <remarks>
    /// Native: <c>normal</c>
    /// </remarks>
    public fixed sbyte Normal[4];

    /// <summary>
    /// Tangent vector stored as SNORM8. XYZ are tangent, W stores handedness.
    /// </summary>
    /// <remarks>
    /// Native: <c>tangent</c>
    /// </remarks>
    public fixed sbyte Tangent[4];

    /// <summary>
    /// Vertex color in RGBA8.
    /// </summary>
    /// <remarks>
    /// Native: <c>color</c>
    /// </remarks>
    public Color Color;

    /// <summary>
    /// Indices of up to 4 bones influencing this vertex.
    /// </summary>
    /// <remarks>
    /// Native: <c>boneIndices</c>
    /// </remarks>
    public fixed byte BoneIndices[4];

    /// <summary>
    /// Bone weights in UNORM8. Values should sum to 255.
    /// </summary>
    /// <remarks>
    /// Native: <c>boneWeights</c>
    /// </remarks>
    public fixed byte BoneWeights[4];

}
