// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

namespace R3D_cs;

/// <summary>
/// Types of events that an animation player can emit.
/// </summary>
/// <remarks>
/// Native: <c>R3D_AnimationEvent</c>
/// </remarks>
public enum AnimationEvent
{
    /// <summary>
    /// Animation has finished playing (non-looping).
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_AnimationEvent.R3D_ANIM_EVENT_FINISHED</c>
    /// </remarks>
    AnimEventFinished,

    /// <summary>
    /// Animation has completed a loop.
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_AnimationEvent.R3D_ANIM_EVENT_LOOPED</c>
    /// </remarks>
    AnimEventLooped,
}
