// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

namespace R3D_cs;

/// <summary>
/// Types of events that an animation player can emit.
/// </summary>
/// <seealso>R3D_AnimationEvent</seealso>
public enum AnimationEvent
{
    /// <summary>
    /// Animation has finished playing (non-looping).
    /// </summary>
    /// <seealso>R3D_AnimationEvent.R3D_ANIM_EVENT_FINISHED</seealso>
    AnimEventFinished,

    /// <summary>
    /// Animation has completed a loop.
    /// </summary>
    /// <seealso>R3D_AnimationEvent.R3D_ANIM_EVENT_LOOPED</seealso>
    AnimEventLooped,
}
