// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

namespace R3D_cs;

/// <summary>
/// Anti-aliasing modes used during rendering.
/// <para>
/// Anti-aliasing reduces visible jagged edges (aliasing artifacts) in the final rendered image.
/// </para>
/// </summary>
/// <remarks>
/// Native: <c>R3D_AntiAliasingMode</c>
/// </remarks>
public enum AntiAliasingMode
{
    /// <summary>
    /// No anti-aliasing. Best performance, visible jagged edges.
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_AntiAliasingMode.R3D_ANTI_ALIASING_MODE_NONE</c>
    /// </remarks>
    None,

    /// <summary>
    /// Fast Approximate AA. Smooths edges efficiently but may appear blurry.
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_AntiAliasingMode.R3D_ANTI_ALIASING_MODE_FXAA</c>
    /// </remarks>
    Fxaa,

    /// <summary>
    /// Subpixel Morphological AA. Sharper than FXAA, moderate performance cost.
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_AntiAliasingMode.R3D_ANTI_ALIASING_MODE_SMAA</c>
    /// </remarks>
    Smaa,
}
