// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

namespace R3D_cs;

/// <summary>
/// Quality presets for anti-aliasing.
/// <para>
/// Presets adjust internal algorithm parameters (e.g. edge detection, search steps, thresholds). Higher presets increase quality and GPU cost.
/// </para>
/// </summary>
/// <remarks>
/// Native: <c>R3D_AntiAliasingPreset</c>
/// </remarks>
public enum AntiAliasingPreset
{
    /// <summary>
    /// Performance-oriented preset with reduced quality.
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_AntiAliasingPreset.R3D_ANTI_ALIASING_PRESET_LOW</c>
    /// </remarks>
    Low,

    /// <summary>
    /// Balanced quality/performance preset.
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_AntiAliasingPreset.R3D_ANTI_ALIASING_PRESET_MEDIUM</c>
    /// </remarks>
    Medium,

    /// <summary>
    /// High quality preset with increased GPU cost.
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_AntiAliasingPreset.R3D_ANTI_ALIASING_PRESET_HIGH</c>
    /// </remarks>
    High,

    /// <summary>
    /// Maximum quality preset, highest performance cost.
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_AntiAliasingPreset.R3D_ANTI_ALIASING_PRESET_ULTRA</c>
    /// </remarks>
    Ultra,

    /// <summary>
    /// Number of presets (not a valid preset value).
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_AntiAliasingPreset.R3D_ANTI_ALIASING_PRESET_COUNT</c>
    /// </remarks>
    Count,
}
