// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

namespace R3D_cs;

/// <summary>
/// Anti-aliasing modes for rendering.
/// </summary>
/// <remarks>
/// Native: <c>R3D_AntiAliasing</c>
/// </remarks>
public enum AntiAliasing
{
    /// <summary>
    /// Anti-aliasing is disabled. Edges may appear jagged.
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_AntiAliasing.R3D_ANTI_ALIASING_DISABLED</c>
    /// </remarks>
    Disabled,

    /// <summary>
    /// FXAA is applied. Smooths edges efficiently but may appear blurry.
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_AntiAliasing.R3D_ANTI_ALIASING_FXAA</c>
    /// </remarks>
    Fxaa,
}
