// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

namespace R3D_cs;

/// <summary>
/// Aspect ratio handling modes for rendering.
/// </summary>
/// <remarks>
/// Native: <c>R3D_AspectMode</c>
/// </remarks>
public enum AspectMode
{
    /// <summary>
    /// Expands the rendered output to fully fill the target (render texture or window).
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_AspectMode.R3D_ASPECT_EXPAND</c>
    /// </remarks>
    Expand,

    /// <summary>
    /// Preserves the target's aspect ratio without distortion, adding empty gaps if necessary.
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_AspectMode.R3D_ASPECT_KEEP</c>
    /// </remarks>
    Keep,
}
