// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

namespace R3D_cs;

/// <summary>
/// Billboard modes.
/// <para>
/// This enumeration defines how a 3D object aligns itself relative to the camera. It provides options to disable billboarding or to enable specific modes of alignment.
/// </para>
/// </summary>
/// <seealso>R3D_BillboardMode</seealso>
public enum BillboardMode
{
    /// <summary>
    /// Billboarding is disabled; the object retains its original orientation.
    /// </summary>
    /// <seealso>R3D_BillboardMode.R3D_BILLBOARD_DISABLED</seealso>
    Disabled,

    /// <summary>
    /// Full billboarding; the object fully faces the camera, rotating on all axes.
    /// </summary>
    /// <seealso>R3D_BillboardMode.R3D_BILLBOARD_FRONT</seealso>
    Front,

    /// <summary>
    /// Y-axis constrained billboarding; the object rotates only around the Y-axis, keeping its &quot;up&quot; orientation fixed. This is suitable for upright objects like characters or signs.
    /// </summary>
    /// <seealso>R3D_BillboardMode.R3D_BILLBOARD_Y_AXIS</seealso>
    YAxis,
}
