// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

namespace R3D_cs;

/// <summary>
/// Bloom effect modes.
/// <para>
/// Different blending methods for the bloom glow effect.
/// </para>
/// </summary>
/// <remarks>
/// Native: <c>R3D_Bloom</c>
/// </remarks>
public enum Bloom
{
    /// <summary>
    /// No bloom effect applied
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_Bloom.R3D_BLOOM_DISABLED</c>
    /// </remarks>
    Disabled,

    /// <summary>
    /// Linear interpolation blend between scene and bloom
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_Bloom.R3D_BLOOM_MIX</c>
    /// </remarks>
    Mix,

    /// <summary>
    /// Additive blending, intensifying bright regions
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_Bloom.R3D_BLOOM_ADDITIVE</c>
    /// </remarks>
    Additive,

    /// <summary>
    /// Screen blending for softer highlight enhancement
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_Bloom.R3D_BLOOM_SCREEN</c>
    /// </remarks>
    Screen,
}
