// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

namespace R3D_cs;

/// <summary>
/// Specifies the color space for user-provided colors and color textures.
/// <para>
/// This enum defines how colors are interpreted for material inputs:
/// <list type="bullet">
/// <item><description>Surface colors (e.g., albedo or emission tint)</description></item>
/// <item><description>Color textures (albedo, emission maps)</description></item>
/// </list>
/// </para>
/// <para>
/// Lighting values (direct or indirect light) are always linear and are not affected by this setting.
/// </para>
/// <para>
/// Used with `R3D_SetColorSpace()` to control whether input colors should be treated as linear or sRGB.
/// </para>
/// </summary>
/// <remarks>
/// Native: <c>R3D_ColorSpace</c>
/// </remarks>
public enum ColorSpace
{
    /// <summary>
    /// Linear color space: values are used as-is.
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_ColorSpace.R3D_COLORSPACE_LINEAR</c>
    /// </remarks>
    Linear,

    /// <summary>
    /// sRGB color space: values are converted to linear on load.
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_ColorSpace.R3D_COLORSPACE_SRGB</c>
    /// </remarks>
    Srgb,
}
