// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

namespace R3D_cs;

/// <summary>
/// Comparison modes.
/// <para>
/// Defines how fragments are tested against the depth/stencil buffer during rendering.
/// </para>
/// </summary>
/// <remarks>
/// The depth/stencil comparison mode affects both forward and deferred rendering passes.
/// Native: <c>R3D_CompareMode</c>
/// </remarks>
public enum CompareMode
{
    /// <summary>
    /// Passes if 'value' &lt; 'buffer' (default)
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_CompareMode.R3D_COMPARE_LESS</c>
    /// </remarks>
    Less,

    /// <summary>
    /// Passes if 'value' &lt; = 'buffer'
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_CompareMode.R3D_COMPARE_LEQUAL</c>
    /// </remarks>
    Lequal,

    /// <summary>
    /// Passes if 'value' == 'buffer'
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_CompareMode.R3D_COMPARE_EQUAL</c>
    /// </remarks>
    Equal,

    /// <summary>
    /// Passes if 'value' &gt;  'buffer'
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_CompareMode.R3D_COMPARE_GREATER</c>
    /// </remarks>
    Greater,

    /// <summary>
    /// Passes if 'value' &gt;= 'buffer'
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_CompareMode.R3D_COMPARE_GEQUAL</c>
    /// </remarks>
    Gequal,

    /// <summary>
    /// Passes if 'value' != 'buffer'
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_CompareMode.R3D_COMPARE_NOTEQUAL</c>
    /// </remarks>
    Notequal,

    /// <summary>
    /// Always passes
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_CompareMode.R3D_COMPARE_ALWAYS</c>
    /// </remarks>
    Always,

    /// <summary>
    /// Never passes
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_CompareMode.R3D_COMPARE_NEVER</c>
    /// </remarks>
    Never,
}
