// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

namespace R3D_cs;

/// <summary>
/// Supported cubemap source layouts.
/// <para>
/// Used when converting an image into a cubemap. AUTO_DETECT tries to guess the layout based on image dimensions.
/// </para>
/// </summary>
/// <remarks>
/// Native: <c>R3D_CubemapLayout</c>
/// </remarks>
public enum CubemapLayout
{
    /// <summary>
    /// Automatically detect layout type
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_CubemapLayout.R3D_CUBEMAP_LAYOUT_AUTO_DETECT</c>
    /// </remarks>
    AutoDetect,

    /// <summary>
    /// Layout is defined by a vertical line with faces
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_CubemapLayout.R3D_CUBEMAP_LAYOUT_LINE_VERTICAL</c>
    /// </remarks>
    LineVertical,

    /// <summary>
    /// Layout is defined by a horizontal line with faces
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_CubemapLayout.R3D_CUBEMAP_LAYOUT_LINE_HORIZONTAL</c>
    /// </remarks>
    LineHorizontal,

    /// <summary>
    /// Layout is defined by a 3x4 cross with cubemap faces
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_CubemapLayout.R3D_CUBEMAP_LAYOUT_CROSS_THREE_BY_FOUR</c>
    /// </remarks>
    CrossThreeByFour,

    /// <summary>
    /// Layout is defined by a 4x3 cross with cubemap faces
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_CubemapLayout.R3D_CUBEMAP_LAYOUT_CROSS_FOUR_BY_THREE</c>
    /// </remarks>
    CrossFourByThree,

    /// <summary>
    /// Layout is defined by an equirectangular panorama
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_CubemapLayout.R3D_CUBEMAP_LAYOUT_PANORAMA</c>
    /// </remarks>
    Panorama,
}
