// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

namespace R3D_cs;

/// <summary>
/// Face culling modes.
/// <para>
/// Specifies which faces of a geometry are discarded during rendering based on their winding order.
/// </para>
/// </summary>
/// <remarks>
/// Native: <c>R3D_CullMode</c>
/// </remarks>
public enum CullMode
{
    /// <summary>
    /// No culling; all faces are rendered.
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_CullMode.R3D_CULL_NONE</c>
    /// </remarks>
    None,

    /// <summary>
    /// Cull back-facing polygons (faces with clockwise winding order).
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_CullMode.R3D_CULL_BACK</c>
    /// </remarks>
    Back,

    /// <summary>
    /// Cull front-facing polygons (faces with counter-clockwise winding order).
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_CullMode.R3D_CULL_FRONT</c>
    /// </remarks>
    Front,
}
