// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

namespace R3D_cs;

/// <summary>
/// Face culling modes.
/// <para>
/// Specifies which faces of a geometry are discarded during rendering based on their winding order.
/// </para>
/// </summary>
/// <seealso>R3D_CullMode</seealso>
public enum CullMode
{
    /// <summary>
    /// No culling; all faces are rendered.
    /// </summary>
    /// <seealso>R3D_CullMode.R3D_CULL_NONE</seealso>
    None,

    /// <summary>
    /// Cull back-facing polygons (faces with clockwise winding order).
    /// </summary>
    /// <seealso>R3D_CullMode.R3D_CULL_BACK</seealso>
    Back,

    /// <summary>
    /// Cull front-facing polygons (faces with counter-clockwise winding order).
    /// </summary>
    /// <seealso>R3D_CullMode.R3D_CULL_FRONT</seealso>
    Front,
}
