// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

namespace R3D_cs;

/// <summary>
/// Depth of field modes.
/// </summary>
/// <seealso>R3D_DoF</seealso>
public enum DoF
{
    /// <summary>
    /// No depth of field effect
    /// </summary>
    /// <seealso>R3D_DoF.R3D_DOF_DISABLED</seealso>
    Disabled,

    /// <summary>
    /// Depth of field enabled with focus point and blur
    /// </summary>
    /// <seealso>R3D_DoF.R3D_DOF_ENABLED</seealso>
    Enabled,
}
