// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

namespace R3D_cs;

/// <summary>
/// Depth of field modes.
/// </summary>
/// <remarks>
/// Native: <c>R3D_DoF</c>
/// </remarks>
public enum DoF
{
    /// <summary>
    /// No depth of field effect
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_DoF.R3D_DOF_DISABLED</c>
    /// </remarks>
    Disabled,

    /// <summary>
    /// Depth of field enabled with focus point and blur
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_DoF.R3D_DOF_ENABLED</c>
    /// </remarks>
    Enabled,
}
