// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

namespace R3D_cs;

/// <summary>
/// Downscaling/filtering methods for rendering output.
/// <para>
/// Downscale mode to apply when the output window is smaller than the internal render resolution.
/// </para>
/// </summary>
/// <remarks>
/// Native: <c>R3D_DownscaleMode</c>
/// </remarks>
public enum DownscaleMode
{
    /// <summary>
    /// Nearest-neighbor downscaling: very fast, but produces aliasing.
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_DownscaleMode.R3D_DOWNSCALE_NEAREST</c>
    /// </remarks>
    Nearest,

    /// <summary>
    /// Bilinear filtering. Fast, may show moire on high-frequency content.
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_DownscaleMode.R3D_DOWNSCALE_LINEAR</c>
    /// </remarks>
    Linear,

    /// <summary>
    /// 4-sample supersampling. Reduces aliasing and moire, low cost. Recommended default.
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_DownscaleMode.R3D_DOWNSCALE_RGSS</c>
    /// </remarks>
    Rgss,

    /// <summary>
    /// 16-sample supersampling. Better color accuracy than RGSS, higher cost.
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_DownscaleMode.R3D_DOWNSCALE_PDSS</c>
    /// </remarks>
    Pdss,
}
