// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

namespace R3D_cs;

/// <summary>
/// Downscaling/filtering methods for rendering output.
/// <para>
/// Downscale mode to apply when the output window is smaller than the internal render resolution.
/// </para>
/// </summary>
/// <seealso>R3D_DownscaleMode</seealso>
public enum DownscaleMode
{
    /// <summary>
    /// Nearest-neighbor downscaling: very fast, but produces aliasing.
    /// </summary>
    /// <seealso>R3D_DownscaleMode.R3D_DOWNSCALE_NEAREST</seealso>
    Nearest,

    /// <summary>
    /// Bilinear downscaling: very fast, can serve as a basic form of anti-aliasing (SSAA).
    /// </summary>
    /// <seealso>R3D_DownscaleMode.R3D_DOWNSCALE_LINEAR</seealso>
    Linear,

    /// <summary>
    /// Box-blur downscaling: uses a simple but effective box blur, slightly more expensive than linear, smooths moiré better.
    /// </summary>
    /// <seealso>R3D_DownscaleMode.R3D_DOWNSCALE_BOX</seealso>
    Box,
}
