// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

namespace R3D_cs;

/// <summary>
/// Fog effect modes.
/// <para>
/// Distance-based fog density distribution methods.
/// </para>
/// </summary>
/// <seealso>R3D_Fog</seealso>
public enum Fog
{
    /// <summary>
    /// No fog effect
    /// </summary>
    /// <seealso>R3D_Fog.R3D_FOG_DISABLED</seealso>
    Disabled,

    /// <summary>
    /// Linear density increase between start and end distances
    /// </summary>
    /// <seealso>R3D_Fog.R3D_FOG_LINEAR</seealso>
    Linear,

    /// <summary>
    /// Exponential squared density (exp2), more realistic
    /// </summary>
    /// <seealso>R3D_Fog.R3D_FOG_EXP2</seealso>
    EXP2,

    /// <summary>
    /// Simple exponential density increase
    /// </summary>
    /// <seealso>R3D_Fog.R3D_FOG_EXP</seealso>
    Exp,
}
