// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

using System;
using System.Numerics;
using System.Runtime.InteropServices;
using Raylib_cs;

namespace R3D_cs;

/// <summary>
/// Flags controlling importer behavior.
/// <para>
/// These flags define how the importer processes the source asset.
/// </para>
/// </summary>
/// <remarks>
/// Native: <c>R3D_ImportFlags</c>
/// </remarks>
[Flags]
public enum ImportFlags : uint
{
    /// <summary>
    /// When enabled, raw mesh data is preserved in RAM after model import.
    /// </summary>
    /// <remarks>Native: <c>R3D_IMPORT_MESH_DATA</c></remarks>
    MeshData = (1<<0),

    /// <summary>
    /// When disabled, a faster import preset is used, suitable for runtime.
    /// </summary>
    /// <remarks>Native: <c>R3D_IMPORT_QUALITY</c></remarks>
    Quality = (1<<1),
}
