// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

using System;
using System.Numerics;
using System.Runtime.InteropServices;
using Raylib_cs;

namespace R3D_cs;

/// <summary>
/// Bitmask defining which instance attributes are present.
/// </summary>
/// <seealso>R3D_InstanceFlags</seealso>
[Flags]
public enum InstanceFlags
{
    /// <summary>Vector3</summary>
    /// <seealso>R3D_INSTANCE_POSITION</seealso>
    Position = (1<<0),

    /// <summary>Quaternion</summary>
    /// <seealso>R3D_INSTANCE_ROTATION</seealso>
    Rotation = (1<<1),

    /// <summary>Vector3</summary>
    /// <seealso>R3D_INSTANCE_SCALE</seealso>
    Scale = (1<<2),

    /// <summary>Color</summary>
    /// <seealso>R3D_INSTANCE_COLOR</seealso>
    Color = (1<<3),

    /// <summary>Vector4</summary>
    /// <seealso>R3D_INSTANCE_CUSTOM</seealso>
    Custom = (1<<4),
}
