// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

using System;
using System.Numerics;
using System.Runtime.InteropServices;
using Raylib_cs;

namespace R3D_cs;

/// <summary>
/// Bitmask defining which instance attributes are present.
/// <para>
/// Each bit enables one per-instance attribute stream. Attribute data is stored in separate GPU buffers, one buffer per enabled attribute.
/// </para>
/// <para>
/// The memory format of each enabled attribute is defined by `R3D_InstanceLayout`. In shaders, these attributes are exposed as floating-point vectors, including normalized integer formats such as UNORM/SNORM.
/// </para>
/// </summary>
/// <remarks>
/// Native: <c>R3D_InstanceFlags</c>
/// </remarks>
[Flags]
public enum InstanceFlags : uint
{
    /// <summary>Position attribute: 3 components</summary>
    /// <remarks>Native: <c>R3D_INSTANCE_POSITION</c></remarks>
    Position = (1u<<0),

    /// <summary>Rotation attribute: 4 components (quaternion)</summary>
    /// <remarks>Native: <c>R3D_INSTANCE_ROTATION</c></remarks>
    Rotation = (1u<<1),

    /// <summary>Scale attribute: 3 components</summary>
    /// <remarks>Native: <c>R3D_INSTANCE_SCALE</c></remarks>
    Scale = (1u<<2),

    /// <summary>Color attribute: 4 components</summary>
    /// <remarks>Native: <c>R3D_INSTANCE_COLOR</c></remarks>
    Color = (1u<<3),

    /// <summary>Custom attribute: 4 components</summary>
    /// <remarks>Native: <c>R3D_INSTANCE_CUSTOM</c></remarks>
    Custom = (1u<<4),
}
