// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

namespace R3D_cs;

/// <summary>
/// Storage format used by an instance attribute.
/// <para>
/// The selected format controls how the attribute is stored in GPU memory. All formats are read by the shader as floating-point values.
/// </para>
/// <para>
/// UNORM formats are converted to the [0, 1] range. SNORM formats are converted to the [-1, 1] range.
/// </para>
/// </summary>
/// <remarks>
/// Native: <c>R3D_InstanceFormat</c>
/// </remarks>
public enum InstanceFormat
{
    /// <summary>
    /// 32-bit floating-point component.
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_InstanceFormat.R3D_INSTANCE_FORMAT_FLOAT32</c>
    /// </remarks>
    FLOAT32,

    /// <summary>
    /// 16-bit floating-point component.
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_InstanceFormat.R3D_INSTANCE_FORMAT_FLOAT16</c>
    /// </remarks>
    FLOAT16,

    /// <summary>
    /// 16-bit unsigned normalized component.
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_InstanceFormat.R3D_INSTANCE_FORMAT_UNORM16</c>
    /// </remarks>
    UNORM16,

    /// <summary>
    /// 16-bit signed normalized component.
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_InstanceFormat.R3D_INSTANCE_FORMAT_SNORM16</c>
    /// </remarks>
    SNORM16,

    /// <summary>
    /// 8-bit unsigned normalized component.
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_InstanceFormat.R3D_INSTANCE_FORMAT_UNORM8</c>
    /// </remarks>
    UNORM8,

    /// <summary>
    /// 8-bit signed normalized component.
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_InstanceFormat.R3D_INSTANCE_FORMAT_SNORM8</c>
    /// </remarks>
    SNORM8,

    /// <summary>
    /// Number of available instance formats.
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_InstanceFormat.R3D_INSTANCE_FORMAT_COUNT</c>
    /// </remarks>
    Count,
}
