// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

using System;
using System.Numerics;
using System.Runtime.InteropServices;
using Raylib_cs;

namespace R3D_cs;

/// <summary>
/// Bitmask defining which instance attributes are present.
/// </summary>
/// <remarks>
/// Native: <c>R3D_InstanceFlags</c>
/// </remarks>
[Flags]
public enum InstanceFlags
{
    /// <summary>Vector3</summary>
    /// <remarks>Native: <c>R3D_INSTANCE_POSITION</c></remarks>
    Position = (1<<0),

    /// <summary>Quaternion</summary>
    /// <remarks>Native: <c>R3D_INSTANCE_ROTATION</c></remarks>
    Rotation = (1<<1),

    /// <summary>Vector3</summary>
    /// <remarks>Native: <c>R3D_INSTANCE_SCALE</c></remarks>
    Scale = (1<<2),

    /// <summary>Color</summary>
    /// <remarks>Native: <c>R3D_INSTANCE_COLOR</c></remarks>
    Color = (1<<3),

    /// <summary>Vector4</summary>
    /// <remarks>Native: <c>R3D_INSTANCE_CUSTOM</c></remarks>
    Custom = (1<<4),
}
