// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

using System;
using System.Numerics;
using System.Runtime.InteropServices;
using Raylib_cs;

namespace R3D_cs;

/// <summary>
/// Bitfield type used to specify rendering layers.
/// <para>
/// This type is used by cameras and renderable objects to control visibility. A renderable object is visible to a camera when at least one bit is shared between the object's layer mask and the camera's layer mask.
/// </para>
/// <para>
/// For convenience, 16 predefined layers are provided here, but the underlying type supports up to 32 layers.
/// </para>
/// </summary>
/// <remarks>
/// Native: <c>R3D_Layer</c>
/// </remarks>
[Flags]
public enum Layer : uint
{
    /// <remarks>Native: <c>R3D_LAYER_01</c></remarks>
    Layer01 = (1u<<0),

    /// <remarks>Native: <c>R3D_LAYER_02</c></remarks>
    Layer02 = (1u<<1),

    /// <remarks>Native: <c>R3D_LAYER_03</c></remarks>
    Layer03 = (1u<<2),

    /// <remarks>Native: <c>R3D_LAYER_04</c></remarks>
    Layer04 = (1u<<3),

    /// <remarks>Native: <c>R3D_LAYER_05</c></remarks>
    Layer05 = (1u<<4),

    /// <remarks>Native: <c>R3D_LAYER_06</c></remarks>
    Layer06 = (1u<<5),

    /// <remarks>Native: <c>R3D_LAYER_07</c></remarks>
    Layer07 = (1u<<6),

    /// <remarks>Native: <c>R3D_LAYER_08</c></remarks>
    Layer08 = (1u<<7),

    /// <remarks>Native: <c>R3D_LAYER_09</c></remarks>
    Layer09 = (1u<<8),

    /// <remarks>Native: <c>R3D_LAYER_10</c></remarks>
    Layer10 = (1u<<9),

    /// <remarks>Native: <c>R3D_LAYER_11</c></remarks>
    Layer11 = (1u<<10),

    /// <remarks>Native: <c>R3D_LAYER_12</c></remarks>
    Layer12 = (1u<<11),

    /// <remarks>Native: <c>R3D_LAYER_13</c></remarks>
    Layer13 = (1u<<12),

    /// <remarks>Native: <c>R3D_LAYER_14</c></remarks>
    Layer14 = (1u<<13),

    /// <remarks>Native: <c>R3D_LAYER_15</c></remarks>
    Layer15 = (1u<<14),

    /// <remarks>Native: <c>R3D_LAYER_16</c></remarks>
    Layer16 = (1u<<15),

    /// <remarks>Native: <c>R3D_LAYER_ALL</c></remarks>
    All = 0xFFFFFFFF,
}
