// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

namespace R3D_cs;

/// <summary>
/// Types of lights supported by the rendering engine.
/// <para>
/// Each light type has different behaviors and use cases.
/// </para>
/// </summary>
/// <remarks>
/// Native: <c>R3D_LightType</c>
/// </remarks>
public enum LightType
{
    /// <summary>
    /// Directional light, affects the entire scene with parallel rays.
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_LightType.R3D_LIGHT_DIR</c>
    /// </remarks>
    Dir,

    /// <summary>
    /// Spot light, emits light in a cone shape.
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_LightType.R3D_LIGHT_SPOT</c>
    /// </remarks>
    Spot,

    /// <summary>
    /// Omni light, emits light in all directions from a single point.
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_LightType.R3D_LIGHT_OMNI</c>
    /// </remarks>
    Omni,

    /// <remarks>Native: <c>R3D_LightType.R3D_LIGHT_TYPE_COUNT</c></remarks>
    TypeCount,
}
