// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

namespace R3D_cs;

/// <summary>
/// Types of lights supported by the rendering engine.
/// <para>
/// Each light type has different behaviors and use cases.
/// </para>
/// </summary>
/// <seealso>R3D_LightType</seealso>
public enum LightType
{
    /// <summary>
    /// Directional light, affects the entire scene with parallel rays.
    /// </summary>
    /// <seealso>R3D_LightType.R3D_LIGHT_DIR</seealso>
    Dir,

    /// <summary>
    /// Spot light, emits light in a cone shape.
    /// </summary>
    /// <seealso>R3D_LightType.R3D_LIGHT_SPOT</seealso>
    Spot,

    /// <summary>
    /// Omni light, emits light in all directions from a single point.
    /// </summary>
    /// <seealso>R3D_LightType.R3D_LIGHT_OMNI</seealso>
    Omni,

    /// <seealso>R3D_LightType.R3D_LIGHT_TYPE_COUNT</seealso>
    TypeCount,
}
