// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

namespace R3D_cs;

/// <summary>
/// Hint on how a mesh will be used.
/// </summary>
/// <seealso>R3D_MeshUsage</seealso>
public enum MeshUsage
{
    /// <summary>
    /// Will never be updated.
    /// </summary>
    /// <seealso>R3D_MeshUsage.R3D_STATIC_MESH</seealso>
    StaticMesh,

    /// <summary>
    /// Will be updated occasionally.
    /// </summary>
    /// <seealso>R3D_MeshUsage.R3D_DYNAMIC_MESH</seealso>
    DynamicMesh,

    /// <summary>
    /// Will be update on each frame.
    /// </summary>
    /// <seealso>R3D_MeshUsage.R3D_STREAMED_MESH</seealso>
    StreamedMesh,
}
