// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

namespace R3D_cs;

/// <summary>
/// Defines the buffer to output (render texture or window).
/// </summary>
/// <remarks>
/// Nothing will be output if the requested target has not been created / used.
/// </remarks>
/// <seealso>R3D_OutputMode</seealso>
public enum OutputMode
{
    /// <seealso>R3D_OutputMode.R3D_OUTPUT_SCENE</seealso>
    Scene,

    /// <seealso>R3D_OutputMode.R3D_OUTPUT_ALBEDO</seealso>
    Albedo,

    /// <seealso>R3D_OutputMode.R3D_OUTPUT_NORMAL</seealso>
    Normal,

    /// <seealso>R3D_OutputMode.R3D_OUTPUT_ORM</seealso>
    Orm,

    /// <seealso>R3D_OutputMode.R3D_OUTPUT_DIFFUSE</seealso>
    Diffuse,

    /// <seealso>R3D_OutputMode.R3D_OUTPUT_SPECULAR</seealso>
    Specular,

    /// <seealso>R3D_OutputMode.R3D_OUTPUT_SSAO</seealso>
    Ssao,

    /// <seealso>R3D_OutputMode.R3D_OUTPUT_SSIL</seealso>
    Ssil,

    /// <seealso>R3D_OutputMode.R3D_OUTPUT_SSR</seealso>
    Ssr,

    /// <seealso>R3D_OutputMode.R3D_OUTPUT_BLOOM</seealso>
    Bloom,
}
