// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

namespace R3D_cs;

/// <summary>
/// Defines the geometric primitive type.
/// </summary>
/// <remarks>
/// Native: <c>R3D_PrimitiveType</c>
/// </remarks>
public enum PrimitiveType
{
    /// <summary>
    /// Each vertex represents a single point.
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_PrimitiveType.R3D_PRIMITIVE_POINTS</c>
    /// </remarks>
    Points,

    /// <summary>
    /// Each pair of vertices forms an independent line segment.
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_PrimitiveType.R3D_PRIMITIVE_LINES</c>
    /// </remarks>
    Lines,

    /// <summary>
    /// Connected series of line segments sharing vertices.
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_PrimitiveType.R3D_PRIMITIVE_LINE_STRIP</c>
    /// </remarks>
    LineStrip,

    /// <summary>
    /// Closed loop of connected line segments.
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_PrimitiveType.R3D_PRIMITIVE_LINE_LOOP</c>
    /// </remarks>
    LineLoop,

    /// <summary>
    /// Each set of three vertices forms an independent triangle.
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_PrimitiveType.R3D_PRIMITIVE_TRIANGLES</c>
    /// </remarks>
    Triangles,

    /// <summary>
    /// Connected strip of triangles sharing vertices.
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_PrimitiveType.R3D_PRIMITIVE_TRIANGLE_STRIP</c>
    /// </remarks>
    TriangleStrip,

    /// <summary>
    /// Fan of triangles sharing the first vertex.
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_PrimitiveType.R3D_PRIMITIVE_TRIANGLE_FAN</c>
    /// </remarks>
    TriangleFan,
}
