// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

namespace R3D_cs;

/// <summary>
/// Defines the geometric primitive type.
/// </summary>
/// <seealso>R3D_PrimitiveType</seealso>
public enum PrimitiveType
{
    /// <summary>
    /// Each vertex represents a single point.
    /// </summary>
    /// <seealso>R3D_PrimitiveType.R3D_PRIMITIVE_POINTS</seealso>
    Points,

    /// <summary>
    /// Each pair of vertices forms an independent line segment.
    /// </summary>
    /// <seealso>R3D_PrimitiveType.R3D_PRIMITIVE_LINES</seealso>
    Lines,

    /// <summary>
    /// Connected series of line segments sharing vertices.
    /// </summary>
    /// <seealso>R3D_PrimitiveType.R3D_PRIMITIVE_LINE_STRIP</seealso>
    LineStrip,

    /// <summary>
    /// Closed loop of connected line segments.
    /// </summary>
    /// <seealso>R3D_PrimitiveType.R3D_PRIMITIVE_LINE_LOOP</seealso>
    LineLoop,

    /// <summary>
    /// Each set of three vertices forms an independent triangle.
    /// </summary>
    /// <seealso>R3D_PrimitiveType.R3D_PRIMITIVE_TRIANGLES</seealso>
    Triangles,

    /// <summary>
    /// Connected strip of triangles sharing vertices.
    /// </summary>
    /// <seealso>R3D_PrimitiveType.R3D_PRIMITIVE_TRIANGLE_STRIP</seealso>
    TriangleStrip,

    /// <summary>
    /// Fan of triangles sharing the first vertex.
    /// </summary>
    /// <seealso>R3D_PrimitiveType.R3D_PRIMITIVE_TRIANGLE_FAN</seealso>
    TriangleFan,
}
