// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

using System;
using System.Numerics;
using System.Runtime.InteropServices;
using Raylib_cs;

namespace R3D_cs;

/// <summary>
/// Bit-flags controlling what components are generated.
/// <para>
/// <list type="bullet">
/// <item><description>R3D_PROBE_ILLUMINATION -&gt; generate diffuse irradiance</description></item>
/// <item><description>R3D_PROBE_REFLECTION   -&gt; generate specular prefiltered map</description></item>
/// </list>
/// </para>
/// </summary>
/// <seealso>R3D_ProbeFlags</seealso>
[Flags]
public enum ProbeFlags : uint
{
    /// <seealso>R3D_PROBE_ILLUMINATION</seealso>
    Illumination = (1<<0),

    /// <seealso>R3D_PROBE_REFLECTION</seealso>
    Reflection = (1<<1),
}
