// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

using System;
using System.Numerics;
using System.Runtime.InteropServices;
using Raylib_cs;

namespace R3D_cs;

/// <summary>
/// Bit-flags controlling what components are generated.
/// <para>
/// <list type="bullet">
/// <item><description>R3D_PROBE_ILLUMINATION -&gt; generate diffuse irradiance</description></item>
/// <item><description>R3D_PROBE_REFLECTION   -&gt; generate specular prefiltered map</description></item>
/// </list>
/// </para>
/// </summary>
/// <remarks>
/// Native: <c>R3D_ProbeFlags</c>
/// </remarks>
[Flags]
public enum ProbeFlags : uint
{
    /// <remarks>Native: <c>R3D_PROBE_ILLUMINATION</c></remarks>
    Illumination = (1<<0),

    /// <remarks>Native: <c>R3D_PROBE_REFLECTION</c></remarks>
    Reflection = (1<<1),
}
