// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

namespace R3D_cs;

/// <summary>
/// Projection mode used by an R3D camera.
/// </summary>
/// <remarks>
/// Native: <c>R3D_Projection</c>
/// </remarks>
public enum Projection
{
    /// <summary>
    /// Perspective projection.
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_Projection.R3D_PROJECTION_PERSPECTIVE</c>
    /// </remarks>
    Perspective,

    /// <summary>
    /// Orthographic projection.
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_Projection.R3D_PROJECTION_ORTHOGRAPHIC</c>
    /// </remarks>
    Orthographic,
}
