// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

namespace R3D_cs;

/// <summary>
/// Modes for updating shadow maps.
/// <para>
/// Determines how often the shadow maps are refreshed.
/// </para>
/// </summary>
/// <seealso>R3D_ShadowUpdateMode</seealso>
public enum ShadowUpdateMode
{
    /// <summary>
    /// Shadow maps update only when explicitly requested.
    /// </summary>
    /// <seealso>R3D_ShadowUpdateMode.R3D_SHADOW_UPDATE_MANUAL</seealso>
    Manual,

    /// <summary>
    /// Shadow maps update at defined time intervals.
    /// </summary>
    /// <seealso>R3D_ShadowUpdateMode.R3D_SHADOW_UPDATE_INTERVAL</seealso>
    Interval,

    /// <summary>
    /// Shadow maps update every frame for real-time accuracy.
    /// </summary>
    /// <seealso>R3D_ShadowUpdateMode.R3D_SHADOW_UPDATE_CONTINUOUS</seealso>
    Continuous,
}
