// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

namespace R3D_cs;

/// <summary>
/// Modes for updating shadow maps.
/// <para>
/// Determines how often the shadow maps are refreshed.
/// </para>
/// </summary>
/// <remarks>
/// Native: <c>R3D_ShadowUpdateMode</c>
/// </remarks>
public enum ShadowUpdateMode
{
    /// <summary>
    /// Shadow maps update only when explicitly requested.
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_ShadowUpdateMode.R3D_SHADOW_UPDATE_MANUAL</c>
    /// </remarks>
    Manual,

    /// <summary>
    /// Shadow maps update at defined time intervals.
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_ShadowUpdateMode.R3D_SHADOW_UPDATE_INTERVAL</c>
    /// </remarks>
    Interval,

    /// <summary>
    /// Shadow maps update every frame for real-time accuracy.
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_ShadowUpdateMode.R3D_SHADOW_UPDATE_CONTINUOUS</c>
    /// </remarks>
    Continuous,
}
