// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

namespace R3D_cs;

/// <summary>
/// Stencil buffer operations.
/// <para>
/// Defines how the stencil buffer value is modified based on test results.
/// </para>
/// </summary>
/// <remarks>
/// Native: <c>R3D_StencilOp</c>
/// </remarks>
public enum StencilOp
{
    /// <summary>
    /// Keep the current stencil value
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_StencilOp.R3D_STENCIL_KEEP</c>
    /// </remarks>
    StencilKeep,

    /// <summary>
    /// Set stencil value to 0
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_StencilOp.R3D_STENCIL_ZERO</c>
    /// </remarks>
    StencilZero,

    /// <summary>
    /// Replace with reference value
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_StencilOp.R3D_STENCIL_REPLACE</c>
    /// </remarks>
    StencilReplace,

    /// <summary>
    /// Increment stencil value (clamped)
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_StencilOp.R3D_STENCIL_INCR</c>
    /// </remarks>
    StencilIncr,

    /// <summary>
    /// Decrement stencil value (clamped)
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_StencilOp.R3D_STENCIL_DECR</c>
    /// </remarks>
    StencilDecr,
}
