// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

namespace R3D_cs;

/// <summary>
/// Types of travel status for state machine edge.
/// </summary>
/// <remarks>
/// Native: <c>R3D_StmEdgeStatus</c>
/// </remarks>
public enum StmEdgeStatus
{
    /// <summary>
    /// Edge is traversable by travel function.
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_StmEdgeStatus.R3D_STM_EDGE_ON</c>
    /// </remarks>
    On,

    /// <summary>
    /// Edge is traversable automatically and by travel function.
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_StmEdgeStatus.R3D_STM_EDGE_AUTO</c>
    /// </remarks>
    Auto,

    /// <summary>
    /// Edge is traversable automatically and by travel function, but only once; edge status changes to nextStatus when traversed.
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_StmEdgeStatus.R3D_STM_EDGE_ONCE</c>
    /// </remarks>
    Once,

    /// <summary>
    /// Edge is not traversable.
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_StmEdgeStatus.R3D_STM_EDGE_OFF</c>
    /// </remarks>
    Off,
}
