// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

namespace R3D_cs;

/// <summary>
/// Types of operation modes for state machine edge.
/// </summary>
/// <remarks>
/// Native: <c>R3D_StmEdgeMode</c>
/// </remarks>
public enum StmEdgeMode
{
    /// <summary>
    /// Switch to next state instantly, with respecting cross fade time.
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_StmEdgeMode.R3D_STM_EDGE_INSTANT</c>
    /// </remarks>
    Instant,

    /// <summary>
    /// Switch to next state when associated animation is done or looped with looper parameter set true.
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_StmEdgeMode.R3D_STM_EDGE_ONDONE</c>
    /// </remarks>
    Ondone,
}
