// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

namespace R3D_cs;

/// <summary>
/// Tone mapping algorithms.
/// <para>
/// HDR to LDR color compression methods.
/// </para>
/// </summary>
/// <remarks>
/// Native: <c>R3D_Tonemap</c>
/// </remarks>
public enum Tonemap
{
    /// <summary>
    /// Direct linear mapping (no compression)
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_Tonemap.R3D_TONEMAP_LINEAR</c>
    /// </remarks>
    Linear,

    /// <summary>
    /// Reinhard operator, balanced HDR compression
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_Tonemap.R3D_TONEMAP_REINHARD</c>
    /// </remarks>
    Reinhard,

    /// <summary>
    /// Film-like response curve
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_Tonemap.R3D_TONEMAP_FILMIC</c>
    /// </remarks>
    Filmic,

    /// <summary>
    /// Academy Color Encoding System (cinematic standard)
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_Tonemap.R3D_TONEMAP_ACES</c>
    /// </remarks>
    Aces,

    /// <summary>
    /// Modern algorithm preserving highlights and shadows
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_Tonemap.R3D_TONEMAP_AGX</c>
    /// </remarks>
    Agx,

    /// <summary>
    /// Internal: number of tonemap modes
    /// </summary>
    /// <remarks>
    /// Native: <c>R3D_Tonemap.R3D_TONEMAP_COUNT</c>
    /// </remarks>
    Count,
}
