// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

namespace R3D_cs;

/// <summary>
/// Tone mapping algorithms.
/// <para>
/// HDR to LDR color compression methods.
/// </para>
/// </summary>
/// <seealso>R3D_Tonemap</seealso>
public enum Tonemap
{
    /// <summary>
    /// Direct linear mapping (no compression)
    /// </summary>
    /// <seealso>R3D_Tonemap.R3D_TONEMAP_LINEAR</seealso>
    Linear,

    /// <summary>
    /// Reinhard operator, balanced HDR compression
    /// </summary>
    /// <seealso>R3D_Tonemap.R3D_TONEMAP_REINHARD</seealso>
    Reinhard,

    /// <summary>
    /// Film-like response curve
    /// </summary>
    /// <seealso>R3D_Tonemap.R3D_TONEMAP_FILMIC</seealso>
    Filmic,

    /// <summary>
    /// Academy Color Encoding System (cinematic standard)
    /// </summary>
    /// <seealso>R3D_Tonemap.R3D_TONEMAP_ACES</seealso>
    Aces,

    /// <summary>
    /// Modern algorithm preserving highlights and shadows
    /// </summary>
    /// <seealso>R3D_Tonemap.R3D_TONEMAP_AGX</seealso>
    Agx,

    /// <summary>
    /// Internal: number of tonemap modes
    /// </summary>
    /// <seealso>R3D_Tonemap.R3D_TONEMAP_COUNT</seealso>
    Count,
}
