// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

namespace R3D_cs;

/// <summary>
/// Transparency modes.
/// <para>
/// This enumeration defines how a material handles transparency during rendering. It controls whether transparency is disabled, rendered using a depth pre-pass, or rendered with standard alpha blending.
/// </para>
/// </summary>
/// <seealso>R3D_TransparencyMode</seealso>
public enum TransparencyMode
{
    /// <summary>
    /// No transparency, supports alpha cutoff.
    /// </summary>
    /// <seealso>R3D_TransparencyMode.R3D_TRANSPARENCY_DISABLED</seealso>
    Disabled,

    /// <summary>
    /// Supports transparency with shadows. Writes shadows for alpha &gt; 0.1 and depth for alpha &gt; 0.99.
    /// </summary>
    /// <seealso>R3D_TransparencyMode.R3D_TRANSPARENCY_PREPASS</seealso>
    Prepass,

    /// <summary>
    /// Standard transparency without shadows or depth writes.
    /// </summary>
    /// <seealso>R3D_TransparencyMode.R3D_TRANSPARENCY_ALPHA</seealso>
    Alpha,
}
