// Auto-generated by R3D-cs.GenerateBindings
// Do not edit manually

namespace R3D_cs;

/// <summary>
/// Upscaling/filtering methods for rendering output.
/// <para>
/// Upscale mode to apply when the output window is larger than the internal render resolution.
/// </para>
/// </summary>
/// <seealso>R3D_UpscaleMode</seealso>
public enum UpscaleMode
{
    /// <summary>
    /// Nearest-neighbor upscaling: very fast, but produces blocky pixels.
    /// </summary>
    /// <seealso>R3D_UpscaleMode.R3D_UPSCALE_NEAREST</seealso>
    Nearest,

    /// <summary>
    /// Bilinear upscaling: very fast, smoother than nearest, but can appear blurry.
    /// </summary>
    /// <seealso>R3D_UpscaleMode.R3D_UPSCALE_LINEAR</seealso>
    Linear,

    /// <summary>
    /// Bicubic (Catmull-Rom) upscaling: slower, smoother, and less blurry than linear.
    /// </summary>
    /// <seealso>R3D_UpscaleMode.R3D_UPSCALE_BICUBIC</seealso>
    Bicubic,

    /// <summary>
    /// Lanczos-2 upscaling: preserves more fine details, but is the most expensive.
    /// </summary>
    /// <seealso>R3D_UpscaleMode.R3D_UPSCALE_LANCZOS</seealso>
    Lanczos,
}
